// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

enum FeatureStrings {
    static func clipboard(_ language: AppLanguage) -> ClipboardFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }

    static func monitorAlerts(_ language: AppLanguage) -> MonitorAlertFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }

    static func whatsAppDownloads(_ language: AppLanguage) -> WhatsAppDownloadStrings {
        WhatsAppDownloadStrings.localized(language)
    }
}

extension ClipboardFeatureStrings {
    static let ko = ClipboardFeatureStrings(
        title: "클립보드",
        enable: "클립보드 기록 저장",
        caption: "복사한 텍스트를 저장하여 나중에 다시 사용할 수 있습니다. 모든 항목은 로컬에 보관되며 언제든 지울 수 있습니다.",
        localNote: "모든 항목은 이 Mac에만 저장됩니다. 너무 큰 항목은 무시됩니다.",
        skipSensitive: "민감해 보이는 텍스트 건너뛰기",
        skipSensitiveCaption: "암호, 토큰, 키처럼 보이는 짧고 공백 없는 문자열을 저장하지 않습니다.",
        limit: "제한",
        limitUnlimited: "무제한",
        showInPanel: "패널에 표시",
        shortcut: "기록 단축키",
        shortcutCaption: "검색, 고정 항목 및 이전 앱에 붙여넣기 위한 ⌘1~⌘9 단축키가 있는 빠른 윈도우를 엽니다.",
        shortcutHint: "행을 클릭하면 이전 앱에 붙여넣습니다. ⌘-클릭으로 여러 항목을 선택하고, ⌘C로 붙여넣지 않고 복사합니다.",
        clickRowShortcut: "행 클릭",
        commandClickShortcut: "⌘ 클릭",
        pinned: "고정됨",
        recent: "최근 항목",
        pin: "고정",
        unpin: "고정 해제",
        clearRecent: "최근 항목 지우기",
        clearAll: "고정되지 않은 항목 지우기",
        empty: "저장한 텍스트가 없습니다",
        disabled: "복사한 텍스트를 저장하려면 기록을 켜세요.",
        search: "복사한 텍스트 검색",
        copy: "복사",
        copied: "복사됨",
        delete: "항목 삭제",
        selectMultiple: "묶음에 추가",
        unselectMultiple: "묶음에서 제거",
        selectShortcutAction: "선택",
        pasteSelectedFormat: "%d개 붙여넣기",
        copySelectedFormat: "%d개 복사",
        clearSelection: "선택 해제",
        moveUp: "위로 이동",
        moveDown: "아래로 이동",
        noResults: "결과 없음",
        newestFirst: "최신순",
        active: "새 텍스트 저장 중",
        includeImagesFiles: "복사한 이미지와 파일도 저장",
        includeImagesFilesCaption: "이미지는 기록에 추가되고 파일은 위치 링크로 저장됩니다. 텍스트 항목처럼 고정하고 붙여넣을 수 있습니다.",
        imageEntryLabel: "이미지",
        fileCountFormat: "파일 %d개",
        pasteImageAsFile: "복사한 이미지를 파일로 붙여넣기",
        pasteImageAsFileCaption: "Finder가 활성화되어 있을 때 ⌘V를 누르면 복사한 이미지가 현재 폴더에 PNG로 저장됩니다.",
        previewLabel: "미리보기",
        edit: "편집",
        cancel: "취소",
        save: "저장",
        autoClearEnable: "클립보드 자동 지우기 대기 시간",
        autoClearSecondsSuffix: "초",
        autoClearOnSleep: "Mac이 잠자기에 들어갈 때 클립보드 지우기",
        autoClearOnDisplaySleep: "디스플레이가 꺼질 때 클립보드 지우기",
        autoClearOnScreenLock: "화면이 잠길 때 클립보드 지우기",
        autoClearCaption: "시스템 클립보드만 지웁니다. 이미 저장된 항목은 기록에 남습니다.",
        deleteSelectedFormat: "%d개 삭제"
    )
}

extension MonitorAlertFeatureStrings {
    static let ko = MonitorAlertFeatureStrings(
        section: "알림",
        caption: "선택한 기준에 도달하면 알림이 표시됩니다. CPU 사용량과 온도 알림은 기준을 약 12초 동안 계속 넘어야 하므로 짧은 급증은 무시됩니다. 반복 설정은 같은 알림의 반복만 제한합니다.",
        notificationsDenied: "시스템 설정에서 Vorssaint 알림이 꺼져 있어 경고를 표시할 수 없습니다.",
        cpu: "높은 CPU 사용량",
        cpuTemperature: "높은 CPU 온도",
        memory: "위험한 메모리 압력",
        disk: "부족한 디스크 공간",
        battery: "낮은 배터리",
        cpuThreshold: "CPU 사용량",
        cpuTemperatureThreshold: "온도",
        diskThreshold: "남은 공간",
        batteryThreshold: "배터리 잔량",
        cooldown: "같은 알림을 다시 보내기까지",
        cooldown2: "2분",
        cooldown5: "5분",
        cooldown15: "15분",
        cooldown30: "30분",
        cooldown60: "1시간",
        cpuTitle: "높은 CPU 사용량",
        cpuBodyFormat: "CPU 사용량이 몇 초 동안 %d%%를 넘었습니다.",
        cpuTemperatureTitle: "CPU 과열",
        cpuTemperatureBodyFormat: "CPU 온도가 %d °C에 도달했습니다.",
        memoryTitle: "위험한 메모리",
        memoryBody: "메모리 압력이 위험 수준에 도달했습니다.",
        diskTitle: "부족한 디스크 공간",
        diskBodyFormat: "%@의 여유 공간이 %d%% 미만입니다.",
        batteryTitle: "낮은 배터리",
        batteryBodyFormat: "배터리 잔량이 %d%%입니다.",
        batteryTemperature: "높은 배터리 온도",
        batteryTemperatureThreshold: "온도",
        batteryTemperatureTitle: "배터리 과열",
        batteryTemperatureBodyFormat: "배터리 온도가 %d °C에 도달했습니다."
    )
}

struct ClipboardFeatureStrings {
    let title: String
    let enable: String
    let caption: String
    let localNote: String
    let skipSensitive: String
    let skipSensitiveCaption: String
    let limit: String
    let limitUnlimited: String
    let showInPanel: String
    let shortcut: String
    let shortcutCaption: String
    let shortcutHint: String
    let clickRowShortcut: String
    let commandClickShortcut: String
    let pinned: String
    let recent: String
    let pin: String
    let unpin: String
    let clearRecent: String
    let clearAll: String
    let empty: String
    let disabled: String
    let search: String
    let copy: String
    let copied: String
    let delete: String
    let selectMultiple: String
    let unselectMultiple: String
    let selectShortcutAction: String
    let pasteSelectedFormat: String
    let copySelectedFormat: String
    let clearSelection: String
    let moveUp: String
    let moveDown: String
    let noResults: String
    let newestFirst: String
    let active: String
    let includeImagesFiles: String
    let includeImagesFilesCaption: String
    let imageEntryLabel: String
    let fileCountFormat: String
    let pasteImageAsFile: String
    let pasteImageAsFileCaption: String
    let previewLabel: String
    let edit: String
    let cancel: String
    let save: String
    let autoClearEnable: String
    let autoClearSecondsSuffix: String
    let autoClearOnSleep: String
    let autoClearOnDisplaySleep: String
    let autoClearOnScreenLock: String
    let autoClearCaption: String
    let deleteSelectedFormat: String

    static let enUS = ClipboardFeatureStrings(
        title: "Clipboard",
        enable: "Save clipboard history",
        caption: "Stores copied text so you can reuse it later. Everything stays local and can be cleared anytime.",
        localNote: "Everything stays on this Mac. Very large items are ignored.",
        skipSensitive: "Skip text that looks sensitive",
        skipSensitiveCaption: "Avoids saving short no-space strings that look like passwords, tokens or keys.",
        limit: "Limit",
        limitUnlimited: "Unlimited",
        showInPanel: "Show in panel",
        shortcut: "History shortcut",
        shortcutCaption: "Opens a quick window with search, pinned items and ⌘1 to ⌘9 shortcuts for pasting into the previous app.",
        shortcutHint: "Click a row to paste it into the previous app. ⌘-click selects several; ⌘C copies without pasting.",
        clickRowShortcut: "Click row",
        commandClickShortcut: "⌘ Click",
        pinned: "Pinned",
        recent: "Recent",
        pin: "Pin",
        unpin: "Unpin",
        clearRecent: "Clear recent",
        clearAll: "Clear unpinned",
        empty: "No saved text",
        disabled: "Enable history to start saving copied text.",
        search: "Search copied text",
        copy: "Copy",
        copied: "Copied",
        delete: "Delete item",
        selectMultiple: "Add to pile",
        unselectMultiple: "Remove from pile",
        selectShortcutAction: "Select",
        pasteSelectedFormat: "Paste %d",
        copySelectedFormat: "Copy %d",
        clearSelection: "Clear selection",
        moveUp: "Move up",
        moveDown: "Move down",
        noResults: "No results",
        newestFirst: "Newest first",
        active: "Saving new text",
        includeImagesFiles: "Also save copied images and files",
        includeImagesFilesCaption: "Images join the history and files are remembered as links to their location. Pin and paste them like any text item.",
        imageEntryLabel: "Image",
        fileCountFormat: "%d files",
        pasteImageAsFile: "Paste copied images as files",
        pasteImageAsFileCaption: "When Finder is active, ⌘V saves a copied image as a PNG in the current folder.",
        previewLabel: "Preview",
        edit: "Edit",
        cancel: "Cancel",
        save: "Save",
        autoClearEnable: "Auto clear clipboard with a delay of",
        autoClearSecondsSuffix: "seconds",
        autoClearOnSleep: "Clear clipboard on computer sleep",
        autoClearOnDisplaySleep: "Clear clipboard on display sleep",
        autoClearOnScreenLock: "Clear clipboard on screen lock",
        autoClearCaption: "Clears the system clipboard only. Items already saved stay in the history.",
        deleteSelectedFormat: "Delete %d"
    )

    static let ptBR = ClipboardFeatureStrings(
        title: "Clipboard",
        enable: "Guardar histórico de clipboard",
        caption: "Guarda textos copiados para reutilizar depois. Tudo fica local e pode ser apagado a qualquer momento.",
        localNote: "Tudo fica neste Mac. Itens muito grandes são ignorados.",
        skipSensitive: "Ignorar textos com aparência sensível",
        skipSensitiveCaption: "Evita salvar textos curtos sem espaços que parecem senha, token ou chave.",
        limit: "Limite",
        limitUnlimited: "Ilimitado",
        showInPanel: "Mostrar no painel",
        shortcut: "Atalho do histórico",
        shortcutCaption: "Abre uma janela rápida com busca, favoritos e atalhos ⌘1 a ⌘9 para colar no app anterior.",
        shortcutHint: "Clique numa linha para colar no app anterior. ⌘+clique seleciona várias; ⌘C copia sem colar.",
        clickRowShortcut: "Clique na linha",
        commandClickShortcut: "⌘ Clique",
        pinned: "Fixados",
        recent: "Recentes",
        pin: "Fixar",
        unpin: "Desfixar",
        clearRecent: "Limpar recentes",
        clearAll: "Limpar não fixados",
        empty: "Nenhum texto salvo",
        disabled: "Ative o histórico para começar a guardar textos copiados.",
        search: "Buscar textos copiados",
        copy: "Copiar",
        copied: "Copiado",
        delete: "Apagar item",
        selectMultiple: "Marcar para pilha",
        unselectMultiple: "Remover da pilha",
        selectShortcutAction: "Selecionar",
        pasteSelectedFormat: "Colar %d",
        copySelectedFormat: "Copiar %d",
        clearSelection: "Limpar seleção",
        moveUp: "Mover para cima",
        moveDown: "Mover para baixo",
        noResults: "Nenhum resultado",
        newestFirst: "Mais recentes primeiro",
        active: "Guardando novos textos",
        includeImagesFiles: "Guardar também imagens e arquivos copiados",
        includeImagesFilesCaption: "Imagens entram no histórico e arquivos são lembrados como links para o local deles. Fixe e cole como qualquer texto.",
        imageEntryLabel: "Imagem",
        fileCountFormat: "%d arquivos",
        pasteImageAsFile: "Colar imagens copiadas como arquivos",
        pasteImageAsFileCaption: "Com o Finder ativo, ⌘V salva uma imagem copiada como PNG na pasta atual.",
        previewLabel: "Prévia",
        edit: "Editar",
        cancel: "Cancelar",
        save: "Salvar",
        autoClearEnable: "Limpar o clipboard automaticamente após",
        autoClearSecondsSuffix: "segundos",
        autoClearOnSleep: "Limpar o clipboard quando o Mac dormir",
        autoClearOnDisplaySleep: "Limpar o clipboard quando a tela apagar",
        autoClearOnScreenLock: "Limpar o clipboard ao bloquear a tela",
        autoClearCaption: "Limpa apenas o clipboard do sistema. Os itens já guardados continuam no histórico.",
        deleteSelectedFormat: "Apagar %d"
    )

    static let tr = ClipboardFeatureStrings(
        title: "Pano",
        enable: "Pano geçmişini kaydet",
        caption: "Kopyalanan metinleri daha sonra yeniden kullanabilmen için saklar. Her şey yerel kalır ve istediğin zaman temizlenebilir.",
        localNote: "Her şey bu Mac’te kalır. Çok büyük öğeler yok sayılır.",
        skipSensitive: "Hassas görünen metinleri atla",
        skipSensitiveCaption: "Parola, token veya anahtar gibi görünen kısa ve boşluksuz dizeleri kaydetmekten kaçınır.",
        limit: "Sınır",
        limitUnlimited: "Sınırsız",
        showInPanel: "Panelde göster",
        shortcut: "Geçmiş kısayolu",
        shortcutCaption: "Arama, sabitlenmiş öğeler ve önceki uygulamaya yapıştırmak için ⌘1 - ⌘9 kısayolları olan hızlı bir pencere açar.",
        shortcutHint: "Bir satıra tıklayarak önceki uygulamaya yapıştırın. ⌘-tıklama birden çok öğe seçer; ⌘C yapıştırmadan kopyalar.",
        clickRowShortcut: "Satıra tıkla",
        commandClickShortcut: "⌘ Tıkla",
        pinned: "Sabitlenenler",
        recent: "Son",
        pin: "Sabitle",
        unpin: "Sabitlemeyi kaldır",
        clearRecent: "Sonları temizle",
        clearAll: "Sabitlenmeyenleri temizle",
        empty: "Kayıtlı metin yok",
        disabled: "Kopyalanan metinleri kaydetmeye başlamak için geçmişi etkinleştir.",
        search: "Kopyalanan metinlerde ara",
        copy: "Kopyala",
        copied: "Kopyalandı",
        delete: "Öğeyi sil",
        selectMultiple: "Yığına ekle",
        unselectMultiple: "Yığından çıkar",
        selectShortcutAction: "Seç",
        pasteSelectedFormat: "%d öğeyi yapıştır",
        copySelectedFormat: "%d öğeyi kopyala",
        clearSelection: "Seçimi temizle",
        moveUp: "Yukarı taşı",
        moveDown: "Aşağı taşı",
        noResults: "Sonuç yok",
        newestFirst: "En yeniler önce",
        active: "Yeni metinler kaydediliyor",
        includeImagesFiles: "Kopyalanan görselleri ve dosyaları da kaydet",
        includeImagesFilesCaption: "Görseller geçmişe eklenir, dosyalar konumlarına bağlantı olarak hatırlanır. Metin gibi sabitle ve yapıştır.",
        imageEntryLabel: "Görsel",
        fileCountFormat: "%d dosya",
        pasteImageAsFile: "Kopyalanan görselleri dosya olarak yapıştır",
        pasteImageAsFileCaption: "Finder etkinken ⌘V, kopyalanan görseli geçerli klasöre PNG olarak kaydeder.",
        previewLabel: "Önizleme",
        edit: "Düzenle",
        cancel: "İptal",
        save: "Kaydet",
        autoClearEnable: "Panoyu otomatik temizle, gecikme",
        autoClearSecondsSuffix: "saniye",
        autoClearOnSleep: "Mac uykuya geçince panoyu temizle",
        autoClearOnDisplaySleep: "Ekran uykuya geçince panoyu temizle",
        autoClearOnScreenLock: "Ekran kilitlenince panoyu temizle",
        autoClearCaption: "Yalnızca sistem panosunu temizler. Kaydedilmiş ögeler geçmişte kalır.",
        deleteSelectedFormat: "%d öğeyi sil"
    )

    static let ru = ClipboardFeatureStrings(
        title: "Буфер обмена",
        enable: "Сохранять историю буфера обмена",
        caption: "Сохраняет скопированный текст, чтобы вы могли использовать его позже. Всё остаётся локально и может быть очищено в любой момент.",
        localNote: "Всё остаётся на этом Mac. Слишком большие элементы игнорируются.",
        skipSensitive: "Пропускать текст, похожий на конфиденциальный",
        skipSensitiveCaption: "Не сохраняет короткие строки без пробелов, похожие на пароли, токены или ключи.",
        limit: "Лимит",
        limitUnlimited: "Без ограничений",
        showInPanel: "Показывать в панели",
        shortcut: "Горячая клавиша истории",
        shortcutCaption: "Открывает быстрое окно с поиском, закреплёнными элементами и сочетаниями ⌘1–⌘9 для вставки в предыдущее приложение.",
        shortcutHint: "Щёлкните по строке, чтобы вставить её в предыдущее приложение. ⌘-клик выбирает несколько; ⌘C копирует без вставки.",
        clickRowShortcut: "Щелчок по строке",
        commandClickShortcut: "⌘ Клик",
        pinned: "Закреплённые",
        recent: "Недавние",
        pin: "Закрепить",
        unpin: "Открепить",
        clearRecent: "Очистить недавнее",
        clearAll: "Очистить незакреплённые",
        empty: "Нет сохранённого текста",
        disabled: "Включите историю, чтобы начать сохранять скопированный текст.",
        search: "Поиск по скопированному тексту",
        copy: "Скопировать",
        copied: "Скопировано",
        delete: "Удалить элемент",
        selectMultiple: "Добавить в стопку",
        unselectMultiple: "Убрать из стопки",
        selectShortcutAction: "Выбрать",
        pasteSelectedFormat: "Вставить: %d",
        copySelectedFormat: "Копировать: %d",
        clearSelection: "Снять выделение",
        moveUp: "Вверх",
        moveDown: "Вниз",
        noResults: "Ничего не найдено",
        newestFirst: "Сначала новые",
        active: "Сохраняет новые элементы",
        includeImagesFiles: "Сохранять также изображения и файлы",
        includeImagesFilesCaption: "Изображения попадают в историю, а файлы запоминаются как ссылки на их расположение. Закрепляйте и вставляйте их как текст.",
        imageEntryLabel: "Изображение",
        fileCountFormat: "Файлов: %d",
        pasteImageAsFile: "Вставлять скопированные изображения как файлы",
        pasteImageAsFileCaption: "Когда Finder активен, ⌘V сохраняет скопированное изображение как PNG в текущей папке.",
        previewLabel: "Просмотр",
        edit: "Редактировать",
        cancel: "Отмена",
        save: "Сохранить",
        autoClearEnable: "Очищать буфер обмена через",
        autoClearSecondsSuffix: "секунд",
        autoClearOnSleep: "Очищать буфер обмена при переходе в режим сна",
        autoClearOnDisplaySleep: "Очищать буфер обмена при выключении экрана",
        autoClearOnScreenLock: "Очищать буфер обмена при блокировке экрана",
        autoClearCaption: "Очищается только системный буфер обмена. Сохранённые элементы остаются в истории.",
        deleteSelectedFormat: "Удалить: %d"
    )

    static let es = ClipboardFeatureStrings(
        title: "Portapapeles",
        enable: "Guardar historial del portapapeles",
        caption: "Guarda el texto copiado para reutilizarlo después. Todo queda local y se puede borrar cuando quieras.",
        localNote: "Todo se queda en este Mac. Los elementos muy grandes se ignoran.",
        skipSensitive: "Omitir texto que parezca sensible",
        skipSensitiveCaption: "Evita guardar cadenas cortas sin espacios que parezcan contraseñas, tokens o claves.",
        limit: "Límite",
        limitUnlimited: "Ilimitado",
        showInPanel: "Mostrar en el panel",
        shortcut: "Atajo del historial",
        shortcutCaption: "Abre una ventana rápida con búsqueda, elementos fijados y atajos ⌘1 a ⌘9 para pegar en la app anterior.",
        shortcutHint: "Haz clic en una fila para pegarla en la app anterior. ⌘+clic selecciona varias; ⌘C copia sin pegar.",
        clickRowShortcut: "Clic en fila",
        commandClickShortcut: "⌘ Clic",
        pinned: "Fijados",
        recent: "Recientes",
        pin: "Fijar",
        unpin: "Desfijar",
        clearRecent: "Limpiar recientes",
        clearAll: "Limpiar no fijados",
        empty: "No hay texto guardado",
        disabled: "Activa el historial para empezar a guardar texto copiado.",
        search: "Buscar texto copiado",
        copy: "Copiar",
        copied: "Copiado",
        delete: "Eliminar elemento",
        selectMultiple: "Añadir a la pila",
        unselectMultiple: "Quitar de la pila",
        selectShortcutAction: "Seleccionar",
        pasteSelectedFormat: "Pegar %d",
        copySelectedFormat: "Copiar %d",
        clearSelection: "Limpiar selección",
        moveUp: "Subir",
        moveDown: "Bajar",
        noResults: "Sin resultados",
        newestFirst: "Más recientes primero",
        active: "Guardando nuevo texto",
        includeImagesFiles: "Guardar también imágenes y archivos copiados",
        includeImagesFilesCaption: "Las imágenes entran en el historial y los archivos se recuerdan como enlaces a su ubicación. Fíjalos y pégalos como cualquier texto.",
        imageEntryLabel: "Imagen",
        fileCountFormat: "%d archivos",
        pasteImageAsFile: "Pegar imágenes copiadas como archivos",
        pasteImageAsFileCaption: "Con Finder activo, ⌘V guarda una imagen copiada como PNG en la carpeta actual.",
        previewLabel: "Vista previa",
        edit: "Editar",
        cancel: "Cancelar",
        save: "Guardar",
        autoClearEnable: "Vaciar el portapapeles automáticamente tras",
        autoClearSecondsSuffix: "segundos",
        autoClearOnSleep: "Vaciar el portapapeles al suspender el Mac",
        autoClearOnDisplaySleep: "Vaciar el portapapeles al apagarse la pantalla",
        autoClearOnScreenLock: "Vaciar el portapapeles al bloquear la pantalla",
        autoClearCaption: "Solo se vacía el portapapeles del sistema. Los elementos guardados siguen en el historial.",
        deleteSelectedFormat: "Eliminar %d"
    )

    static let de = ClipboardFeatureStrings(
        title: "Zwischenablage",
        enable: "Zwischenablageverlauf speichern",
        caption: "Speichert kopierten Text, damit du ihn später wiederverwenden kannst. Alles bleibt lokal und kann jederzeit gelöscht werden.",
        localNote: "Alles bleibt auf diesem Mac. Sehr große Inhalte werden ignoriert.",
        skipSensitive: "Text überspringen, der sensibel wirkt",
        skipSensitiveCaption: "Speichert keine kurzen Zeichenfolgen ohne Leerzeichen, die wie Passwörter, Token oder Schlüssel wirken.",
        limit: "Limit",
        limitUnlimited: "Unbegrenzt",
        showInPanel: "Im Panel anzeigen",
        shortcut: "Verlaufskürzel",
        shortcutCaption: "Öffnet ein Schnellfenster mit Suche, angehefteten Einträgen und ⌘1 bis ⌘9 zum Einfügen in die vorherige App.",
        shortcutHint: "Klicke auf eine Zeile, um sie in die vorherige App einzufügen. ⌘-Klick wählt mehrere aus; ⌘C kopiert ohne Einfügen.",
        clickRowShortcut: "Zeile klicken",
        commandClickShortcut: "⌘ Klick",
        pinned: "Angeheftet",
        recent: "Zuletzt",
        pin: "Anheften",
        unpin: "Lösen",
        clearRecent: "Zuletzt löschen",
        clearAll: "Nicht angeheftete löschen",
        empty: "Kein gespeicherter Text",
        disabled: "Aktiviere den Verlauf, um kopierten Text zu speichern.",
        search: "Kopierten Text suchen",
        copy: "Kopieren",
        copied: "Kopiert",
        delete: "Eintrag löschen",
        selectMultiple: "Zum Stapel hinzufügen",
        unselectMultiple: "Aus dem Stapel entfernen",
        selectShortcutAction: "Auswählen",
        pasteSelectedFormat: "%d einfügen",
        copySelectedFormat: "%d kopieren",
        clearSelection: "Auswahl löschen",
        moveUp: "Nach oben",
        moveDown: "Nach unten",
        noResults: "Keine Ergebnisse",
        newestFirst: "Neueste zuerst",
        active: "Speichert neuen Text",
        includeImagesFiles: "Auch kopierte Bilder und Dateien speichern",
        includeImagesFilesCaption: "Bilder wandern in den Verlauf, Dateien werden als Verweise auf ihren Ort gemerkt. Anheften und Einsetzen wie bei Text.",
        imageEntryLabel: "Bild",
        fileCountFormat: "%d Dateien",
        pasteImageAsFile: "Kopierte Bilder als Dateien einsetzen",
        pasteImageAsFileCaption: "Wenn Finder aktiv ist, speichert ⌘V ein kopiertes Bild als PNG im aktuellen Ordner.",
        previewLabel: "Vorschau",
        edit: "Bearbeiten",
        cancel: "Abbrechen",
        save: "Sichern",
        autoClearEnable: "Zwischenablage automatisch leeren nach",
        autoClearSecondsSuffix: "Sekunden",
        autoClearOnSleep: "Zwischenablage beim Ruhezustand leeren",
        autoClearOnDisplaySleep: "Zwischenablage beim Ausschalten des Bildschirms leeren",
        autoClearOnScreenLock: "Zwischenablage beim Sperren des Bildschirms leeren",
        autoClearCaption: "Leert nur die Zwischenablage des Systems. Bereits gesicherte Einträge bleiben im Verlauf.",
        deleteSelectedFormat: "%d löschen"
    )

    static let fr = ClipboardFeatureStrings(
        title: "Presse-papiers",
        enable: "Enregistrer l’historique du presse-papiers",
        caption: "Enregistre le texte copié pour le réutiliser plus tard. Tout reste local et peut être effacé à tout moment.",
        localNote: "Tout reste sur ce Mac. Les éléments très volumineux sont ignorés.",
        skipSensitive: "Ignorer le texte qui semble sensible",
        skipSensitiveCaption: "Évite d’enregistrer les courtes chaînes sans espaces qui ressemblent à des mots de passe, jetons ou clés.",
        limit: "Limite",
        limitUnlimited: "Illimité",
        showInPanel: "Afficher dans le panneau",
        shortcut: "Raccourci de l’historique",
        shortcutCaption: "Ouvre une fenêtre rapide avec recherche, éléments épinglés et raccourcis ⌘1 à ⌘9 pour coller dans l’app précédente.",
        shortcutHint: "Cliquez sur une ligne pour la coller dans l’app précédente. ⌘+clic en sélectionne plusieurs\u{00A0}; ⌘C copie sans coller.",
        clickRowShortcut: "Cliquer la ligne",
        commandClickShortcut: "⌘ Clic",
        pinned: "Épinglés",
        recent: "Récents",
        pin: "Épingler",
        unpin: "Désépingler",
        clearRecent: "Effacer les récents",
        clearAll: "Effacer non épinglés",
        empty: "Aucun texte enregistré",
        disabled: "Activez l’historique pour commencer à enregistrer le texte copié.",
        search: "Rechercher le texte copié",
        copy: "Copier",
        copied: "Copié",
        delete: "Supprimer l’élément",
        selectMultiple: "Ajouter à la pile",
        unselectMultiple: "Retirer de la pile",
        selectShortcutAction: "Sélectionner",
        pasteSelectedFormat: "Coller %d",
        copySelectedFormat: "Copier %d",
        clearSelection: "Effacer la sélection",
        moveUp: "Monter",
        moveDown: "Descendre",
        noResults: "Aucun résultat",
        newestFirst: "Plus récents d’abord",
        active: "Enregistre le nouveau texte",
        includeImagesFiles: "Enregistrer aussi les images et fichiers copiés",
        includeImagesFilesCaption: "Les images rejoignent l’historique et les fichiers sont mémorisés comme des liens vers leur emplacement. Épinglez-les et collez-les comme du texte.",
        imageEntryLabel: "Image",
        fileCountFormat: "%d fichiers",
        pasteImageAsFile: "Coller les images copiées comme fichiers",
        pasteImageAsFileCaption: "Lorsque Finder est actif, ⌘V enregistre l’image copiée au format PNG dans le dossier actuel.",
        previewLabel: "Aperçu",
        edit: "Modifier",
        cancel: "Annuler",
        save: "Enregistrer",
        autoClearEnable: "Vider le presse-papiers automatiquement après",
        autoClearSecondsSuffix: "secondes",
        autoClearOnSleep: "Vider le presse-papiers à la mise en veille du Mac",
        autoClearOnDisplaySleep: "Vider le presse-papiers à l’extinction de l’écran",
        autoClearOnScreenLock: "Vider le presse-papiers au verrouillage de l’écran",
        autoClearCaption: "Seul le presse-papiers du système est vidé. Les éléments enregistrés restent dans l’historique.",
        deleteSelectedFormat: "Supprimer %d"
    )

    static let it = ClipboardFeatureStrings(
        title: "Appunti",
        enable: "Salva cronologia degli appunti",
        caption: "Salva il testo copiato per riutilizzarlo in seguito. Tutto resta locale e può essere cancellato in qualsiasi momento.",
        localNote: "Tutto resta su questo Mac. Gli elementi molto grandi vengono ignorati.",
        skipSensitive: "Ignora testo che sembra sensibile",
        skipSensitiveCaption: "Evita di salvare stringhe brevi senza spazi che sembrano password, token o chiavi.",
        limit: "Limite",
        limitUnlimited: "Illimitato",
        showInPanel: "Mostra nel pannello",
        shortcut: "Scorciatoia cronologia",
        shortcutCaption: "Apre una finestra rapida con ricerca, elementi fissati e scorciatoie ⌘1 a ⌘9 per incollare nell’app precedente.",
        shortcutHint: "Fai clic su una riga per incollarla nell’app precedente. ⌘+clic ne seleziona diverse; ⌘C copia senza incollare.",
        clickRowShortcut: "Clic sulla riga",
        commandClickShortcut: "⌘ Clic",
        pinned: "Fissati",
        recent: "Recenti",
        pin: "Fissa",
        unpin: "Sblocca",
        clearRecent: "Cancella recenti",
        clearAll: "Cancella non fissati",
        empty: "Nessun testo salvato",
        disabled: "Attiva la cronologia per iniziare a salvare il testo copiato.",
        search: "Cerca testo copiato",
        copy: "Copia",
        copied: "Copiato",
        delete: "Elimina elemento",
        selectMultiple: "Aggiungi alla pila",
        unselectMultiple: "Rimuovi dalla pila",
        selectShortcutAction: "Seleziona",
        pasteSelectedFormat: "Incolla %d",
        copySelectedFormat: "Copia %d",
        clearSelection: "Cancella selezione",
        moveUp: "Sposta su",
        moveDown: "Sposta giù",
        noResults: "Nessun risultato",
        newestFirst: "Più recenti prima",
        active: "Salvataggio nuovo testo",
        includeImagesFiles: "Salva anche immagini e file copiati",
        includeImagesFilesCaption: "Le immagini entrano nella cronologia e i file vengono ricordati come collegamenti alla loro posizione. Fissali e incollali come qualsiasi testo.",
        imageEntryLabel: "Immagine",
        fileCountFormat: "%d file",
        pasteImageAsFile: "Incolla le immagini copiate come file",
        pasteImageAsFileCaption: "Quando Finder è attivo, ⌘V salva un’immagine copiata come PNG nella cartella attuale.",
        previewLabel: "Anteprima",
        edit: "Modifica",
        cancel: "Annulla",
        save: "Salva",
        autoClearEnable: "Svuota gli appunti automaticamente dopo",
        autoClearSecondsSuffix: "secondi",
        autoClearOnSleep: "Svuota gli appunti quando il Mac va in stop",
        autoClearOnDisplaySleep: "Svuota gli appunti quando lo schermo si spegne",
        autoClearOnScreenLock: "Svuota gli appunti al blocco dello schermo",
        autoClearCaption: "Svuota solo gli appunti di sistema. Gli elementi salvati restano nella cronologia.",
        deleteSelectedFormat: "Elimina %d"
    )

    static let ja = ClipboardFeatureStrings(
        title: "クリップボード",
        enable: "クリップボード履歴を保存",
        caption: "コピーしたテキストを保存して、あとで再利用できます。すべてローカルに保存され、いつでも削除できます。",
        localNote: "すべてこのMacに残ります。大きすぎる項目は無視されます。",
        skipSensitive: "機密らしいテキストを無視",
        skipSensitiveCaption: "パスワード、トークン、キーに見える短い空白なしの文字列を保存しません。",
        limit: "上限",
        limitUnlimited: "無制限",
        showInPanel: "パネルに表示",
        shortcut: "履歴ショートカット",
        shortcutCaption: "検索、固定項目、前のアプリへ貼り付ける ⌘1 から ⌘9 のショートカットを備えたクイックウインドウを開きます。",
        shortcutHint: "行をクリックすると前のアプリに貼り付けます。⌘クリックで複数選択、⌘C は貼り付けずにコピーします。",
        clickRowShortcut: "行をクリック",
        commandClickShortcut: "⌘ クリック",
        pinned: "固定済み",
        recent: "最近",
        pin: "固定",
        unpin: "固定解除",
        clearRecent: "最近を消去",
        clearAll: "未固定を消去",
        empty: "保存済みテキストなし",
        disabled: "履歴を有効にすると、コピーしたテキストを保存できます。",
        search: "コピーしたテキストを検索",
        copy: "コピー",
        copied: "コピー済み",
        delete: "項目を削除",
        selectMultiple: "束に追加",
        unselectMultiple: "束から削除",
        selectShortcutAction: "選択",
        pasteSelectedFormat: "%d件を貼り付け",
        copySelectedFormat: "%d件をコピー",
        clearSelection: "選択を解除",
        moveUp: "上へ移動",
        moveDown: "下へ移動",
        noResults: "結果なし",
        newestFirst: "新しい順",
        active: "新しいテキストを保存中",
        includeImagesFiles: "コピーした画像やファイルも保存",
        includeImagesFilesCaption: "画像は履歴に入り、ファイルは場所へのリンクとして記憶されます。テキストと同じようにピン留めやペーストができます。",
        imageEntryLabel: "画像",
        fileCountFormat: "%d個のファイル",
        pasteImageAsFile: "コピーした画像をファイルとしてペースト",
        pasteImageAsFileCaption: "Finder がアクティブなとき、⌘V でコピーした画像を現在のフォルダに PNG として保存します。",
        previewLabel: "プレビュー",
        edit: "編集",
        cancel: "キャンセル",
        save: "保存",
        autoClearEnable: "クリップボードを自動消去するまでの時間",
        autoClearSecondsSuffix: "秒",
        autoClearOnSleep: "システムスリープ時にクリップボードを消去",
        autoClearOnDisplaySleep: "ディスプレイスリープ時にクリップボードを消去",
        autoClearOnScreenLock: "画面ロック時にクリップボードを消去",
        autoClearCaption: "システムのクリップボードのみを消去します。保存済みの項目は履歴に残ります。",
        deleteSelectedFormat: "%d件を削除"
    )

    static let zhHans = ClipboardFeatureStrings(
        title: "剪贴板",
        enable: "保存剪贴板历史",
        caption: "保存拷贝过的文本，方便之后再次使用。所有内容都保存在本机，可随时清除。",
        localNote: "一切都保留在这台 Mac 上。特别大的内容会被忽略。",
        skipSensitive: "跳过疑似敏感文本",
        skipSensitiveCaption: "避免保存像密码、令牌或密钥的短文本。",
        limit: "数量上限",
        limitUnlimited: "无限制",
        showInPanel: "在面板中显示",
        shortcut: "历史快捷键",
        shortcutCaption: "打开快速窗口，支持搜索、固定项目，以及用 ⌘1 到 ⌘9 粘贴到上一个 App。",
        shortcutHint: "点击整行即可粘贴到上一个 App。⌘+点击可选择多项；⌘C 仅拷贝不粘贴。",
        clickRowShortcut: "点击整行",
        commandClickShortcut: "⌘ 点击",
        pinned: "已固定",
        recent: "最近",
        pin: "固定",
        unpin: "取消固定",
        clearRecent: "清除最近项目",
        clearAll: "清除未固定项目",
        empty: "没有保存的文本",
        disabled: "启用历史记录后即可开始保存拷贝的文本。",
        search: "搜索拷贝的文本",
        copy: "拷贝",
        copied: "已拷贝",
        delete: "删除项目",
        selectMultiple: "加入堆叠",
        unselectMultiple: "从堆叠移除",
        selectShortcutAction: "选择",
        pasteSelectedFormat: "粘贴 %d 项",
        copySelectedFormat: "拷贝 %d 项",
        clearSelection: "清除选择",
        moveUp: "上移",
        moveDown: "下移",
        noResults: "没有结果",
        newestFirst: "最新优先",
        active: "正在保存新文本",
        includeImagesFiles: "同时保存拷贝的图片和文件",
        includeImagesFilesCaption: "图片会进入历史记录，文件会以其位置链接的形式被记住。可以像文本一样固定和粘贴。",
        imageEntryLabel: "图片",
        fileCountFormat: "%d 个文件",
        pasteImageAsFile: "将拷贝的图片粘贴为文件",
        pasteImageAsFileCaption: "Finder 处于活动状态时，按 ⌘V 会将拷贝的图片以 PNG 格式存储到当前文件夹。",
        previewLabel: "预览",
        edit: "编辑",
        cancel: "取消",
        save: "保存",
        autoClearEnable: "自动清空剪贴板，延迟",
        autoClearSecondsSuffix: "秒",
        autoClearOnSleep: "睡眠时清空剪贴板",
        autoClearOnDisplaySleep: "显示器睡眠时清空剪贴板",
        autoClearOnScreenLock: "锁定屏幕时清空剪贴板",
        autoClearCaption: "仅清空系统剪贴板，已保存的条目仍保留在历史记录中。",
        deleteSelectedFormat: "删除 %d 项"
    )

    static let zhTW = ClipboardFeatureStrings(
        title: "剪貼簿",
        enable: "儲存剪貼簿紀錄",
        caption: "儲存複製過的文字，方便之後再次使用。所有內容都會儲存在這台裝置上，並可隨時清除。",
        localNote: "一切都保留在這台 Mac 上。過大的內容會被略過。",
        skipSensitive: "略過可能含有敏感資料的文字",
        skipSensitiveCaption: "避免儲存像是密碼、權杖或金鑰這類較短的文字。",
        limit: "數量上限",
        limitUnlimited: "無限制",
        showInPanel: "在面板中顯示",
        shortcut: "剪貼簿紀錄快速鍵",
        shortcutCaption: "開啟快速視窗，可搜尋、釘選項目，並使用 ⌘1 到 ⌘9 貼到上一個 App。",
        shortcutHint: "點選整列即可貼到上一個 App。⌘+點選可選取多個項目；⌘C 只複製不貼上。",
        clickRowShortcut: "點選整列",
        commandClickShortcut: "⌘ 點選",
        pinned: "已釘選",
        recent: "最近",
        pin: "釘選",
        unpin: "取消釘選",
        clearRecent: "清除最近項目",
        clearAll: "清除未釘選項目",
        empty: "沒有儲存的文字",
        disabled: "開啟紀錄後，即可開始儲存複製的文字。",
        search: "搜尋複製的文字",
        copy: "複製",
        copied: "已複製",
        delete: "刪除項目",
        selectMultiple: "加入堆疊",
        unselectMultiple: "從堆疊移除",
        selectShortcutAction: "選取",
        pasteSelectedFormat: "貼上 %d 個",
        copySelectedFormat: "拷貝 %d 個",
        clearSelection: "清除選取項目",
        moveUp: "上移",
        moveDown: "下移",
        noResults: "沒有結果",
        newestFirst: "最新優先",
        active: "正在儲存新文字",
        includeImagesFiles: "同時保存拷貝的圖片和檔案",
        includeImagesFilesCaption: "圖片會進入歷史記錄，檔案會以其位置連結的形式被記住。可以像文字一樣固定和貼上。",
        imageEntryLabel: "圖片",
        fileCountFormat: "%d 個檔案",
        pasteImageAsFile: "將複製的圖片貼上為檔案",
        pasteImageAsFileCaption: "Finder 啟用時，按下 ⌘V 會將複製的圖片以 PNG 格式儲存到目前的資料夾。",
        previewLabel: "預覽",
        edit: "編輯",
        cancel: "取消",
        save: "儲存",
        autoClearEnable: "自動清除剪貼簿，延遲",
        autoClearSecondsSuffix: "秒",
        autoClearOnSleep: "睡眠時清除剪貼簿",
        autoClearOnDisplaySleep: "顯示器睡眠時清除剪貼簿",
        autoClearOnScreenLock: "鎖定螢幕時清除剪貼簿",
        autoClearCaption: "僅清除系統剪貼簿，已儲存的項目仍保留在記錄中。",
        deleteSelectedFormat: "刪除 %d 個"
    )

    static let zhHK = ClipboardFeatureStrings(
        title: "剪貼簿",
        enable: "儲存剪貼簿記錄",
        caption: "儲存複製過的文字，方便之後再次使用。所有內容都會儲存在此裝置上，並可隨時清除。",
        localNote: "一切都保留在這部 Mac 上。過大的內容會被略過。",
        skipSensitive: "略過可能含有敏感資料的文字",
        skipSensitiveCaption: "避免儲存密碼、權杖或密鑰等較短文字。",
        limit: "數量上限",
        limitUnlimited: "無限制",
        showInPanel: "在面板中顯示",
        shortcut: "剪貼簿記錄快捷鍵",
        shortcutCaption: "開啟快速視窗，可搜尋、釘選項目，並使用 ⌘1 至 ⌘9 貼到上一個 App。",
        shortcutHint: "按一下整列即可貼到上一個 App。⌘+按一下可選取多個項目；⌘C 只複製不貼上。",
        clickRowShortcut: "按一下整列",
        commandClickShortcut: "⌘ 按一下",
        pinned: "已釘選",
        recent: "最近",
        pin: "釘選",
        unpin: "取消釘選",
        clearRecent: "清除最近項目",
        clearAll: "清除未釘選項目",
        empty: "沒有已儲存的文字",
        disabled: "開啟記錄後，即可開始儲存複製的文字。",
        search: "搜尋複製的文字",
        copy: "複製",
        copied: "已複製",
        delete: "刪除項目",
        selectMultiple: "加入堆疊",
        unselectMultiple: "從堆疊移除",
        selectShortcutAction: "選取",
        pasteSelectedFormat: "貼上 %d 個",
        copySelectedFormat: "複製 %d 個",
        clearSelection: "清除所選項目",
        moveUp: "上移",
        moveDown: "下移",
        noResults: "沒有結果",
        newestFirst: "最新優先",
        active: "正在儲存新文字",
        includeImagesFiles: "同時儲存拷貝的圖片和檔案",
        includeImagesFilesCaption: "圖片會加入歷史記錄，檔案會以其位置連結的形式被記住。可以像文字一樣固定和貼上。",
        imageEntryLabel: "圖片",
        fileCountFormat: "%d 個檔案",
        pasteImageAsFile: "將複製的圖片貼上為檔案",
        pasteImageAsFileCaption: "Finder 啟用時，按下 ⌘V 會將複製的圖片以 PNG 格式儲存到目前的資料夾。",
        previewLabel: "預覽",
        edit: "編輯",
        cancel: "取消",
        save: "儲存",
        autoClearEnable: "自動清除剪貼簿，延遲",
        autoClearSecondsSuffix: "秒",
        autoClearOnSleep: "睡眠時清除剪貼簿",
        autoClearOnDisplaySleep: "顯示器睡眠時清除剪貼簿",
        autoClearOnScreenLock: "鎖定螢幕時清除剪貼簿",
        autoClearCaption: "只會清除系統剪貼簿，已儲存的項目仍會保留在記錄中。",
        deleteSelectedFormat: "刪除 %d 個"
    )
}

struct MonitorAlertFeatureStrings {
    let section: String
    let caption: String
    let notificationsDenied: String
    let cpu: String
    let cpuTemperature: String
    let memory: String
    let disk: String
    let battery: String
    let cpuThreshold: String
    let cpuTemperatureThreshold: String
    let diskThreshold: String
    let batteryThreshold: String
    let cooldown: String
    let cooldown2: String
    let cooldown5: String
    let cooldown15: String
    let cooldown30: String
    let cooldown60: String
    let cpuTitle: String
    let cpuBodyFormat: String
    let cpuTemperatureTitle: String
    let cpuTemperatureBodyFormat: String
    let memoryTitle: String
    let memoryBody: String
    let diskTitle: String
    let diskBodyFormat: String
    let batteryTitle: String
    let batteryBodyFormat: String
    let batteryTemperature: String
    let batteryTemperatureThreshold: String
    let batteryTemperatureTitle: String
    let batteryTemperatureBodyFormat: String

    static let enUS = MonitorAlertFeatureStrings(
        section: "Alerts",
        caption: "Alerts fire when their selected limits are reached. CPU use and temperature alerts ignore spikes shorter than about 12 seconds. The repeat setting only limits repeats of the same alert.",
        notificationsDenied: "Notifications for Vorssaint are off in System Settings, so alerts cannot appear.",
        cpu: "High CPU",
        cpuTemperature: "High CPU temperature",
        memory: "Critical memory pressure",
        disk: "Low disk space",
        battery: "Low battery",
        cpuThreshold: "CPU above",
        cpuTemperatureThreshold: "Temperature above",
        diskThreshold: "Free space below",
        batteryThreshold: "Battery below",
        cooldown: "Repeat the same alert after",
        cooldown2: "2 minutes",
        cooldown5: "5 minutes",
        cooldown15: "15 minutes",
        cooldown30: "30 minutes",
        cooldown60: "1 hour",
        cpuTitle: "High CPU",
        cpuBodyFormat: "CPU stayed above %d%% for a few seconds.",
        cpuTemperatureTitle: "Hot CPU",
        cpuTemperatureBodyFormat: "CPU reached %d °C.",
        memoryTitle: "Critical memory",
        memoryBody: "Memory pressure reached the critical level.",
        diskTitle: "Low disk space",
        diskBodyFormat: "%@ has less than %d%% free.",
        batteryTitle: "Low battery",
        batteryBodyFormat: "Battery is at %d%%.",
        batteryTemperature: "High battery temperature",
        batteryTemperatureThreshold: "Temperature above",
        batteryTemperatureTitle: "Hot battery",
        batteryTemperatureBodyFormat: "Battery reached %d °C."
    )

    static let ptBR = MonitorAlertFeatureStrings(
        section: "Alertas",
        caption: "Os alertas disparam quando os limites escolhidos são atingidos. O uso da CPU e os alertas de temperatura ignoram picos com menos de 12 segundos. A opção de repetição só limita o mesmo alerta.",
        notificationsDenied: "As notificações do Vorssaint estão desativadas nos Ajustes do Sistema, então os alertas não aparecem.",
        cpu: "CPU alta",
        cpuTemperature: "Temperatura alta da CPU",
        memory: "Pressão de memória crítica",
        disk: "Pouco espaço em disco",
        battery: "Bateria baixa",
        cpuThreshold: "CPU acima de",
        cpuTemperatureThreshold: "Temperatura acima de",
        diskThreshold: "Espaço livre abaixo de",
        batteryThreshold: "Bateria abaixo de",
        cooldown: "Repetir o mesmo alerta depois de",
        cooldown2: "2 minutos",
        cooldown5: "5 minutos",
        cooldown15: "15 minutos",
        cooldown30: "30 minutos",
        cooldown60: "1 hora",
        cpuTitle: "CPU alta",
        cpuBodyFormat: "A CPU ficou acima de %d%% por alguns segundos.",
        cpuTemperatureTitle: "CPU quente",
        cpuTemperatureBodyFormat: "A CPU chegou a %d °C.",
        memoryTitle: "Memória crítica",
        memoryBody: "A pressão de memória chegou ao nível crítico.",
        diskTitle: "Pouco espaço em disco",
        diskBodyFormat: "%@ está com menos de %d%% livre.",
        batteryTitle: "Bateria baixa",
        batteryBodyFormat: "A bateria está em %d%%.",
        batteryTemperature: "Temperatura alta da bateria",
        batteryTemperatureThreshold: "Temperatura acima de",
        batteryTemperatureTitle: "Bateria quente",
        batteryTemperatureBodyFormat: "A bateria chegou a %d °C."
    )

    static let tr = MonitorAlertFeatureStrings(
        section: "Uyarılar",
        caption: "Uyarılar seçilen eşiklere ulaşıldığında gönderilir. CPU kullanımı ve sıcaklık uyarıları yaklaşık 12 saniyeden kısa sıçramaları yok sayar. Tekrarlama ayarı yalnızca aynı uyarının tekrarlanmasını sınırlar.",
        notificationsDenied: "Sistem Ayarları’nda Vorssaint bildirimleri kapalı, bu yüzden uyarılar görünemez.",
        cpu: "Yüksek CPU",
        cpuTemperature: "Yüksek CPU sıcaklığı",
        memory: "Kritik bellek basıncı",
        disk: "Düşük disk alanı",
        battery: "Düşük pil",
        cpuThreshold: "CPU şu değerin üstünde",
        cpuTemperatureThreshold: "Sıcaklık şu değerin üstünde",
        diskThreshold: "Boş alan şu değerin altında",
        batteryThreshold: "Pil şu değerin altında",
        cooldown: "Aynı uyarıyı şu süre sonra yinele",
        cooldown2: "2 dakika",
        cooldown5: "5 dakika",
        cooldown15: "15 dakika",
        cooldown30: "30 dakika",
        cooldown60: "1 saat",
        cpuTitle: "Yüksek CPU",
        cpuBodyFormat: "CPU birkaç saniye boyunca %d%% üzerinde kaldı.",
        cpuTemperatureTitle: "CPU sıcak",
        cpuTemperatureBodyFormat: "CPU %d °C değerine ulaştı.",
        memoryTitle: "Kritik bellek",
        memoryBody: "Bellek basıncı kritik seviyeye ulaştı.",
        diskTitle: "Düşük disk alanı",
        diskBodyFormat: "%@ diskinde %d%% altında boş alan var.",
        batteryTitle: "Düşük pil",
        batteryBodyFormat: "Pil %d%% seviyesinde.",
        batteryTemperature: "Yüksek pil sıcaklığı",
        batteryTemperatureThreshold: "Sıcaklık şu değerin üstünde",
        batteryTemperatureTitle: "Pil sıcak",
        batteryTemperatureBodyFormat: "Pil %d °C değerine ulaştı."
    )

    static let ru = MonitorAlertFeatureStrings(
        section: "Оповещения",
        caption: "Оповещения появляются при достижении выбранных порогов. Загрузка CPU и температурные оповещения игнорируют скачки короче примерно 12 секунд. Настройка повтора ограничивает только повтор одного и того же оповещения.",
        notificationsDenied: "Уведомления Vorssaint выключены в Системных настройках, поэтому оповещения не появятся.",
        cpu: "Высокая нагрузка CPU",
        cpuTemperature: "Высокая температура CPU",
        memory: "Критическое давление памяти",
        disk: "Мало места на диске",
        battery: "Низкий заряд батареи",
        cpuThreshold: "CPU выше",
        cpuTemperatureThreshold: "Температура выше",
        diskThreshold: "Свободного места меньше",
        batteryThreshold: "Батарея ниже",
        cooldown: "Повторить то же оповещение через",
        cooldown2: "2 минуты",
        cooldown5: "5 минут",
        cooldown15: "15 минут",
        cooldown30: "30 минут",
        cooldown60: "1 час",
        cpuTitle: "Высокая нагрузка CPU",
        cpuBodyFormat: "CPU держался выше %d%% несколько секунд.",
        cpuTemperatureTitle: "CPU перегрет",
        cpuTemperatureBodyFormat: "CPU достиг %d °C.",
        memoryTitle: "Критическая память",
        memoryBody: "Давление памяти достигло критического уровня.",
        diskTitle: "Мало места на диске",
        diskBodyFormat: "На %@ осталось меньше %d%% свободного места.",
        batteryTitle: "Низкий заряд батареи",
        batteryBodyFormat: "Заряд батареи: %d%%.",
        batteryTemperature: "Высокая температура батареи",
        batteryTemperatureThreshold: "Температура выше",
        batteryTemperatureTitle: "Батарея перегрета",
        batteryTemperatureBodyFormat: "Батарея достигла %d °C."
    )

    static let es = MonitorAlertFeatureStrings(
        section: "Alertas",
        caption: "Las alertas aparecen cuando se alcanzan los límites elegidos. El uso de CPU y las alertas de temperatura ignoran los picos de menos de unos 12 segundos. El ajuste de repetición solo limita la repetición de la misma alerta.",
        notificationsDenied: "Las notificaciones de Vorssaint están desactivadas en Ajustes del Sistema, así que las alertas no aparecen.",
        cpu: "CPU alta",
        cpuTemperature: "Temperatura de CPU alta",
        memory: "Presión de memoria crítica",
        disk: "Poco espacio en disco",
        battery: "Batería baja",
        cpuThreshold: "CPU por encima de",
        cpuTemperatureThreshold: "Temperatura por encima de",
        diskThreshold: "Espacio libre por debajo de",
        batteryThreshold: "Batería por debajo de",
        cooldown: "Repetir la misma alerta después de",
        cooldown2: "2 minutos",
        cooldown5: "5 minutos",
        cooldown15: "15 minutos",
        cooldown30: "30 minutos",
        cooldown60: "1 hora",
        cpuTitle: "CPU alta",
        cpuBodyFormat: "La CPU estuvo por encima de %d%% durante unos segundos.",
        cpuTemperatureTitle: "CPU caliente",
        cpuTemperatureBodyFormat: "La CPU llegó a %d °C.",
        memoryTitle: "Memoria crítica",
        memoryBody: "La presión de memoria llegó al nivel crítico.",
        diskTitle: "Poco espacio en disco",
        diskBodyFormat: "%@ tiene menos de %d%% libre.",
        batteryTitle: "Batería baja",
        batteryBodyFormat: "La batería está al %d%%.",
        batteryTemperature: "Temperatura de la batería alta",
        batteryTemperatureThreshold: "Temperatura por encima de",
        batteryTemperatureTitle: "Batería caliente",
        batteryTemperatureBodyFormat: "La batería llegó a %d °C."
    )

    static let de = MonitorAlertFeatureStrings(
        section: "Warnungen",
        caption: "Warnungen erscheinen, wenn die gewählten Grenzwerte erreicht werden. CPU-Auslastung und Temperaturwarnungen ignorieren Spitzen, die kürzer als etwa 12 Sekunden dauern. Die Wiederholungseinstellung begrenzt nur die Wiederholung derselben Warnung.",
        notificationsDenied: "Mitteilungen für Vorssaint sind in den Systemeinstellungen aus, daher können keine Warnungen erscheinen.",
        cpu: "Hohe CPU",
        cpuTemperature: "Hohe CPU-Temperatur",
        memory: "Kritischer Speicherdruck",
        disk: "Wenig Speicherplatz",
        battery: "Niedriger Akkustand",
        cpuThreshold: "CPU über",
        cpuTemperatureThreshold: "Temperatur über",
        diskThreshold: "Freier Platz unter",
        batteryThreshold: "Akku unter",
        cooldown: "Dieselbe Warnung erneut nach",
        cooldown2: "2 Minuten",
        cooldown5: "5 Minuten",
        cooldown15: "15 Minuten",
        cooldown30: "30 Minuten",
        cooldown60: "1 Stunde",
        cpuTitle: "Hohe CPU",
        cpuBodyFormat: "Die CPU lag einige Sekunden über %d%%.",
        cpuTemperatureTitle: "Heiße CPU",
        cpuTemperatureBodyFormat: "Die CPU hat %d °C erreicht.",
        memoryTitle: "Kritischer Speicher",
        memoryBody: "Der Speicherdruck hat den kritischen Wert erreicht.",
        diskTitle: "Wenig Speicherplatz",
        diskBodyFormat: "%@ hat weniger als %d%% frei.",
        batteryTitle: "Niedriger Akkustand",
        batteryBodyFormat: "Der Akku ist bei %d%%.",
        batteryTemperature: "Hohe Akkutemperatur",
        batteryTemperatureThreshold: "Temperatur über",
        batteryTemperatureTitle: "Heißer Akku",
        batteryTemperatureBodyFormat: "Der Akku hat %d °C erreicht."
    )

    static let fr = MonitorAlertFeatureStrings(
        section: "Alertes",
        caption: "Les alertes apparaissent lorsque les seuils choisis sont atteints. L’utilisation du processeur et les alertes de température ignorent les pics de moins de 12 secondes environ. Le réglage de répétition limite uniquement la répétition de la même alerte.",
        notificationsDenied: "Les notifications de Vorssaint sont désactivées dans Réglages Système, les alertes ne peuvent donc pas apparaître.",
        cpu: "CPU élevé",
        cpuTemperature: "Température CPU élevée",
        memory: "Pression mémoire critique",
        disk: "Espace disque faible",
        battery: "Batterie faible",
        cpuThreshold: "CPU au-dessus de",
        cpuTemperatureThreshold: "Température au-dessus de",
        diskThreshold: "Espace libre sous",
        batteryThreshold: "Batterie sous",
        cooldown: "Répéter la même alerte après",
        cooldown2: "2 minutes",
        cooldown5: "5 minutes",
        cooldown15: "15 minutes",
        cooldown30: "30 minutes",
        cooldown60: "1 heure",
        cpuTitle: "CPU élevé",
        cpuBodyFormat: "Le CPU est resté au-dessus de %d%% pendant quelques secondes.",
        cpuTemperatureTitle: "CPU chaud",
        cpuTemperatureBodyFormat: "Le CPU a atteint %d °C.",
        memoryTitle: "Mémoire critique",
        memoryBody: "La pression mémoire a atteint le niveau critique.",
        diskTitle: "Espace disque faible",
        diskBodyFormat: "%@ a moins de %d%% libre.",
        batteryTitle: "Batterie faible",
        batteryBodyFormat: "La batterie est à %d%%.",
        batteryTemperature: "Température de la batterie élevée",
        batteryTemperatureThreshold: "Température au-dessus de",
        batteryTemperatureTitle: "Batterie chaude",
        batteryTemperatureBodyFormat: "La batterie a atteint %d °C."
    )

    static let it = MonitorAlertFeatureStrings(
        section: "Avvisi",
        caption: "Gli avvisi compaiono quando vengono raggiunte le soglie scelte. L’uso della CPU e gli avvisi di temperatura ignorano i picchi più brevi di circa 12 secondi. L’impostazione di ripetizione limita solo la ripetizione dello stesso avviso.",
        notificationsDenied: "Le notifiche di Vorssaint sono disattivate in Impostazioni di Sistema, quindi gli avvisi non compaiono.",
        cpu: "CPU alta",
        cpuTemperature: "Temperatura CPU alta",
        memory: "Pressione memoria critica",
        disk: "Poco spazio su disco",
        battery: "Batteria scarica",
        cpuThreshold: "CPU sopra",
        cpuTemperatureThreshold: "Temperatura sopra",
        diskThreshold: "Spazio libero sotto",
        batteryThreshold: "Batteria sotto",
        cooldown: "Ripeti lo stesso avviso dopo",
        cooldown2: "2 minuti",
        cooldown5: "5 minuti",
        cooldown15: "15 minuti",
        cooldown30: "30 minuti",
        cooldown60: "1 ora",
        cpuTitle: "CPU alta",
        cpuBodyFormat: "La CPU è rimasta sopra %d%% per alcuni secondi.",
        cpuTemperatureTitle: "CPU calda",
        cpuTemperatureBodyFormat: "La CPU ha raggiunto %d °C.",
        memoryTitle: "Memoria critica",
        memoryBody: "La pressione della memoria ha raggiunto il livello critico.",
        diskTitle: "Poco spazio su disco",
        diskBodyFormat: "%@ ha meno del %d%% libero.",
        batteryTitle: "Batteria scarica",
        batteryBodyFormat: "La batteria è al %d%%.",
        batteryTemperature: "Temperatura batteria alta",
        batteryTemperatureThreshold: "Temperatura sopra",
        batteryTemperatureTitle: "Batteria calda",
        batteryTemperatureBodyFormat: "La batteria ha raggiunto %d °C."
    )

    static let ja = MonitorAlertFeatureStrings(
        section: "アラート",
        caption: "選択したしきい値に達すると通知します。CPU 使用率と温度の通知は約 12 秒未満の短い急上昇を無視します。繰り返し設定は同じ通知の繰り返しだけを制限します。",
        notificationsDenied: "システム設定でVorssaintの通知がオフのため、アラートは表示されません。",
        cpu: "CPU 高負荷",
        cpuTemperature: "CPU 温度が高い",
        memory: "メモリ圧迫が深刻",
        disk: "ディスク空き容量不足",
        battery: "バッテリー残量低下",
        cpuThreshold: "CPU が次を超過",
        cpuTemperatureThreshold: "温度が次を超過",
        diskThreshold: "空き容量が次を下回る",
        batteryThreshold: "バッテリーが次を下回る",
        cooldown: "同じ通知を再度送るまで",
        cooldown2: "2 分",
        cooldown5: "5 分",
        cooldown15: "15 分",
        cooldown30: "30 分",
        cooldown60: "1 時間",
        cpuTitle: "CPU 高負荷",
        cpuBodyFormat: "CPU が数秒間 %d%% を超えました。",
        cpuTemperatureTitle: "CPU が高温",
        cpuTemperatureBodyFormat: "CPU が %d °C に達しました。",
        memoryTitle: "メモリが深刻",
        memoryBody: "メモリ圧迫が深刻レベルに達しました。",
        diskTitle: "ディスク空き容量不足",
        diskBodyFormat: "%@ の空き容量が %d%% 未満です。",
        batteryTitle: "バッテリー残量低下",
        batteryBodyFormat: "バッテリー残量は %d%% です。",
        batteryTemperature: "バッテリー温度が高い",
        batteryTemperatureThreshold: "温度が次を超過",
        batteryTemperatureTitle: "バッテリーが高温",
        batteryTemperatureBodyFormat: "バッテリーが %d °C に達しました。"
    )

    static let zhHans = MonitorAlertFeatureStrings(
        section: "提醒",
        caption: "达到所选阈值时会发出提醒。CPU 使用率和温度提醒会忽略短于约 12 秒的短暂峰值。重复设置仅限制同一提醒的重复频率。",
        notificationsDenied: "Vorssaint 的通知已在系统设置中关闭，警报无法显示。",
        cpu: "CPU 过高",
        cpuTemperature: "CPU 温度过高",
        memory: "内存压力严重",
        disk: "磁盘空间不足",
        battery: "电池电量低",
        cpuThreshold: "CPU 高于",
        cpuTemperatureThreshold: "温度高于",
        diskThreshold: "可用空间低于",
        batteryThreshold: "电量低于",
        cooldown: "再次发送同一提醒的间隔",
        cooldown2: "2 分钟",
        cooldown5: "5 分钟",
        cooldown15: "15 分钟",
        cooldown30: "30 分钟",
        cooldown60: "1 小时",
        cpuTitle: "CPU 过高",
        cpuBodyFormat: "CPU 已连续几秒高于 %d%%。",
        cpuTemperatureTitle: "CPU 过热",
        cpuTemperatureBodyFormat: "CPU 已达到 %d °C。",
        memoryTitle: "内存严重",
        memoryBody: "内存压力已达到严重级别。",
        diskTitle: "磁盘空间不足",
        diskBodyFormat: "%@ 的可用空间低于 %d%%。",
        batteryTitle: "电池电量低",
        batteryBodyFormat: "电池电量为 %d%%。",
        batteryTemperature: "电池温度过高",
        batteryTemperatureThreshold: "温度高于",
        batteryTemperatureTitle: "电池过热",
        batteryTemperatureBodyFormat: "电池已达到 %d °C。"
    )

    static let zhTW = MonitorAlertFeatureStrings(
        section: "提醒",
        caption: "達到所選門檻時會發出提醒。CPU 使用率和溫度提醒會忽略短於約 12 秒的短暫尖峰。重複設定只限制相同提醒的重複頻率。",
        notificationsDenied: "Vorssaint 的通知已在系統設定中關閉，警示無法顯示。",
        cpu: "CPU 使用率過高",
        cpuTemperature: "CPU 溫度過高",
        memory: "記憶體壓力過高",
        disk: "磁碟空間不足",
        battery: "電池電量偏低",
        cpuThreshold: "CPU 高於",
        cpuTemperatureThreshold: "溫度高於",
        diskThreshold: "可用空間低於",
        batteryThreshold: "電量低於",
        cooldown: "再次發送相同提醒的間隔",
        cooldown2: "2 分鐘",
        cooldown5: "5 分鐘",
        cooldown15: "15 分鐘",
        cooldown30: "30 分鐘",
        cooldown60: "1 小時",
        cpuTitle: "CPU 使用率過高",
        cpuBodyFormat: "CPU 已連續數秒高於 %d%%。",
        cpuTemperatureTitle: "CPU 過熱",
        cpuTemperatureBodyFormat: "CPU 已達到 %d °C。",
        memoryTitle: "記憶體壓力過高",
        memoryBody: "記憶體壓力已達到嚴重等級。",
        diskTitle: "磁碟空間不足",
        diskBodyFormat: "%@ 的可用空間低於 %d%%。",
        batteryTitle: "電池電量偏低",
        batteryBodyFormat: "電池電量為 %d%%。",
        batteryTemperature: "電池溫度過高",
        batteryTemperatureThreshold: "溫度高於",
        batteryTemperatureTitle: "電池過熱",
        batteryTemperatureBodyFormat: "電池已達到 %d °C。"
    )

    static let zhHK = MonitorAlertFeatureStrings(
        section: "提示",
        caption: "達到所選門檻時會發出提示。CPU 使用率和溫度提示會忽略短於約 12 秒的短暫尖峰。重複設定只限制相同提示的重複頻率。",
        notificationsDenied: "Vorssaint 的通知已在系統設定中關閉，警示無法顯示。",
        cpu: "CPU 使用率過高",
        cpuTemperature: "CPU 溫度過高",
        memory: "記憶體壓力過高",
        disk: "磁碟空間不足",
        battery: "電池電量偏低",
        cpuThreshold: "CPU 高於",
        cpuTemperatureThreshold: "溫度高於",
        diskThreshold: "可用空間低於",
        batteryThreshold: "電量低於",
        cooldown: "再次發出相同提示的間隔",
        cooldown2: "2 分鐘",
        cooldown5: "5 分鐘",
        cooldown15: "15 分鐘",
        cooldown30: "30 分鐘",
        cooldown60: "1 小時",
        cpuTitle: "CPU 使用率過高",
        cpuBodyFormat: "CPU 已連續數秒高於 %d%%。",
        cpuTemperatureTitle: "CPU 過熱",
        cpuTemperatureBodyFormat: "CPU 已達到 %d °C。",
        memoryTitle: "記憶體壓力過高",
        memoryBody: "記憶體壓力已達至嚴重水平。",
        diskTitle: "磁碟空間不足",
        diskBodyFormat: "%@ 的可用空間低於 %d%%。",
        batteryTitle: "電池電量偏低",
        batteryBodyFormat: "電池電量為 %d%%。",
        batteryTemperature: "電池溫度過高",
        batteryTemperatureThreshold: "溫度高於",
        batteryTemperatureTitle: "電池過熱",
        batteryTemperatureBodyFormat: "電池已達到 %d °C。"
    )
}
