// SPDX-License-Identifier: GPL-3.0-or-later
import Foundation

struct UXEntryStrings {
    var outputDevicesNeedMixer = "Output switching is unavailable while the volume mixer is off."
    var clipboardAutoClearTitle = "Automatic clipboard clearing"
    var cleanupRules = "Cleanup rules"
    var startupAndShortcuts = "Startup and shortcuts"
    var menuBarDisplay = "Menu bar display"
    var displayDevices = "Displays"
    var keyboardControl = "Keyboard control"
    var samplingAndUnits = "Sampling and metrics"
    var panelOrderHint = "Drag to reorder sections. Use the switches below to show or hide them."
    var removeFromListFormat = "Remove %@ from this list"
    var mandatoryException = "Required exception"

    var retentionAndBehavior = "Retention and closing behavior"
    var appearance = "Appearance"
    var radialProfileDetails = "Profile details"
    var radialProfileTriggers = "Triggers for this profile"
    var radialOpeningBehavior = "Opening behavior for all profiles"

    var activationAndShortcuts = "Activation and shortcuts"
    var appearanceAndPreviews = "Appearance and previews"
    var windowScope = "Windows to include"
    var interaction = "Interaction"
    var editRules = "View and edit rules"
    var captureOptions = "Capture options"
    var outputSettings = "Output and saving"
    var displayLocations = "Display locations"
    var monitorLocation = "Live metrics appear in the menu bar icon and the menu bar panel. Choose what each shows on its settings page."
    var openPanel = "Open menu bar panel"
    var chooseMenuBarMetrics = "Choose menu bar metrics…"
    var choosePanelContents = "Choose panel contents…"
    var panelLayout = "Arrange the full panel…"
    var showGroup = "Show this panel group"
    var hiddenGroupFormat = "The “%@” panel group is hidden. This entry will appear when the group is shown."
    var noDisplaySelected = "Neither the menu bar icon nor the panel shows any metrics."
    var panelUnavailable = "No visible menu bar anchor is available. Open Menu Bar Icon settings to restore an entry, then try again."
    var emptyPanel = "Some panel groups are hidden. Restore them in panel settings. Also check each module’s behavior settings."
    var emptyPanelInactive = "No panel content is currently available. Enable modules in Features and check their behavior settings."

    init(_ language: AppLanguage) {
        switch language {
        case .zhHans:
            outputDevicesNeedMixer = "暂不可用：输出切换需要启用音量混音器。"
            clipboardAutoClearTitle = "自动清空系统剪贴板"
            cleanupRules = "清理规则"
            startupAndShortcuts = "启动与快捷键"
            menuBarDisplay = "菜单栏显示"
            displayDevices = "显示器设备"
            keyboardControl = "键盘控制"
            samplingAndUnits = "采样与统计口径"
            panelOrderHint = "拖动以调整分区顺序。下面的开关控制显示或隐藏。"
            removeFromListFormat = "从此列表移除 %@"
            mandatoryException = "必需保留的例外"

            retentionAndBehavior = "保留与关闭行为"
            appearance = "显示"
            radialProfileDetails = "配置详情"
            radialProfileTriggers = "此配置的触发方式"
            radialOpeningBehavior = "所有配置的打开方式"

            activationAndShortcuts = "唤出与快捷键"
            appearanceAndPreviews = "显示与预览"
            windowScope = "窗口范围"
            interaction = "操作方式"
            editRules = "查看与编辑规则"
            captureOptions = "截图选项"
            outputSettings = "输出与保存"
            displayLocations = "显示位置"
            monitorLocation = "实时指标显示在菜单栏图标和菜单栏面板中，在各自的设置页选择显示哪些。"
            openPanel = "打开菜单栏面板"
            chooseMenuBarMetrics = "选择菜单栏显示的指标…"
            choosePanelContents = "选择面板显示的内容…"
            panelLayout = "调整完整面板布局…"
            showGroup = "显示此面板分组"
            hiddenGroupFormat = "面板中的“%@”分组已隐藏。显示该分组后，此入口才会出现。"
            noDisplaySelected = "菜单栏图标和面板都没有显示监控内容。"
            panelUnavailable = "没有可见的菜单栏入口。请进入菜单栏图标设置恢复入口后重试。"
            emptyPanel = "有面板分组已隐藏，可在面板设置中恢复显示。同时请检查各模块的运行设置。"
            emptyPanelInactive = "当前没有可显示的面板内容。请在“功能”中启用模块，并检查模块内的运行设置。"
        case .de:
            outputDevicesNeedMixer = "Der Ausgabewechsel benötigt den aktivierten Lautstärkemixer."
            clipboardAutoClearTitle = "Zwischenablage automatisch leeren"
            cleanupRules = "Bereinigungsregeln"
            startupAndShortcuts = "Start und Kurzbefehle"
            menuBarDisplay = "Menüleistenanzeige"
            displayDevices = "Displays"
            keyboardControl = "Tastatursteuerung"
            samplingAndUnits = "Abtastung und Messwerte"
            panelOrderHint = "Abschnitte zum Sortieren ziehen. Die Schalter unten steuern ihre Sichtbarkeit."
            removeFromListFormat = "%@ aus dieser Liste entfernen"
            mandatoryException = "Erforderliche Ausnahme"

            retentionAndBehavior = "Aufbewahrung und Schließverhalten"
            appearance = "Darstellung"
            radialProfileDetails = "Profildetails"
            radialProfileTriggers = "Auslöser für dieses Profil"
            radialOpeningBehavior = "Öffnungsverhalten für alle Profile"

            activationAndShortcuts = "Aufrufen und Kurzbefehle"
            appearanceAndPreviews = "Darstellung und Vorschauen"
            windowScope = "Einbezogene Fenster"
            interaction = "Bedienung"
            editRules = "Regeln anzeigen und bearbeiten"
            captureOptions = "Aufnahmeoptionen"
            outputSettings = "Ausgabe und Speichern"
            displayLocations = "Anzeigeorte"
            monitorLocation = "Live-Messwerte erscheinen im Menüleistensymbol und im Menüleistenpanel. Was jeweils angezeigt wird, legst du auf der zugehörigen Einstellungsseite fest."
            openPanel = "Menüleisten-Panel öffnen"
            chooseMenuBarMetrics = "Messwerte der Menüleiste auswählen…"
            choosePanelContents = "Panel-Inhalte auswählen…"
            panelLayout = "Gesamtes Panel anordnen…"
            showGroup = "Diese Panelgruppe anzeigen"
            hiddenGroupFormat = "Die Panelgruppe „%@“ ist ausgeblendet. Dieser Eintrag erscheint, sobald die Gruppe angezeigt wird."
            noDisplaySelected = "Weder das Menüleistensymbol noch das Panel zeigt Messwerte."
            panelUnavailable = "Kein sichtbarer Menüleisteneintrag verfügbar. Stelle einen Eintrag in den Menüleisteneinstellungen wieder her und versuche es erneut."
            emptyPanel = "Einige Panelgruppen sind ausgeblendet. Stelle sie in den Paneleinstellungen wieder her. Prüfe auch die Verhaltenseinstellungen der Module."
            emptyPanelInactive = "Derzeit sind keine Panelinhalte verfügbar. Aktiviere Module unter Funktionen und prüfe ihre Verhaltenseinstellungen."
        case .fr:
            outputDevicesNeedMixer = "Le changement de sortie nécessite le mélangeur de volume activé."
            clipboardAutoClearTitle = "Effacement automatique du presse-papiers"
            cleanupRules = "Règles de nettoyage"
            startupAndShortcuts = "Démarrage et raccourcis"
            menuBarDisplay = "Affichage dans la barre des menus"
            displayDevices = "Écrans"
            keyboardControl = "Commandes au clavier"
            samplingAndUnits = "Échantillonnage et mesures"
            panelOrderHint = "Faites glisser les sections pour les réordonner. Les interrupteurs ci-dessous contrôlent leur affichage."
            removeFromListFormat = "Retirer %@ de cette liste"
            mandatoryException = "Exception obligatoire"

            retentionAndBehavior = "Conservation et fermeture"
            appearance = "Apparence"
            radialProfileDetails = "Détails du profil"
            radialProfileTriggers = "Déclencheurs de ce profil"
            radialOpeningBehavior = "Ouverture de tous les profils"

            activationAndShortcuts = "Ouverture et raccourcis"
            appearanceAndPreviews = "Affichage et aperçus"
            windowScope = "Fenêtres à inclure"
            interaction = "Interaction"
            editRules = "Afficher et modifier les règles"
            captureOptions = "Options de capture"
            outputSettings = "Sortie et enregistrement"
            displayLocations = "Emplacements d’affichage"
            monitorLocation = "Les mesures en direct s’affichent dans l’icône et le panneau de la barre des menus. Choisissez leur contenu sur la page de réglages correspondante."
            openPanel = "Ouvrir le panneau de la barre des menus"
            chooseMenuBarMetrics = "Choisir les mesures de la barre des menus…"
            choosePanelContents = "Choisir le contenu du panneau…"
            panelLayout = "Organiser le panneau complet…"
            showGroup = "Afficher ce groupe du panneau"
            hiddenGroupFormat = "Le groupe « %@ » est masqué dans le panneau. Cette entrée apparaîtra lorsque le groupe sera affiché."
            noDisplaySelected = "Ni l’icône ni le panneau de la barre des menus n’affichent de mesures."
            panelUnavailable = "Aucune entrée visible dans la barre des menus. Rétablissez une entrée dans ses réglages, puis réessayez."
            emptyPanel = "Certains groupes sont masqués. Rétablissez leur affichage dans les réglages du panneau. Vérifiez aussi les réglages de comportement de chaque module."
            emptyPanelInactive = "Aucun contenu de panneau n’est actuellement disponible. Activez des modules dans Fonctions et vérifiez leurs réglages de comportement."
        case .es:
            outputDevicesNeedMixer = "El cambio de salida requiere activar el mezclador de volumen."
            clipboardAutoClearTitle = "Borrado automático del portapapeles"
            cleanupRules = "Reglas de limpieza"
            startupAndShortcuts = "Inicio y atajos"
            menuBarDisplay = "Visualización en la barra de menús"
            displayDevices = "Pantallas"
            keyboardControl = "Control con teclado"
            samplingAndUnits = "Muestreo y métricas"
            panelOrderHint = "Arrastra las secciones para ordenarlas. Los interruptores inferiores controlan su visibilidad."
            removeFromListFormat = "Quitar %@ de esta lista"
            mandatoryException = "Excepción obligatoria"

            retentionAndBehavior = "Conservación y cierre"
            appearance = "Apariencia"
            radialProfileDetails = "Detalles del perfil"
            radialProfileTriggers = "Activadores de este perfil"
            radialOpeningBehavior = "Apertura de todos los perfiles"

            activationAndShortcuts = "Apertura y atajos"
            appearanceAndPreviews = "Apariencia y vistas previas"
            windowScope = "Ventanas incluidas"
            interaction = "Interacción"
            editRules = "Ver y editar reglas"
            captureOptions = "Opciones de captura"
            outputSettings = "Salida y guardado"
            displayLocations = "Ubicaciones de visualización"
            monitorLocation = "Las métricas en tiempo real aparecen en el icono y el panel de la barra de menús. Elige qué muestra cada uno en su página de ajustes."
            openPanel = "Abrir el panel de la barra de menús"
            chooseMenuBarMetrics = "Elegir las métricas de la barra de menús…"
            choosePanelContents = "Elegir el contenido del panel…"
            panelLayout = "Organizar el panel completo…"
            showGroup = "Mostrar este grupo del panel"
            hiddenGroupFormat = "El grupo «%@» está oculto en el panel. Esta entrada aparecerá al mostrar el grupo."
            noDisplaySelected = "Ni el icono ni el panel de la barra de menús muestran métricas."
            panelUnavailable = "No hay una entrada visible en la barra de menús. Restáurala en sus ajustes y vuelve a intentarlo."
            emptyPanel = "Algunos grupos están ocultos. Restáuralos en los ajustes del panel. Comprueba también los ajustes de comportamiento de cada módulo."
            emptyPanelInactive = "No hay contenido disponible en el panel. Activa módulos en Funciones y comprueba sus ajustes de comportamiento."
        case .ja:
            outputDevicesNeedMixer = "出力の切り替えには音量ミキサーを有効にする必要があります。"
            clipboardAutoClearTitle = "クリップボードの自動消去"
            cleanupRules = "クリーンアップのルール"
            startupAndShortcuts = "起動とショートカット"
            menuBarDisplay = "メニューバー表示"
            displayDevices = "ディスプレイ"
            keyboardControl = "キーボード操作"
            samplingAndUnits = "サンプリングと統計"
            panelOrderHint = "ドラッグして並べ替えます。下のスイッチで表示と非表示を切り替えます。"
            removeFromListFormat = "このリストから %@ を削除"
            mandatoryException = "必須の例外"

            retentionAndBehavior = "保持と閉じる動作"
            appearance = "表示"
            radialProfileDetails = "プロファイルの詳細"
            radialProfileTriggers = "このプロファイルの呼び出し"
            radialOpeningBehavior = "全プロファイル共通の開き方"

            activationAndShortcuts = "呼び出しとショートカット"
            appearanceAndPreviews = "表示とプレビュー"
            windowScope = "表示するウィンドウ"
            interaction = "操作方法"
            editRules = "ルールを表示・編集"
            captureOptions = "撮影オプション"
            outputSettings = "出力と保存"
            displayLocations = "表示場所"
            monitorLocation = "リアルタイムの指標はメニューバーアイコンとメニューバーパネルに表示されます。表示内容はそれぞれの設定ページで選択します。"
            openPanel = "メニューバーパネルを開く"
            chooseMenuBarMetrics = "メニューバーに表示する指標を選択…"
            choosePanelContents = "パネルに表示する内容を選択…"
            panelLayout = "パネル全体の配置を変更…"
            showGroup = "このパネルグループを表示"
            hiddenGroupFormat = "パネルの「%@」グループは非表示です。グループを表示すると、この項目が表示されます。"
            noDisplaySelected = "メニューバーアイコンにもパネルにも指標が表示されていません。"
            panelUnavailable = "メニューバーに表示されている項目がありません。アイコン設定で表示を復元してから再試行してください。"
            emptyPanel = "非表示のパネルグループがあります。パネル設定で表示を戻せます。各モジュールの動作設定も確認してください。"
            emptyPanelInactive = "現在、パネルに表示できる内容がありません。「機能」でモジュールを有効にして、各モジュールの動作設定を確認してください。"
        default: break
        }
    }

    func hiddenGroup(_ name: String) -> String {
        String(format: hiddenGroupFormat, name)
    }
}
