// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Français — translated and hand-checked, not machine output.
extension Strings {
    static let fr = Strings(
        statusIdleTooltip: "\(AppInfo.name)\u{00A0}: veille normale",
        statusActiveUntil: "\(AppInfo.name)\u{00A0}: éveillé jusqu’à",
        statusActiveIndefinite: "\(AppInfo.name)\u{00A0}: éveillé indéfiniment",
        menuEnableAwake: "Activer le maintien éveillé",
        menuDisableAwake: "Désactiver le maintien éveillé",
        menuActivateFor: "Activer pour…",
        menuSettings: "Réglages…",
        menuAbout: "À propos de \(AppInfo.name)",
        menuQuit: "Quitter \(AppInfo.name)",
        menuHide: "Masquer \(AppInfo.name)",
        menuHideOthers: "Masquer les autres",
        menuShowAll: "Tout afficher",
        menuEdit: "Édition",
        menuUndo: "Annuler",
        menuRedo: "Rétablir",
        actionClear: "Effacer",
        actionRemove: "Retirer",
        actionBack: "Retour",
        actionSearch: "Rechercher",
        actionMute: "Couper le son",
        actionUnmute: "Réactiver le son",
        actionPlay: "Lire",
        actionPause: "Suspendre",
        menuCut: "Couper",
        menuCopy: "Copier",
        menuPaste: "Coller",
        menuSelectAll: "Tout sélectionner",
        menuWindow: "Fenêtre",
        menuMinimize: "Réduire",
        menuZoom: "Zoom",
        menuClose: "Fermer",

        minutes15: "15 minutes",
        minutes30: "30 minutes",
        hour1: "1 heure",
        hours2: "2 heures",
        hours4: "4 heures",
        hours8: "8 heures",
        indefinitely: "Indéfiniment",
        indefinite: "Indéfinie",

        panelSettings: "Réglages",
        panelQuit: "Quitter",

        keepAwakeTitle: "Garder éveillé",
        keepAwakeEndsIn: "Se termine dans",
        keepAwakeUntilDisabled: "Actif jusqu’à ce que vous le désactiviez",
        keepAwakeNormalRules: "Le Mac suit ses règles d’énergie normales",
        keepAwakeOptions: "Options",
        keepAwakeMouseJiggle: "Déplacer légèrement le pointeur",
        keepAwakeMouseJiggleCaption: "Pendant une session, déplace un peu le pointeur à l’intervalle choisi.",
        keepAwakeMouseJiggleInterval: "Intervalle",
        keepAwakeActiveIconLabel: "Icône active",
        keepAwakeActiveIconVorssaint: "\(AppInfo.name)",
        keepAwakeActiveIconCoffee: "Café",
        keepAwakeActiveIconEye: "Œil",
        keepAwakeActiveIconMoon: "Lune",
        keepAwakeActiveIconLight: "Ampoule",
        keepAwakeIconTintLabel: "Couleur de l’icône active",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Vert",
        keepAwakeIconTintBlue: "Bleu",
        keepAwakeIconTintPurple: "Violet",
        keepAwakeIconTintPink: "Rose",
        keepAwakeIconTintNone: "Sans couleur",
        durationLabel: "Durée",
        clamshellTitle: "Continuer écran rabattu",
        clamshellOnCaption: "Veille entièrement désactivée. Attention à l’énergie",
        clamshellNeedsSession: "Appliqué dès que «\u{00A0}Garder éveillé\u{00A0}» est actif",
        clamshellReady: "Prêt. Bascule sans mot de passe",
        clamshellNeedsPassword: "Demandera le mot de passe administrateur une fois",

        systemSection: "Système",
        temperatures: "Températures",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Utilisation du matériel",
        memorySection: "Mémoire",
        memoryPressure: "Pression",
        memorySwapUsed: "Swap utilisé",
        memoryCompressed: "Compressée",
        memoryCachedFiles: "Fichiers en cache",
        pressureNormal: "Normale",
        pressureWarning: "Attention",
        pressureCritical: "Critique",
        monitorUnavailable: "Capteurs indisponibles sur ce Mac",
        energyAppsTitle: "Consommation importante",
        energyAppsIdle: "Aucune consommation importante",

        notifySessionEndedTitle: "Session terminée",
        notifySessionEndedBody: "Le temps est écoulé. Le Mac se remettra en veille normalement.",
        notifyBatteryTitle: "\(AppInfo.name) désactivé",
        notifyBatteryBody: "Batterie faible. La veille normale a été rétablie pour préserver la charge.",
        adminPromptClamshellOff: "\(AppInfo.name) a besoin de votre mot de passe pour rétablir la veille normale du Mac.",
        adminPromptRecover: "\(AppInfo.name) a quitté alors que la veille du Mac était désactivée. Saisissez le mot de passe pour rétablir la veille normale.",
        adminPromptUpdate: "\(AppInfo.name) a besoin de votre mot de passe pour installer la mise à jour.",
        adminPromptSudoersInstall: "\(AppInfo.name) va créer une règle restreinte (pmset disablesleep uniquement) pour basculer le mode écran rabattu sans demander de mot de passe. C’est la seule fois où le mot de passe est nécessaire.",
        adminPromptSudoersRemove: "\(AppInfo.name) va supprimer la règle d’écran rabattu sans mot de passe.",

        settingsTitle: "Réglages de \(AppInfo.name)",
        tabGeneral: "Général",
        tabMouse: "Souris",
        tabDock: "Dock",
        tabWindowBehavior: "Comportement des fenêtres",
        tabKeyboard: "Clavier",
        tabTrackpad: "Trackpad",
        tabAdvanced: "Avancé",
        tabAbout: "À propos",
        tabReleaseNotes: "Nouveautés",
        advancedResetSection: "Autorisations",
        advancedResetDescription: "Retire toutes les autorisations que vous avez accordées à \(AppInfo.name) (Accessibilité, Enregistrement de l’écran, Accès complet au disque et autres), l’élément d’ouverture et la règle d’écran rabattu. Utile pour repartir de zéro ou avant de désinstaller. L’app reste installée.",
        advancedClearButton: "Effacer toutes les autorisations",
        advancedCleared: "Autorisations effacées.",
        advancedClearConfirmTitle: "Effacer toutes les autorisations\u{00A0}?",
        advancedClearConfirmBody: "Les fonctionnalités qui nécessitent des autorisations cesseront de fonctionner jusqu’à ce que vous les accordiez à nouveau. Vos réglages sont conservés.",
        advancedUninstallSection: "Désinstaller",
        advancedUninstallDescription: "Tente de supprimer les autorisations de l’app, son élément de connexion, sa règle sans mot de passe pour le mode capot fermé, ses réglages et ses données locales. Après sa fermeture, l’app tente de se déplacer vers la corbeille. Les sauvegardes et exports enregistrés séparément ne sont pas supprimés.",
        advancedUninstallButton: "Désinstaller complètement \(AppInfo.name)",
        advancedUninstallConfirmTitle: "Désinstaller \(AppInfo.name)\u{00A0}?",
        advancedUninstallConfirmBody: "\(AppInfo.name) va effacer ses autorisations, supprimer ses préférences et se placer dans la corbeille, puis quitter. L’app ne peut pas annuler cette action, mais elle reste dans la corbeille jusqu’à ce que vous la vidiez.",
        advancedUninstallFailedTitle: "Désinstallation interrompue",
        advancedUninstallFailedBody: "\(AppInfo.name) n’a pas pu rétablir un réglage système qu’il avait modifié\u{00A0}: la veille, la vitesse des ventilateurs ou l’accélération de la souris. Rien n’a été supprimé. Réessayez et autorisez la demande de mot de passe si elle apparaît.",

        launchAtLogin: "Ouvrir à l’ouverture de session",
        languageLabel: "Langue",
        showCountdown: "Afficher le temps restant à côté de l’icône",
        hotkeyToggle: "Activer le raccourci pour «\u{00A0}Garder éveillé\u{00A0}»",
        hotkeyCaption: "Fonctionne dans toutes les apps, sans autorisation supplémentaire.",

        sessionSection: "Session",
        defaultDurationLabel: "Durée par défaut",
        keepAwakeAutoStart: "Garder éveillé à l’ouverture de \(AppInfo.name)",
        keepAwakeAutoStartCaption: "Démarre une session avec la durée par défaut.",
        batteryProtectionSection: "Protection de la batterie",
        batteryDisableBelow: "Désactiver lorsque la batterie passe sous",
        batteryNever: "Jamais",
        batteryProtectionCaption: "Empêche une session oubliée de vider la batterie du MacBook.",
        clamshellSection: "Écran rabattu",
        configuring: "Configuration…",
        sudoersFailed: "Impossible d’activer l’écran rabattu. Réessayez.",
        clamshellExplanation: "«\u{00A0}Continuer écran rabattu\u{00A0}» désactive entièrement la veille tant que «\u{00A0}Garder éveillé\u{00A0}» est actif et se rétablit automatiquement à la fin de la session ou quand l’app quitte. À privilégier branché sur secteur.",

        scrollSection: "Défilement",
        invertMouseScroll: "Inverser le défilement de la souris",
        invertMouseScrollCaption: "Inverse le sens de la molette de la souris.",
        scrollTrackpadNote: "Le trackpad n’est pas affecté\u{00A0}: il conserve le défilement naturel de macOS.",
        scrollActiveNow: "Inversion du défilement de la souris en cours",
        mouseNavigationActiveNow: "Boutons latéraux actifs en ce moment",
        smoothScrollName: "Défilement fluide",
        smoothScrollCaption: "Transforme chaque cran de la molette de la souris en un court glissement fluide. Le trackpad ne change pas.",
        smoothScrollStepLabel: "Vitesse de défilement",
        mouseNavigationEnable: "Utiliser les boutons latéraux pour Précédent et Suivant",
        mouseNavigationCaption: "Transforme les boutons Précédent et Suivant de la souris en commandes de navigation dans le Finder, les navigateurs et les apps compatibles.",
        middleClickSection: "Clic du milieu",
        middleClickEnable: "Le clic à trois doigts devient un clic du milieu",
        middleClickEnableCaption: "Appuyer sur le trackpad avec trois doigts agit comme un clic sur la molette de la souris\u{00A0}: ouvrir les liens dans un nouvel onglet, fermer des onglets et tout ce que fait le bouton du milieu.",
        middleClickDragConflict: "Le glissement à trois doigts de macOS est activé et utilise ce même geste. Désactivez-le dans Réglages Système, sous Accessibilité, Contrôle du pointeur, Options du trackpad, pour que le clic du milieu fonctionne.",
        middleClickTapPicker: "Un tapotement léger clique aussi",
        middleClickTapOff: "Désactivé",
        middleClickTapThreeFingers: "3 doigts",
        middleClickTapFourFingers: "4 doigts",
        middleClickTapCaption: "Un tapotement léger avec ce nombre de doigts, sans appuyer, déclenche aussi le clic du milieu. Glisser ne compte jamais. Si le tapotement à trois doigts de macOS est assigné à Rechercher, désactivez-le pour que les deux ne se déclenchent pas ensemble.",
        quickToolShortcutToggle: "Raccourci global",
        ocrName: "Copier le texte à l’écran",
        ocrCaption: "Sélectionnez une zone de l’écran et le texte reconnu est copié, prêt à coller.",
        ocrCopied: "Texte copié",
        ocrNoText: "Aucun texte trouvé",
        colorPickerName: "Pipette de couleur",
        colorPickerCaption: "Capturez la couleur de n’importe quel pixel de l’écran et copiez-la dans le format de votre choix.",
        colorPickerFormatLabel: "Format copié",
        colorPickerBareHexToggle: "Copier sans le préfixe #",
        colorPickerPickNow: "Prélever la couleur",
        pastePlainName: "Coller en texte brut",
        pastePlainCaption: "Colle ce qui a été copié sans couleurs, polices ni mise en forme. L’original reste dans le presse-papiers.",
        switcherSection: "Sélecteur d’apps",
        switcherEnable: "Utiliser le sélecteur \(AppInfo.name)",
        switcherEnableCaption: "Passez d’une app ou fenêtre à l’autre, y compris les fenêtres minimisées et plusieurs fenêtres d’une même app.",
        switcherNoWindows: "Aucune fenêtre ouverte",
        appQuitFailedFormat: "Impossible de demander la fermeture de %@.",
        switcherIconRowMode: "Afficher %@ avec de grandes icônes",
        switcherIconRowModeCaption: "Affiche une icône par app avec les aperçus de ses fenêtres au-dessus.",
        switcherSimpleMode: "Sélecteur d’apps simple",
        switcherSimpleModeCaption: "Affiche les icônes des apps et les titres des fenêtres, sans aperçu ni capture d’écran par le sélecteur.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Fenêtres",
        switcherWindowShortcutCaption: "Ouvre un sélecteur pour les fenêtres de l’app au premier plan. Sélecteur d’apps ouvert, passe d’une fenêtre à l’autre de l’app sélectionnée.",
        switcherTakeOverSystemShortcuts: "Remplacer ⌘Tab et ⌘` de macOS",
        switcherTakeOverSystemShortcutsCaption: "Désactive les raccourcis macOS correspondants uniquement lorsque le sélecteur \(AppInfo.name) est actif. Toutes les apps ouvertes restent accessibles.",
        switcherAppearanceDelay: "Délai d’affichage",
        switcherAppearanceDelayCaption: "Durée pendant laquelle le raccourci doit rester enfoncé avant l’affichage du sélecteur.",
        switcherMergeTabs: "Afficher une seule entrée par app",
        switcherMergeTabsCaption: "Regroupe toutes les fenêtres d’une app en une seule entrée dans le sélecteur, au lieu d’une entrée par fenêtre.",
        switcherWindowlessApps: "Apps sans fenêtre ouverte",
        switcherWindowlessAppsCaption: "Choisit quelles apps ouvertes sans aucune fenêtre apparaissent dans le sélecteur.",
        switcherWindowlessAppsOff: "Ne pas afficher",
        switcherWindowlessAppsFinder: "Finder uniquement",
        switcherWindowlessAppsAll: "Toutes les apps",
        switcherNoOpenWindow: "Sans fenêtre ouverte",
        switcherOtherDesktop: "Autre bureau",

        cutPasteName: "Couper-coller",
        cutPasteEnable: "Couper-coller des fichiers dans le Finder",
        cutPasteEnableCaption: "Utilisez ⌘X pour couper et ⌘V pour déplacer des fichiers et des dossiers dans le Finder.",
        cutPasteShowHUD: "Afficher le panneau flottant",
        cutPasteShowHUDCaption: "Affiche un indicateur flottant avec les fichiers coupés lorsque le Finder est actif.",
        cutPasteHowTitle: "Comment l’utiliser",
        cutPasteStep1: "Sélectionnez des éléments dans le Finder et appuyez sur ⌘X pour les couper.",
        cutPasteStep2: "Ouvrez le dossier de destination et appuyez sur ⌘V pour les y déplacer.",
        cutPasteTextNote: "Dans les champs de texte (comme lors d’un renommage), ⌘X et ⌘V continuent de fonctionner normalement.",
        cutPasteActiveNow: "Prêt à couper dans le Finder",
        cutPasteAutomationNote: "La première fois, macOS demande l’autorisation de contrôler le Finder.",
        cutReadyTitle: "Coupé",
        cutReadyHint: "dans le dossier de destination pour déplacer",
        cutCancel: "Annuler la coupe",
        cutDoneTitle: "Déplacé\u{00A0}!",
        cutMovedSingular: "1 élément déplacé",
        cutMovedPluralFormat: "%d éléments déplacés",
        cutSomeFailed: "Certains éléments n’ont pas pu être déplacés",
        cutMovingTitle: "Déplacement…",
        cutMovingCountFormat: "%d sur %d",

        autoQuitName: "Quitter à la fermeture",
        autoQuitEnable: "Quitter une app à la fermeture de sa dernière fenêtre",
        autoQuitEnableCaption: "Fermer la dernière fenêtre d’une app la fait aussi quitter.",
        autoQuitActiveNow: "Actif en ce moment",
        autoQuitStep1: "Fermez la dernière fenêtre d’une app (⌘W ou le bouton rouge).",
        autoQuitStep2: "L’app quitte d’elle-même. Les fenêtres «\u{00A0}Enregistrer les modifications\u{00A0}?\u{00A0}» s’affichent toujours.",
        autoQuitPredictableNote: "Les apps qui fonctionnent normalement sans fenêtre ne quittent jamais.",
        autoQuitExceptionsTitle: "Exceptions",
        autoQuitExceptionsCaption: "Les apps de cette liste restent ouvertes même sans aucune fenêtre.",
        autoQuitExceptionsEmpty: "Aucune exception",
        autoQuitAddApp: "Ajouter une app…",

        uninstallerName: "Programme de désinstallation",
        uninstallerEnableCaption: "Retire une app avec les caches, les préférences, les journaux et les résidus qu’elle laisse derrière elle.",
        uninstallerMenuItem: "Désinstaller une app…",
        uninstallerDropTitle: "Glissez une app ici",
        uninstallerDropSubtitle: "ou choisissez-en une à analyser",
        uninstallerChoose: "Choisir une app…",
        uninstallerPickerTitle: "Choisir une app",
        uninstallerPickerSearch: "Rechercher des apps",
        uninstallerPickerEmpty: "Aucune app trouvée",
        uninstallerEmptyNote: "Rien n’est retiré sans votre confirmation.",
        uninstallerFDANote: "Accordez l’Accès complet au disque pour une analyse plus approfondie.",
        uninstallerFDAGrant: "Accorder l’accès…",
        uninstallerFDAHint: "Activez \(AppInfo.name) dans la liste. S’il ne s’y trouve pas, cliquez sur + et choisissez \(AppInfo.name) dans Applications. L’accès ne s’applique qu’après la réouverture de l’app.",
        uninstallerFDARelaunch: "Relancer maintenant",
        uninstallerScanning: "Analyse des fichiers…",
        uninstallerRemoving: "Déplacement vers la corbeille…",
        uninstallerFoundTitle: "trouvé",
        uninstallerSelectedFormat: "%d sur %d sélectionnés",
        uninstallerRemove: "Placer dans la corbeille",
        uninstallerCancel: "Annuler",
        uninstallerDoneTitle: "Terminé\u{00A0}!",
        uninstallerFreedFormat: "Données supprimées : %@",
        uninstallerSomeFailed: "Certains éléments n’ont pas pu être placés dans la corbeille.",
        uninstallerConfirmationExpired: "Cette confirmation n’est plus valable. Vérifiez les éléments actuels et confirmez à nouveau.",
        uninstallerFailedNeedsFDA: "Les données des apps en bac à sable ne peuvent être déplacées qu’avec l’accès complet au disque. Le mot de passe administrateur ne le remplace pas.",
        uninstallerFailedMoreFormat: "et %d autres",
        uninstallerAnother: "Désinstaller une autre app",
        uninstallerCatApp: "Application",
        uninstallerCatSupport: "Assistance",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Préférences",
        uninstallerCatContainers: "Conteneurs",
        uninstallerCatLogs: "Journaux",
        uninstallerCatState: "État enregistré",
        uninstallerCatOther: "Autres",

        urlCleanerName: "Nettoyer l’URL",
        urlCleanerEnable: "Nettoyer automatiquement les URL à la copie",
        urlCleanerEnableCaption: "Retire les paramètres de suivi d’un lien dès qu’il arrive dans le presse-papiers.",
        urlCleanerActiveNow: "Actif en ce moment",
        urlCleanerManualTitle: "Nettoyer maintenant",
        urlCleanerInputPlaceholder: "Collez une URL",
        urlCleanerOutputPlaceholder: "L’URL nettoyée apparaît ici",
        urlCleanerCleanButton: "Nettoyer",
        urlCleanerPasteButton: "Coller",
        urlCleanerCopyButton: "Copier",
        urlCleanerClearButton: "Vider le champ",
        urlCleanerNoURL: "Collez une URL valide.",
        urlCleanerNoChange: "Rien à nettoyer.",
        urlCleanerCleaned: "URL nettoyée.",
        urlCleanerCopied: "Copié.",
        urlCleanerLocalNote: "Local. Sans réseau.",

        homebrewName: "Homebrew",
        homebrewMissingTitle: "Homebrew introuvable",
        homebrewMissingBody: "Homebrew n’est pas installé. Une fois installé, les paquets qu’il gère apparaissent ici.",
        homebrewRequested: "Installés par vous",
        homebrewMasApps: "App Store",
        homebrewCopyName: "Copier le nom",
        homebrewTrustTitle: "Tap pas encore approuvé",
        homebrewTrustCaption: "Homebrew demande désormais votre confirmation avant d’utiliser des taps tiers. Approuvez %@ pour continuer.",
        homebrewTrustButton: "Approuver et continuer",
        homebrewNoPackages: "Aucun paquet trouvé",
        homebrewUninstall: "Désinstaller",
        homebrewUpgrade: "Mettre à jour",
        homebrewPinnedVersion: "Version verrouillée",
        homebrewAllPackages: "paquets",
        homebrewOpenTerminal: "Ouvrir Terminal",
        homebrewCancelOperation: "Annuler",
        homebrewClearLog: "Effacer le journal",
        homebrewHomepage: "Ouvrir le site",
        homebrewUpdateAvailableBadge: "Mise à jour disponible",
        homebrewConfirmUninstallTitle: "Désinstaller avec Homebrew\u{00A0}?",
        homebrewConfirmUninstallBodyFormat: "Homebrew va désinstaller %@. Des fichiers de configuration peuvent rester sur le système.",
        homebrewConfirmUpgradeTitle: "Mettre à jour avec Homebrew\u{00A0}?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew va télécharger et appliquer la dernière version de %@. Des dépendances peuvent aussi être mises à jour.",
        homebrewTerminalFallback: "Cette opération nécessite Terminal pour demander le mot de passe administrateur. \(AppInfo.name) ne capture pas les mots de passe.",
        homebrewLoading: "Chargement…",
        homebrewOperationUninstallFormat: "Désinstallation de %@",
        homebrewOperationUpgradeFormat: "Mise à jour de %@",
        homebrewOperationUpdateHomebrew: "Mise à jour de Homebrew",
        homebrewOperationUninstalledFormat: "%@ désinstallé.",
        homebrewOperationUpgradedFormat: "%@ mis à jour.",
        homebrewOperationUpdatedHomebrew: "Homebrew mis à jour.",
        homebrewOperationFailedFormat: "Impossible de terminer %@.",
        homebrewOperationCancelled: "Opération annulée.",
        homebrewOperationPreparing: "Préparation…",
        homebrewOperationDownloading: "Téléchargement des fichiers…",
        homebrewOperationUninstalling: "Suppression des fichiers…",
        homebrewOperationUpgrading: "Mise à jour des fichiers…",
        homebrewOperationFinalizing: "Finalisation…",
        homebrewOperationRefreshing: "Actualisation de la liste…",
        homebrewOperationTerminal: "Continuez dans Terminal.",
        homebrewOperationElapsedFormat: "%@ écoulés",
        homebrewOperationShowDetails: "Afficher les détails",
        homebrewOperationHideDetails: "Masquer les détails",
        homebrewOperationTechnicalLog: "Détails techniques",
        homebrewOperationProgressUnknown: "Homebrew n’a pas encore indiqué de pourcentage.",

        mediaName: "Médias",
        mediaEnableCaption: "Compressez les vidéos, convertissez et traitez les images, créez des GIFs et extrayez du texte localement.",
        mediaLocalNote: "Local. Sans réseau.",
        mediaToolVideo: "Vidéo",
        mediaToolGIF: "GIF",
        mediaToolImage: "Image",
        mediaToolText: "Texte",
        mediaSelectFile: "Choisir un fichier",
        mediaDropHint: "Déposez un fichier ici ou cliquez pour choisir.",
        mediaOutput: "Sortie",
        mediaOutputAutomatic: "Automatique",
        mediaChooseOutput: "Destination",
        mediaStartVideo: "Compresser la vidéo",
        mediaStartGIF: "Créer un GIF",
        mediaStartImage: "Traiter l’image",
        mediaStartConvertPDF: "Convertir en PDF",
        mediaStartText: "Extraire le texte",
        mediaCancel: "Annuler",
        mediaStartTime: "Début",
        mediaEndTime: "Fin",
        mediaQuality: "Compression",
        mediaCompressionLow: "Faible",
        mediaCompressionMedium: "Moyenne",
        mediaCompressionHigh: "Forte",
        mediaMaxSize: "Taille",
        mediaSizingResolution: "Résolution",
        mediaSizingFileSize: "Poids",
        mediaTargetSize: "Poids visé",
        mediaTargetSizeHint: "La résolution s’adapte pour rester sous la limite.",
        mediaErrorTargetTooSmall: "Poids visé trop bas pour ce clip. Raccourcissez-le ou augmentez la limite.",
        mediaMegabytesSuffix: " Mo",
        mediaWidth: "Largeur",
        mediaFPS: "FPS",
        mediaFormat: "Format",
        mediaStripMetadata: "Supprimer les métadonnées",
        mediaLoopGIF: "Boucler le GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Précis",
        mediaOCRFast: "Rapide",
        mediaRunning: "Traitement",
        mediaCompleted: "Terminé",
        mediaCancelled: "Annulé.",
        mediaOpenInFinder: "Afficher",
        mediaCopyText: "Copier le texte",
        mediaRunAgain: "Relancer",
        mediaEmptyText: "Aucun texte trouvé.",
        mediaResultSavedFormat: "Enregistré sous %@",
        mediaResultSizeFormat: "%@ vers %@",
        mediaResultGrewCaption: "Le fichier converti est plus volumineux que l’original.",
        mediaErrorNoFile: "Choisissez d’abord un fichier.",
        mediaErrorNoVideo: "Ce fichier ne contient pas de piste vidéo.",
        mediaErrorSameOutput: "Choisissez une destination différente du fichier original.",
        mediaErrorUnsupported: "Format non pris en charge par macOS.",

        shelfName: "Étagère",
        shelfEnable: "Espace temporaire pour glisser des fichiers",
        shelfEnableCaption: "Un espace flottant pour rassembler fichiers, images et texte, puis les glisser ailleurs plus tard.",
        shelfHowTitle: "Comment l’utiliser",
        shelfStep1: "Ouvrez-la avec le raccourci, ou en secouant la souris pendant un glissement.",
        shelfStep2: "Déposez-y des fichiers, des images, des liens ou du texte pour les conserver.",
        shelfStep3: "Glissez chaque élément vers n’importe quelle app au moment voulu.",
        shelfShakeToggle: "Ouvrir en secouant la souris pendant un glissement",
        shelfShakeCaption: "Secouez rapidement le pointeur tout en tenant un élément pour faire apparaître l’étagère près du curseur.",
        shelfDropZoneToggle: "Garder les fichiers glissés dans la barre des menus",
        shelfDropZoneCaption: "Pendant que vous faites glisser un fichier, l’étagère apparaît sous l’icône de la barre des menus. Ce que vous déposez y reste, dans un bouton que vous réduisez et ouvrez d’un clic et qui disparaît une fois l’étagère vide.",
        shelfCollapse: "Réduire",
        shelfBehaviorTitle: "Après utilisation",
        shelfCloseAfterDrop: "Fermer après un dépôt dans une autre app",
        shelfCloseAfterDropCaption: "Ferme l’étagère quand la destination accepte les éléments. L’épingle du panneau la maintient ouverte.",
        shelfRemoveAfterDrop: "Retirer les éléments après le dépôt",
        shelfRemoveAfterDropCaption: "Les éléments acceptés par une autre app quittent l’étagère. Désactivez cette option pour en garder une copie.",
        shelfExclusionsTitle: "Exceptions automatiques",
        shelfExclusionsEmpty: "Aucune app ajoutée.",
        shelfExclusionsCaption: "Le geste de secousse et la zone de dépôt restent inactifs pour les glissements commencés dans ces apps. Le raccourci et Ouvrir restent disponibles.",
        shelfPin: "Maintenir ouverte",
        shelfUnpin: "Autoriser la fermeture après utilisation",
        shelfHotkeyLabel: "Raccourci",
        shelfOpenNow: "Ouvrir maintenant",
        shelfNoPermission: "Ne nécessite aucune autorisation.",
        shelfMenuItem: "Ouvrir l’étagère",
        shelfTitle: "Étagère",
        shelfEmpty: "Glissez des éléments ici",
        shelfClearAll: "Tout effacer",
        shelfRemoveSelected: "Retirer la sélection",
        shelfSelectedFormat: "%d sélectionnés",
        shelfHint: "Cliquez pour sélectionner. Glissez pour utiliser ou faites un clic droit pour plus d’actions.",
        shelfItemImage: "Image",
        shelfTooltipItemsFormat: "%d éléments",
        shelfTooltipItemsFew: "%d éléments",
        shelfTooltipImageSingular: "%d image",
        shelfTooltipImageFew: "%d images",
        shelfTooltipImagePlural: "%d images",
        shelfTooltipFileSingular: "%d fichier",
        shelfTooltipFileFew: "%d fichiers",
        shelfTooltipFilePlural: "%d fichiers",
        shelfTooltipNoteSingular: "%d note",
        shelfTooltipNoteFew: "%d notes",
        shelfTooltipNotePlural: "%d notes",
        shelfTooltipLinkSingular: "%d lien",
        shelfTooltipLinkFew: "%d liens",
        shelfTooltipLinkPlural: "%d liens",
        shelfActionOpen: "Ouvrir",
        shelfActionOpenWith: "Ouvrir avec",
        shelfActionShare: "Partager",

        breakdownMeasuring: "Mesure…",

        preciseVolumeRollerEnable: "Utiliser des pas de volume plus fins",
        preciseVolumeRollerCaption: "Transforme molettes et touches de volume en pas système plus petits.",
        preciseVolumeRollerTapFailed: "Impossible d’écouter les touches de volume.",

        updatesSection: "Mises à jour",
        autoCheckToggle: "Rechercher les mises à jour automatiquement",
        betaBadgeLabel: "Bêta",
        checkNowButton: "Rechercher maintenant",
        updateChecking: "Recherche…",
        updateUpToDate: "Vous disposez de la dernière version.",
        updateAvailablePrefix: "Mise à jour disponible\u{00A0}:",
        updateInstallButton: "Télécharger et installer",
        updateDownloading: "Téléchargement de la mise à jour…",
        updateInstalling: "Installation et redémarrage…",
        updateFailedPrefix: "Recherche impossible\u{00A0}:",
        updateLastChecked: "Dernière recherche\u{00A0}:",
        updateNotifyTitle: "Mise à jour de \(AppInfo.name)",
        updateInstallFailedBody: "La mise à jour a été téléchargée mais n’a pas pu être appliquée. Téléchargez la dernière version depuis la page des releases GitHub et faites glisser l’app par-dessus l’actuelle.",
        updateNeedsApplicationsTitle: "Déplacez \(AppInfo.name) vers Applications",
        updateNeedsApplicationsBody: "L’app s’exécute depuis un emplacement qui ne peut pas être mis à jour, comme l’image disque ou un emplacement temporaire du système. Faites glisser \(AppInfo.name) dans le dossier Applications, ouvrez-le depuis là et réessayez.",
        menuCheckUpdates: "Rechercher les mises à jour…",

        permissionRequired: "Autorisation requise",
        permissionAccessibility: "Accessibilité",
        permissionScreenRecording: "Enregistrement de l’écran",
        permissionGranted: "Accordée",
        permissionMissing: "Non accordée",
        permissionOpenSettings: "Ouvrir les Réglages Système…",
        permissionRequest: "Accorder l’accès",
        permissionRestartNote: "macOS peut demander de rouvrir l’app après l’avoir accordée.",

        aboutDescription: "Un centre d’utilitaires pour votre Mac.\nÉnergie, moniteur système, défilement et sélecteur de fenêtres, directement dans la barre des menus.",
        versionPrefix: "Version",
        reviewIntro: "Revoir l’introduction",
        reviewHighlights: "Revoir les nouveautés",
        viewOnGitHub: "Voir sur GitHub",

        obContinue: "Continuer",
        obBack: "Retour",
        obStart: "Ouvrir \(AppInfo.name)",
        obStepWelcomeTitle: "Bienvenue dans \(AppInfo.name)",
        obStepWelcomeBody: "Un utilitaire discret dans la barre des menus qui rend macOS plus pratique au quotidien.",
        obWelcomeBullet1Title: "Énergie maîtrisée",
        obWelcomeBullet1Body: "Gardez le Mac éveillé aussi longtemps que vous le souhaitez, même écran rabattu.",
        obWelcomeBullet2Title: "Une vue claire du système",
        obWelcomeBullet2Body: "Températures du CPU, du GPU et de la batterie, utilisation du matériel et pression de la mémoire en temps réel.",
        obWelcomeBullet3Title: "Souris et fenêtres à votre façon",
        obWelcomeBullet3Body: "Défilement de souris inversé et un sélecteur de fenêtres avec miniatures.",
        obLanguageLabel: "Langue",
        obStepDoneTitle: "Tout est prêt\u{00A0}!",
        obStepDoneBody: "\(AppInfo.name) veille déjà sur votre Mac.",
        obDoneHint: "Cherchez l’icône de pieuvre dans la barre des menus, en haut à droite de l’écran.",
        obWhatsNewTitle: "Nouveautés de cette version",
        obWhatsNewFallback: "Cette mise à jour inclut les derniers correctifs et améliorations.",
        obPurposeTitle: "Qu’est-ce qui vous amène\u{00A0}?",
        obPurposeBody: "Choisissez les fonctions à activer. Vos options actuelles sont conservées.",
        obPurposeSkip: "Vous pourrez ajouter ou retirer des fonctions dans les Réglages.",

        tabMonitor: "Moniteur",
        tabMenuBarIcon: "Icône de la barre des menus",
        tabMenuBarPanel: "Panneau de la barre des menus",
        monitorMenuBarSection: "Dans la barre des menus",
        monitorCombineTemperatures: "Combiner utilisation et température",
        monitorCombineTemperaturesCaption: "Quand l’utilisation et la température du même élément sont activées, elles s’affichent dans un seul bloc.",
        monitorSeparateMenuBarMetrics: "Séparer les mesures en éléments dédiés",
        monitorSeparateMenuBarMetricsCaption: "Sépare les blocs actifs dans la barre des menus et garde utilisation et température ensemble quand combiner est actif.",
        monitorNetworkUploadFirst: "Envoi au-dessus du téléchargement",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Mémoire",
        monitorShowNetwork: "Réseau",
        monitorShowPowerLabel: "Énergie",
        monitorIntervalLabel: "Actualiser toutes les",
        monitorInterval1: "1 seconde",
        monitorInterval2: "2 secondes",
        monitorInterval5: "5 secondes",
        monitorPanelSection: "Dans le panneau",
        betaBadge: "BETA",
        betaFeatureWarning: "Bêta. Vous pouvez rencontrer quelques bugs.",

        networkSection: "Réseau",
        networkDownload: "Téléchargement",
        networkUpload: "Envoi",
        networkThisSession: "Cette session",
        networkMeasuring: "Mesure…",
        networkApps: "Apps utilisant le réseau",
        networkAppsIdle: "Aucune app n’utilise le réseau",

        diskSection: "Disques",
        diskUsed: "utilisé",
        diskAvailable: "disponible",
        diskPurgeable: "purgeable",
        diskInternal: "Interne",
        diskExternal: "Externe",
        diskSelect: "Choisir un disque",
        diskRead: "Lecture",
        diskWrite: "Écriture",
        diskSMARTStatus: "État",
        diskSMARTUnavailable: "SMART indisponible pour ce disque",
        diskTotalRead: "Total lu",
        diskTotalWritten: "Total écrit",
        diskTemperature: "Température",
        diskHealth: "Santé",
        diskPowerCycles: "Cycles",
        diskPowerOnHours: "Heures allumé",
        diskEject: "Éjecter",
        diskEjectAll: "Tout éjecter",
        diskEjecting: "Éjection…",
        diskReadyToRemove: "Prêt à retirer",
        diskEjectFailed: "Impossible d’éjecter",
        diskProtectionCaption: "Éjectez avant de débrancher.",
        diskNoExternal: "Aucun disque externe prêt à être éjecté.",
        diskOpenInFinder: "Ouvrir",
        diskStorageSettings: "Stockage",
        diskNoDisks: "Aucun disque monté trouvé.",

        powerSection: "Énergie",
        powerSystem: "Système",
        powerAdapter: "Adaptateur",
        powerBattery: "Batterie",
        powerCharging: "En charge",
        powerOnBattery: "Sur batterie",
        powerPluggedIn: "Branché",
        powerUnavailable: "Mesures d’énergie indisponibles sur ce Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Température CPU",
        monitorShowGPUTemperature: "Température GPU",
        monitorShowBatteryTemperature: "Température batterie",
        monitorShowPeripheralBattery: "Batterie des périphériques",
        peripheralBatteryNoDevices: "Aucun périphérique trouvé",

        updateBannerTitle: "Mise à jour disponible",
        updateBannerAction: "Mettre à jour",
        menuBarSpacingLabel: "Espacement dans la barre",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Compact",
        menuBarHideIconToggle: "Masquer l’icône de l’app quand des métriques sont affichées",
        menuBarHideIconCaption: "L’icône revient d’elle-même quand les métriques quittent la barre et quand il y a quelque chose à signaler (une mise à jour prête ou le micro coupé).",
        menuBarIconSection: "Icône de l’app",
        monitorMemoryPressureDot: "Point de pression",
        systemUptime: "Actif depuis",
        batteryCharge: "Charge",
        powerHealth: "État de la batterie",
        powerCycles: "Cycles",
        speedTestRun: "Test de débit",
        speedTestAgain: "Tester à nouveau",
        speedTestLatency: "Latence",
        speedTestTesting: "Test en cours…",
        speedTestFailed: "Échec du test",

        monitorShowInPanel: "Afficher dans le panneau",
        disclosureExpanded: "Développé",
        disclosureCollapsed: "Réduit",
        panelHideItem: "Masquer du panneau",
        panelShowItem: "Afficher dans le panneau",
        panelHiddenItem: "Masqué",
        monitorItemUptime: "Durée d’activité",
        monitorItemNetSpeed: "Débit en direct",
        monitorItemNetTotals: "Totaux de la session",
        monitorItemNetTest: "Test de débit",
        monitorItemDiskUsage: "Utilisation du disque",
        monitorItemDiskActivity: "Activité en direct",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protection externe",
        monitorItemDiskTools: "Outils",
        monitorOrderSection: "Ordre des sections",
        monitorOrderHint: "Glissez pour réordonner les sections du panneau et utilisez l’œil pour afficher ou masquer chacune.",

        cleaningMenuItem: "Mode nettoyage",
        utilitiesSection: "Utilitaires",
        quickControlsSection: "Contrôles",
        panelCategoryWindows: "Fenêtres",
        panelCategoryInput: "Souris et clavier",
        panelCategoryFiles: "Fichiers",
        windowMaximizeName: "Le bouton vert agrandit la fenêtre",
        windowMaximizeCaption: "Cliquez sur le bouton vert en haut à gauche pour agrandir la fenêtre sur le bureau actuel, sans passer en plein écran.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrer les touches doublées",
        keyDebounceCaption: "Filtre les touches doublées très rapides.",
        keyDebounceActiveNow: "Filtre actif",
        keyDebounceGlobalWindow: "Fenêtre globale",
        keyDebouncePerKeySection: "Touches spécifiques",
        keyDebouncePerKeyCaption: "Les valeurs par touche remplacent la fenêtre globale. Utilisez 0 ms pour ne pas filtrer une touche.",
        keyDebounceKeyLabel: "Touche",
        keyDebounceAddKey: "Ajouter une touche",
        keyDebounceNoOverrides: "Aucune touche spécifique configurée.",
        keyDebounceRemoveKey: "Supprimer la touche",
        cleaningPanelCaption: "Verrouille le clavier pour nettoyer en sécurité.",
        cleaningOverlayTitle: "Clavier verrouillé pour le nettoyage",
        cleaningOverlaySubtitle: "Appuyez 5 fois sur Échap pour déverrouiller",
        cleaningOverlayUnlock: "Déverrouiller",
        cleaningOverlayMouseHint: "Votre souris et votre trackpad fonctionnent toujours",
        cleaningKeepScreenVisibleToggle: "Garder l’écran visible",
        cleaningKeepScreenVisibleCaption: "Affiche un indicateur discret dans un coin de l’écran sans masquer le contenu.",
        cleaningStartNow: "Verrouiller le clavier maintenant",
        cleaningNeedsAxTitle: "Accessibilité requise",
        cleaningNeedsAxBody: "Pour verrouiller le clavier en toute sécurité, \(AppInfo.name) a besoin de l’autorisation Accessibilité. Accordez-la dans les Réglages Système et réessayez.",

        shortcutsPageCaption: "Modifiez ici tous les raccourcis globaux des fonctions installées sur ce Mac. Les raccourcis inactifs restent enregistrés sans se déclencher.",
        shortcutsPageTitle: "Raccourcis clavier",
        settingsSearchPlaceholder: "Rechercher dans les réglages",
        supportIntroLaterButton: "Pas maintenant",
        supportIntroDoneButton: "Terminer",
        updateShowcaseTitle: "Nouveautés de la 3.1.4",
        updateShowcaseMessage: "Découvrez rapidement les principales améliorations de cette mise à jour.",
        updateShowcaseUnavailable: "La vidéo n’a pas pu se charger maintenant. Vous pouvez quand même continuer.",
        updateShowcaseRestart: "Revenir au début",
        showMenuBarIcon: "Afficher l’icône dans la barre des menus",
        showMenuBarIconCaption: "Si l’icône de \(AppInfo.name) disparaît (macOS peut masquer des icônes lorsque la barre des menus manque de place, fréquent sur les Mac avec encoche), rouvrez \(AppInfo.name) depuis Applications ou Spotlight\u{00A0}: cela recrée l’icône et, si elle reste masquée, ouvre cette fenêtre.",
        menuBarIconStillHiddenTitle: "L’icône est toujours masquée",
        menuBarIconStillHiddenBody: "L’icône a été reconstruite, mais macOS ne lui a pas donné de place visible. La barre des menus manque probablement d’espace\u{00A0}: retirez quelques icônes de la barre (ou fermez les apps aux menus longs) et réessayez.",
        menuBarIconManagerHintFormat: "%@ est ouvert et garde peut-être l’icône dans sa section masquée. Cherchez \(AppInfo.name) là-bas, ou réglez %@ pour toujours afficher \(AppInfo.name).",
        shortcutRecording: "Appuyez sur le nouveau raccourci",
        shortcutReset: "Réinitialiser",
        shortcutNone: "Aucun",
        shortcutClear: "Supprimer le raccourci",
        shortcutInvalid: "Utilisez au moins Control, Option ou Command avec une touche.",
        shortcutPressKeys: "Appuyez",
        shortcutEscapeHint: "Esc annule.",
        shortcutDeleteHint: "Delete efface.",
        shortcutNotCaptured: "Rien n’a été capturé. macOS ou une autre app utilise déjà cette combinaison. Essayez-en une autre.",
        shortcutConflictFormat: "Ce raccourci est déjà utilisé par %@.",
        shortcutUnavailable: "macOS a refusé ce raccourci. Choisissez-en un autre.",
        shelfShortcutToggle: "Raccourci Shelf",
        switcherUsageHintFormat: "Maintenez %@ pour naviguer\u{00A0}; relâchez pour activer la fenêtre. Maj ou ← revient en arrière\u{00A0}; W ferme la fenêtre\u{00A0}; Q quitte l’app\u{00A0}; Échap annule.",
        cleanerName: "Nettoyage",
        cleanerIntroTitle: "Nettoyez votre Mac",
        cleanerIntroCaption: "Recherche les restes d’apps désinstallées, les caches, les journaux et la corbeille. Vous vérifiez tout avant et les éléments retirés vont à la corbeille.",
        cleanerScan: "Analyser",
        cleanerScanning: "Analyse…",
        cleanerCleaning: "Nettoyage…",
        cleanerCatLeftovers: "Restes d’apps désinstallées",
        cleanerCatLoginItems: "Éléments de démarrage orphelins",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Journaux",
        cleanerCatDeveloper: "Données de développement",
        cleanerCatTrash: "Corbeille",
        cleanerLeftoversNote: "Trouvés par analyse et non cochés. Vérifiez le chemin avant de cocher.",
        cleanerLoginItemsNote: "L’entrée dans Éléments de connexion disparaît après un redémarrage.",
        cleanerTrashNote: "Vider la corbeille est définitif.",
        cleanerCatDeviceBackups: "Sauvegardes iPhone",
        cleanerDeviceBackupsCaption: "Les anciennes sauvegardes d’iPhone et d’iPad occupent une grande part du stockage que macOS appelle Autre. Ne supprimez que celles devenues inutiles\u{00A0}; une nouvelle est créée au prochain branchement.",
        cleanerNothingFound: "Rien à nettoyer. Votre Mac est en ordre.",
        cleanerIncompleteTitle: "Nettoyage incomplet",
        cleanerFailedNote: "Ces éléments n’ont pas pu être nettoyés. Relancez l’analyse pour vérifier les éléments restants.",
        cleanerDoneNote: "Les éléments sont dans la corbeille et peuvent y être récupérés.",
        cleanerAgain: "Analyser à nouveau",
        cleanerRevealInFinder: "Afficher dans le Finder",
        cleanerPanelCaption: "Restes d’apps, caches et journaux",
        cleanerSafeSection: "Nettoyage sûr",
        cleanerOptionalSection: "Facultatif, vérifiez d’abord",
        cleanerCatOtherCaches: "Autres caches",
        cleanerCachesCaption: "Fichiers temporaires que les apps recréent seules.",
        cleanerLogsCaption: "Anciens journaux de diagnostic.",
        cleanerDeveloperCaption: "Restes de compilations et de simulateurs Xcode.",
        cleanerLoginItemsCaption: "Entrées de démarrage laissées par des apps qui n’existent plus.",
        cleanerLeftoversCaption: "Fichiers laissés par des apps désinstallées.",
        cleanerOtherCachesCaption: "Suppression sûre, rien ne casse. Les apps peuvent ouvrir plus lentement une fois et le contenu téléchargé, comme la musique hors ligne, se retélécharge.",
        cleanerCleanSizeFormat: "Nettoyer %@",
        cleanerScheduleTitle: "Nettoyage automatique",
        cleanerScheduleOff: "Désactivé",
        cleanerScheduleDaily: "Quotidien",
        cleanerScheduleWeekly: "Hebdomadaire",
        cleanerScheduleCaption: "Nettoie seul uniquement la partie sûre à l’heure choisie et envoie tout à la corbeille.",
        cleanerAutoNotificationFormat: "%@ libérés et envoyés à la corbeille.",
        cleanerScheduleNextFormat: "Prochain nettoyage %@.",
        cleanerScheduleNotifyToggle: "Prévenir à la fin",
        cleanerNotifDenied: "Les notifications de \(AppInfo.name) sont désactivées dans le système.",
        cleanerNotifOpenSettings: "Ouvrir les réglages de notifications…",
        launchAtLoginNeedsApplications: "L’app s’exécute depuis un emplacement qui ne permet pas l’ouverture à la connexion. Glissez \(AppInfo.name) dans le dossier Applications, ouvrez l’app depuis ce dossier et réactivez l’option.",
        launchAtLoginNeedsApproval: "L’élément d’ouverture est enregistré, mais il reste désactivé dans les Réglages Système. Ouvrez Réglages Système › Général › Ouverture et extensions, puis activez \(AppInfo.name) sous «\u{00A0}Ouvrir à la session\u{00A0}».",
        ocrRemoveLineBreaksToggle: "Supprimer les sauts de ligne",
        ocrRemoveLineBreaksCaption: "Supprime les sauts de ligne afin que le texte copié soit collé en un seul paragraphe.",
        ocrQRToggle: "Lire les codes QR",
        ocrQRCaption: "Si la zone contient un code QR, son contenu s’affiche pour le copier ou l’ouvrir.",
        ocrQRCopied: "Code QR copié",
        qrResultTitle: "Code QR",
        qrResultCopy: "Copier",
        qrResultOpen: "Ouvrir le lien",
        highlightsTitle: "Nouveautés de cette mise à jour",
        highlightsTitleQuitProtection: "Protection de ⌘Q et ⌘W",
        highlightsTitleRecorderBlur: "Flou de confidentialité vidéo",
        highlightsCaptionQuitProtection: "Évitez de quitter des apps ou fermer des fenêtres par erreur en maintenant la touche, en appuyant deux fois ou avec un modificateur supplémentaire, par app.",
        highlightsCaptionRecorderBlur: "Masquez des données sensibles, mots de passe et détails privés sur n’importe quelle section de votre enregistrement avant de l’exporter.",
        highlightsConfigure: "Configurer",
        highlightsSeeAll: "Voir tous les changements",
        switcherCurrentSpaceOnly: "Afficher uniquement le bureau actuel",
        switcherCurrentSpaceOnlyCaption: "N’affiche dans le sélecteur que les fenêtres du bureau où vous êtes. Choisir une fenêtre ne vous emmène jamais sur un autre bureau.",
        shelfFileMissing: "Le fichier n’existe plus",
        monitorOpenActivityMonitor: "Ouvrir le Moniteur d’activité",
        monitorMemoryMetricLabel: "Mesurer la mémoire comme",
        memoryMetricUsed: "Mémoire utilisée",
        memoryMetricApp: "Mémoire des apps",
        keepAwakeRightClickToggle: "Faire un clic droit sur l’icône de la barre des menus pour basculer «\u{00A0}Garder éveillé\u{00A0}»",
        keepAwakeRightClickToggleCaption: "Remplace le menu contextuel du clic droit.",
        urlCleanerRulesTitle: "Règles de nettoyage",
        urlCleanerRulesCaption: "Un site ajoute ces paramètres à ses propres liens de partage pour savoir d’où vient le lien. Coché, le nom est retiré lors du nettoyage\u{00A0}; décoché, il reste. Les noms que vous ajoutez peuvent être supprimés.",
        urlCleanerRulesCoverageCaption: "La liste couvre les différents chemins de partage d’un site (la page web, l’app, un direct), d’où sa longueur\u{00A0}; un vrai lien n’en porte généralement que deux à quatre.",
        urlCleanerRulesAllSites: "Tous les sites",
        urlCleanerRulesAddSite: "Ajouter un site",
        urlCleanerRulesParameterPlaceholder: "Nom du paramètre",
        urlCleanerRulesMatchCaption: "Saisissez le nom à gauche du = , par exemple utm_source. Un nom qui correspond retire ce seul paramètre du lien et laisse le reste tel quel.",
        urlCleanerRulesAddButton: "Ajouter",
        urlCleanerRemovedFormat: "Retirés %@",
        switcherSearchPin: "Épingler la recherche avec S",
        switcherSearchPinCaption: "S lance une recherche et épingle le sélecteur ouvert\u{00A0}: plus de caractères spéciaux tapés quand le raccourci utilise ⌥, et une recherche commençant par Q ou W ne ferme plus la fenêtre ni ne quitte l’app par erreur.",
        invertVerticalScroll: "Inverser le défilement vertical",
        invertHorizontalScroll: "Inverser le défilement horizontal",
        switcherShowShortcutHints: "Afficher les raccourcis",
        switcherShowShortcutHintsCaption: "Affiche les raccourcis des apps et des fenêtres sous les icônes.",
        uninstallerHomebrewPackageFormat: "%@ sera aussi retiré de Homebrew.",
        shelfEdgeToggle: "Ouvrir près d’un bord de l’écran",
        shelfEdgeCaption: "Faites glisser un fichier vers le bord de l’écran pour entrevoir l’étagère. Déposez-le là, ou reculez et elle se retire.",
        focusFollowsMouseName: "Le focus suit la souris",
        focusFollowsMouseCaption: "Active et place au premier plan la fenêtre sous le pointeur après une courte pause.",
        focusFollowsMouseDelay: "Délai de survol",
        switcherMinimizedPlacementLabel: "Fenêtres réduites",
        switcherMinimizedPlacementNormal: "Ordre normal",
        switcherMinimizedPlacementEnd: "Placer à la fin",
        switcherMinimizedPlacementHidden: "Masquer",
        switcherShowFullscreenWindows: "Afficher les fenêtres plein écran",
        switcherScreenPlacementLabel: "Afficher sur",
        switcherScreenPlacementPointer: "Écran avec le pointeur",
        switcherScreenPlacementMenuBar: "Écran avec la barre des menus",
        switcherScreenPlacementActiveWindow: "Écran avec la fenêtre active",
        switcherScreenPlacementCaption: "Sur quel écran le sélecteur s’ouvre quand plusieurs sont connectés.",
        smoothScrollResponseLabel: "Réactivité",
        mouseAccelerationName: "Désactiver l’accélération de la souris",
        mouseAccelerationCaption: "Supprime l’accélération du pointeur pour les souris connectées. Le réglage précédent est restauré à la désactivation ou à la fermeture de \(AppInfo.name).",
        shelfClearOnClose: "Vider à la fermeture",
        shelfClearOnCloseCaption: "Vide l’étagère uniquement lorsque vous cliquez sur le bouton de fermeture. Le masquage automatique et la réduction conservent les éléments."
    )
}
