// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Deutsch — translated and hand-checked, not machine output.
extension Strings {
    static let de = Strings(
        statusIdleTooltip: "\(AppInfo.name): normaler Ruhezustand",
        statusActiveUntil: "\(AppInfo.name): aktiv bis",
        statusActiveIndefinite: "\(AppInfo.name): dauerhaft aktiv",
        menuEnableAwake: "Wachhalten aktivieren",
        menuDisableAwake: "Wachhalten deaktivieren",
        menuActivateFor: "Aktivieren für…",
        menuSettings: "Einstellungen…",
        menuAbout: "Über \(AppInfo.name)",
        menuQuit: "\(AppInfo.name) beenden",
        menuHide: "\(AppInfo.name) ausblenden",
        menuHideOthers: "Andere ausblenden",
        menuShowAll: "Alle einblenden",
        menuEdit: "Bearbeiten",
        menuUndo: "Widerrufen",
        menuRedo: "Wiederholen",
        actionClear: "Löschen",
        actionRemove: "Entfernen",
        actionBack: "Zurück",
        actionSearch: "Suchen",
        actionMute: "Stummschalten",
        actionUnmute: "Wieder aktivieren",
        actionPlay: "Abspielen",
        actionPause: "Pausieren",
        menuCut: "Ausschneiden",
        menuCopy: "Kopieren",
        menuPaste: "Einsetzen",
        menuSelectAll: "Alles auswählen",
        menuWindow: "Fenster",
        menuMinimize: "Im Dock ablegen",
        menuZoom: "Zoomen",
        menuClose: "Schließen",

        minutes15: "15 Minuten",
        minutes30: "30 Minuten",
        hour1: "1 Stunde",
        hours2: "2 Stunden",
        hours4: "4 Stunden",
        hours8: "8 Stunden",
        indefinitely: "Dauerhaft",
        indefinite: "Unbegrenzt",

        panelSettings: "Einstellungen",
        panelQuit: "Beenden",

        keepAwakeTitle: "Wachhalten",
        keepAwakeEndsIn: "Endet in",
        keepAwakeUntilDisabled: "Aktiv, bis du es ausschaltest",
        keepAwakeNormalRules: "Der Mac folgt seinen normalen Energieregeln",
        keepAwakeOptions: "Optionen",
        keepAwakeMouseJiggle: "Zeiger leicht bewegen",
        keepAwakeMouseJiggleCaption: "Bewegt den Zeiger während einer Sitzung im gewählten Intervall leicht.",
        keepAwakeMouseJiggleInterval: "Intervall",
        keepAwakeActiveIconLabel: "Aktives Symbol",
        keepAwakeActiveIconVorssaint: "\(AppInfo.name)",
        keepAwakeActiveIconCoffee: "Kaffee",
        keepAwakeActiveIconEye: "Auge",
        keepAwakeActiveIconMoon: "Mond",
        keepAwakeActiveIconLight: "Glühbirne",
        keepAwakeIconTintLabel: "Farbe des aktiven Symbols",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Grün",
        keepAwakeIconTintBlue: "Blau",
        keepAwakeIconTintPurple: "Lila",
        keepAwakeIconTintPink: "Pink",
        keepAwakeIconTintNone: "Keine Farbe",
        durationLabel: "Dauer",
        clamshellTitle: "Bei zugeklapptem Mac weiterlaufen",
        clamshellOnCaption: "Ruhezustand komplett deaktiviert. Auf den Akku achten",
        clamshellNeedsSession: "Gilt immer, wenn „Wachhalten“ aktiv ist",
        clamshellReady: "Bereit. Schaltet ohne Passwort um",
        clamshellNeedsPassword: "Fragt einmalig nach dem Administratorpasswort",

        systemSection: "System",
        temperatures: "Temperaturen",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Hardware-Auslastung",
        memorySection: "Speicher",
        memoryPressure: "Speicherdruck",
        memorySwapUsed: "Swap-Nutzung",
        memoryCompressed: "Komprimiert",
        memoryCachedFiles: "Dateien im Cache",
        pressureNormal: "Normal",
        pressureWarning: "Erhöht",
        pressureCritical: "Kritisch",
        monitorUnavailable: "Sensoren auf diesem Mac nicht verfügbar",
        energyAppsTitle: "Hoher Energieverbrauch",
        energyAppsIdle: "Kein hoher Energieverbrauch",

        notifySessionEndedTitle: "Sitzung beendet",
        notifySessionEndedBody: "Die Zeit ist abgelaufen. Der Mac wechselt wieder normal in den Ruhezustand.",
        notifyBatteryTitle: "\(AppInfo.name) deaktiviert",
        notifyBatteryBody: "Niedriger Batteriestand. Der normale Ruhezustand wurde wiederhergestellt, um die Ladung zu schonen.",
        adminPromptClamshellOff: "\(AppInfo.name) benötigt dein Passwort, um den normalen Ruhezustand des Mac wiederherzustellen.",
        adminPromptRecover: "\(AppInfo.name) wurde beendet, während der Ruhezustand des Mac deaktiviert war. Gib das Passwort ein, um den normalen Ruhezustand wiederherzustellen.",
        adminPromptUpdate: "\(AppInfo.name) benötigt dein Passwort, um das Update zu installieren.",
        adminPromptSudoersInstall: "\(AppInfo.name) legt eine eingeschränkte Regel an (nur pmset disablesleep), um den Modus bei geschlossenem Display ohne Passwortabfrage umzuschalten. Nur dieses eine Mal wird das Passwort benötigt.",
        adminPromptSudoersRemove: "\(AppInfo.name) entfernt die passwortfreie Regel für das geschlossene Display.",

        settingsTitle: "\(AppInfo.name)-Einstellungen",
        tabGeneral: "Allgemein",
        tabMouse: "Maus",
        tabDock: "Dock",
        tabWindowBehavior: "Fensterverhalten",
        tabKeyboard: "Tastatur",
        tabTrackpad: "Trackpad",
        tabAdvanced: "Erweitert",
        tabAbout: "Über",
        tabReleaseNotes: "Neues",
        advancedResetSection: "Berechtigungen",
        advancedResetDescription: "Entfernt alle Berechtigungen, die du \(AppInfo.name) erteilt hast (Bedienungshilfen, Bildschirmaufnahme, Festplattenvollzugriff und weitere), das Anmeldeobjekt und die Regel für das geschlossene Display. Praktisch für einen Neustart oder vor dem Deinstallieren. Die App bleibt installiert.",
        advancedClearButton: "Alle Berechtigungen zurücksetzen",
        advancedCleared: "Berechtigungen zurückgesetzt.",
        advancedClearConfirmTitle: "Alle Berechtigungen zurücksetzen?",
        advancedClearConfirmBody: "Funktionen, die Berechtigungen benötigen, arbeiten erst wieder, wenn du sie erneut erteilst. Deine Einstellungen bleiben erhalten.",
        advancedUninstallSection: "Deinstallieren",
        advancedUninstallDescription: "Versucht, die Berechtigungen, das Anmeldeobjekt und die passwortfreie Regel für den Betrieb bei geschlossenem Deckel zu entfernen sowie Einstellungen und lokale App-Daten zu löschen. Nach dem Beenden wird versucht, die App in den Papierkorb zu verschieben. Separat gespeicherte Sicherungen und Exporte werden nicht gelöscht.",
        advancedUninstallButton: "\(AppInfo.name) vollständig deinstallieren",
        advancedUninstallConfirmTitle: "\(AppInfo.name) deinstallieren?",
        advancedUninstallConfirmBody: "\(AppInfo.name) setzt seine Berechtigungen zurück, entfernt seine Einstellungen und wandert in den Papierkorb, dann beendet es sich. Das lässt sich aus der App nicht rückgängig machen, doch sie bleibt im Papierkorb, bis du ihn leerst.",
        advancedUninstallFailedTitle: "Deinstallation gestoppt",
        advancedUninstallFailedBody: "\(AppInfo.name) konnte eine geänderte Systemeinstellung nicht wiederherstellen: Ruhezustand, Lüfterdrehzahl oder Mausbeschleunigung. Es wurde nichts entfernt. Versuche es erneut und erlaube die Kennwortabfrage, falls sie erscheint.",

        launchAtLogin: "Beim Anmelden öffnen",
        languageLabel: "Sprache",
        showCountdown: "Verbleibende Zeit neben dem Symbol anzeigen",
        hotkeyToggle: "Kurzbefehl für „Wachhalten“ aktivieren",
        hotkeyCaption: "Funktioniert in jeder App, ohne zusätzliche Berechtigungen.",

        sessionSection: "Sitzung",
        defaultDurationLabel: "Standarddauer",
        keepAwakeAutoStart: "Beim Öffnen von \(AppInfo.name) wach halten",
        keepAwakeAutoStartCaption: "Startet eine Sitzung mit der Standarddauer.",
        batteryProtectionSection: "Batterieschutz",
        batteryDisableBelow: "Deaktivieren bei Batterie unter",
        batteryNever: "Nie",
        batteryProtectionCaption: "Verhindert, dass eine vergessene Sitzung die Batterie des MacBook entlädt.",
        clamshellSection: "Zugeklappt",
        configuring: "Wird konfiguriert…",
        sudoersFailed: "Modus bei geschlossenem Display konnte nicht aktiviert werden. Erneut versuchen.",
        clamshellExplanation: "„Bei zugeklapptem Mac weiterlaufen“ deaktiviert den Ruhezustand vollständig, solange „Wachhalten“ aktiv ist, und wird automatisch zurückgesetzt, sobald die Sitzung endet oder die App beendet wird. Nutze es am besten am Netzteil.",

        scrollSection: "Scrollen",
        invertMouseScroll: "Mausscrollen umkehren",
        invertMouseScrollCaption: "Kehrt die Richtung des Mausrads um.",
        scrollTrackpadNote: "Das Trackpad bleibt unverändert: Es behält das natürliche Scrollen von macOS bei.",
        scrollActiveNow: "Mausscrollen wird gerade umgekehrt",
        mouseNavigationActiveNow: "Seitentasten gerade aktiv",
        smoothScrollName: "Sanftes Scrollen",
        smoothScrollCaption: "Verwandelt jeden Rastschritt des Mausrads in ein kurzes, sanftes Gleiten. Das Trackpad bleibt unverändert.",
        smoothScrollStepLabel: "Scrollgeschwindigkeit",
        mouseNavigationEnable: "Seitentasten für Zurück und Vor verwenden",
        mouseNavigationCaption: "Wandelt die Maus-Tasten Zurück und Vor in Navigationsbefehle für Finder, Browser und kompatible Apps um.",
        middleClickSection: "Mittelklick",
        middleClickEnable: "Drei-Finger-Klick als Mittelklick",
        middleClickEnableCaption: "Das Trackpad mit drei Fingern zu drücken wirkt wie ein Klick aufs Mausrad: Links im neuen Tab öffnen, Tabs schließen und alles andere, was die mittlere Taste kann.",
        middleClickDragConflict: "Das Ziehen mit drei Fingern von macOS ist aktiviert und nutzt dieselbe Geste. Schalte es in den Systemeinstellungen unter Bedienungshilfen, Zeigersteuerung, Trackpad-Optionen aus, damit der Mittelklick funktioniert.",
        middleClickTapPicker: "Leichtes Tippen klickt ebenfalls",
        middleClickTapOff: "Aus",
        middleClickTapThreeFingers: "3 Finger",
        middleClickTapFourFingers: "4 Finger",
        middleClickTapCaption: "Ein leichtes Tippen mit dieser Fingerzahl, ohne zu drücken, löst ebenfalls den Mittelklick aus. Wischen zählt nie. Ist das Dreifinger-Tippen von macOS mit Nachschlagen belegt, schalte es aus, damit nicht beides zugleich auslöst.",
        quickToolShortcutToggle: "Globaler Kurzbefehl",
        ocrName: "Text vom Bildschirm kopieren",
        ocrCaption: "Wähle einen Bildschirmbereich aus und der erkannte Text wird kopiert, bereit zum Einsetzen.",
        ocrCopied: "Text kopiert",
        ocrNoText: "Kein Text gefunden",
        colorPickerName: "Farbpipette",
        colorPickerCaption: "Greife die Farbe jedes Pixels auf dem Bildschirm ab und kopiere sie im gewünschten Format.",
        colorPickerFormatLabel: "Kopiertes Format",
        colorPickerBareHexToggle: "Ohne das Präfix # kopieren",
        pastePlainName: "Als reinen Text einsetzen",
        pastePlainCaption: "Setzt Kopiertes ohne Farben, Schriften oder Formatierung ein. Das Original bleibt in der Zwischenablage.",
        switcherSection: "App-Umschalter",
        switcherEnable: "\(AppInfo.name)-Umschalter verwenden",
        switcherEnableCaption: "Wechselt zwischen Apps und Fenstern, einschließlich minimierter und mehrerer Fenster derselben App.",
        switcherNoWindows: "Keine geöffneten Fenster",
        appQuitFailedFormat: "Beenden konnte nicht angefordert werden: %@.",
        switcherIconRowMode: "%@ mit großen Symbolen anzeigen",
        switcherIconRowModeCaption: "Zeigt ein Symbol pro App und darüber die Fenstervorschauen dieser App.",
        switcherSimpleMode: "Einfacher App-Umschalter",
        switcherSimpleModeCaption: "Zeigt App-Symbole und Fenstertitel, ohne Vorschauen oder Bildschirmaufnahme durch den Umschalter.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Fenster",
        switcherWindowShortcutCaption: "Öffnet einen Umschalter für die Fenster der vordersten App. Bei geöffnetem App-Umschalter springt er zwischen den Fenstern der ausgewählten App.",
        switcherTakeOverSystemShortcuts: "macOS-⌘Tab und ⌘` ersetzen",
        switcherTakeOverSystemShortcutsCaption: "Deaktiviert die passenden macOS-App- und Fensterkurzbefehle nur, solange \(AppInfo.name)s Umschalter aktiv ist. Alle laufenden Apps bleiben erreichbar.",
        switcherAppearanceDelay: "Einblendverzögerung",
        switcherAppearanceDelayCaption: "Wie lange das Tastenkürzel gehalten werden muss, bevor der Umschalter erscheint.",
        switcherMergeTabs: "Einen Eintrag pro App anzeigen",
        switcherMergeTabsCaption: "Fasst alle Fenster einer App zu einem Eintrag im Umschalter zusammen, statt einen Eintrag pro Fenster.",
        switcherWindowlessApps: "Apps ohne geöffnetes Fenster",
        switcherWindowlessAppsCaption: "Legt fest, welche laufenden Apps ganz ohne Fenster im Umschalter erscheinen.",
        switcherWindowlessAppsOff: "Nicht anzeigen",
        switcherWindowlessAppsFinder: "Nur Finder",
        switcherWindowlessAppsAll: "Alle Apps",
        switcherNoOpenWindow: "Kein geöffnetes Fenster",
        switcherOtherDesktop: "Anderer Schreibtisch",

        cutPasteName: "Ausschneiden & Einsetzen",
        cutPasteEnable: "Dateien im Finder ausschneiden & einsetzen",
        cutPasteEnableCaption: "Verwende ⌘X zum Ausschneiden und ⌘V, um Dateien und Ordner im Finder zu bewegen.",
        cutPasteShowHUD: "Schwebendes Fenster anzeigen",
        cutPasteShowHUDCaption: "Zeigt eine schwebende Anzeige mit den ausgeschnittenen Dateien, während der Finder aktiv ist.",
        cutPasteHowTitle: "So geht’s",
        cutPasteStep1: "Wähle Objekte im Finder aus und drücke ⌘X, um sie auszuschneiden.",
        cutPasteStep2: "Öffne den Zielordner und drücke ⌘V, um sie dorthin zu bewegen.",
        cutPasteTextNote: "In Textfeldern (etwa beim Umbenennen) funktionieren ⌘X und ⌘V weiterhin wie gewohnt.",
        cutPasteActiveNow: "Bereit zum Ausschneiden im Finder",
        cutPasteAutomationNote: "Beim ersten Mal fragt macOS um Erlaubnis, den Finder zu steuern.",
        cutReadyTitle: "Ausgeschnitten",
        cutReadyHint: "im Zielordner zum Bewegen",
        cutCancel: "Ausschneiden abbrechen",
        cutDoneTitle: "Bewegt!",
        cutMovedSingular: "1 Objekt bewegt",
        cutMovedPluralFormat: "%d Objekte bewegt",
        cutSomeFailed: "Einige Objekte konnten nicht bewegt werden",
        cutMovingTitle: "Wird bewegt…",
        cutMovingCountFormat: "%d von %d",

        autoQuitName: "Beim Schließen beenden",
        autoQuitEnable: "App beenden, wenn ihr letztes Fenster schließt",
        autoQuitEnableCaption: "Das Schließen des letzten Fensters einer App beendet sie auch.",
        autoQuitActiveNow: "Jetzt aktiv",
        autoQuitStep1: "Schließe das letzte Fenster einer App (⌘W oder der rote Knopf).",
        autoQuitStep2: "Die App beendet sich von selbst. „Sichern?“-Dialoge erscheinen weiterhin.",
        autoQuitPredictableNote: "Apps, die normalerweise ohne Fenster laufen, werden nie beendet.",
        autoQuitExceptionsTitle: "Ausnahmen",
        autoQuitExceptionsCaption: "Apps in dieser Liste bleiben auch ohne Fenster geöffnet.",
        autoQuitExceptionsEmpty: "Keine Ausnahmen",
        autoQuitAddApp: "App hinzufügen…",

        uninstallerName: "Deinstallationsprogramm",
        uninstallerEnableCaption: "Entfernt eine App samt der Caches, Einstellungen, Protokolle und Rückstände, die sie hinterlässt.",
        uninstallerMenuItem: "Eine App deinstallieren…",
        uninstallerDropTitle: "Ziehe eine App hierher",
        uninstallerDropSubtitle: "oder wähle eine zur Analyse",
        uninstallerChoose: "App auswählen…",
        uninstallerPickerTitle: "App auswählen",
        uninstallerPickerSearch: "Apps suchen",
        uninstallerPickerEmpty: "Keine Apps gefunden",
        uninstallerEmptyNote: "Ohne deine Bestätigung wird nichts entfernt.",
        uninstallerFDANote: "Erteile Festplattenvollzugriff für eine gründlichere Analyse.",
        uninstallerFDAGrant: "Zugriff erteilen…",
        uninstallerFDAHint: "Aktiviere \(AppInfo.name) in der Liste. Fehlt es dort, klicke auf + und wähle \(AppInfo.name) unter „Programme“. Der Zugriff gilt erst, nachdem du die App erneut öffnest.",
        uninstallerFDARelaunch: "Jetzt neu öffnen",
        uninstallerScanning: "Dateien werden analysiert…",
        uninstallerRemoving: "Wird in den Papierkorb bewegt…",
        uninstallerFoundTitle: "gefunden",
        uninstallerSelectedFormat: "%d von %d ausgewählt",
        uninstallerRemove: "In den Papierkorb legen",
        uninstallerCancel: "Abbrechen",
        uninstallerDoneTitle: "Fertig!",
        uninstallerFreedFormat: "Entfernte Daten: %@",
        uninstallerSomeFailed: "Einige Objekte konnten nicht in den Papierkorb bewegt werden.",
        uninstallerConfirmationExpired: "Diese Bestätigung ist nicht mehr gültig. Prüfe die aktuellen Einträge und bestätige erneut.",
        uninstallerFailedNeedsFDA: "Daten von Apps in der Sandbox lassen sich nur mit Festplattenvollzugriff bewegen. Das Administratorpasswort ersetzt diese Berechtigung nicht.",
        uninstallerFailedMoreFormat: "und %d weitere",
        uninstallerAnother: "Weitere deinstallieren",
        uninstallerCatApp: "Programm",
        uninstallerCatSupport: "Unterstützung",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Einstellungen",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Protokolle",
        uninstallerCatState: "Gesicherter Zustand",
        uninstallerCatOther: "Sonstiges",

        urlCleanerName: "URL bereinigen",
        urlCleanerEnable: "URLs beim Kopieren automatisch bereinigen",
        urlCleanerEnableCaption: "Entfernt Tracking-Parameter aus einem Link, sobald er in der Zwischenablage landet.",
        urlCleanerActiveNow: "Jetzt aktiv",
        urlCleanerManualTitle: "Jetzt bereinigen",
        urlCleanerInputPlaceholder: "URL einfügen",
        urlCleanerOutputPlaceholder: "Die bereinigte URL erscheint hier",
        urlCleanerCleanButton: "Bereinigen",
        urlCleanerPasteButton: "Einfügen",
        urlCleanerCopyButton: "Kopieren",
        urlCleanerClearButton: "Feld leeren",
        urlCleanerNoURL: "Füge eine gültige URL ein.",
        urlCleanerNoChange: "Nichts zu bereinigen.",
        urlCleanerCleaned: "URL bereinigt.",
        urlCleanerCopied: "Kopiert.",
        urlCleanerLocalNote: "Lokal. Kein Netzwerk.",

        homebrewName: "Homebrew",
        homebrewMissingTitle: "Homebrew nicht gefunden",
        homebrewMissingBody: "Homebrew ist nicht installiert. Danach erscheinen hier die Pakete, die es verwaltet.",
        homebrewRequested: "Von dir installiert",
        homebrewMasApps: "App Store",
        homebrewCopyName: "Namen kopieren",
        homebrewTrustTitle: "Tap noch nicht vertraut",
        homebrewTrustCaption: "Homebrew fragt jetzt nach deiner Bestätigung, bevor es Taps von Dritten verwendet. Vertraue %@, um fortzufahren.",
        homebrewTrustButton: "Vertrauen und fortfahren",
        homebrewNoPackages: "Keine Pakete gefunden",
        homebrewUninstall: "Deinstallieren",
        homebrewUpgrade: "Aktualisieren",
        homebrewPinnedVersion: "Version fixiert",
        homebrewAllPackages: "Pakete",
        homebrewOpenTerminal: "Terminal öffnen",
        homebrewCancelOperation: "Abbrechen",
        homebrewClearLog: "Protokoll leeren",
        homebrewHomepage: "Website öffnen",
        homebrewUpdateAvailableBadge: "Update verfügbar",
        homebrewConfirmUninstallTitle: "Mit Homebrew deinstallieren?",
        homebrewConfirmUninstallBodyFormat: "Homebrew deinstalliert %@. Konfigurationsdateien können im System bleiben.",
        homebrewConfirmUpgradeTitle: "Mit Homebrew aktualisieren?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew lädt die neueste Version von %@ herunter und wendet sie an. Abhängigkeiten können ebenfalls aktualisiert werden.",
        homebrewTerminalFallback: "Diese Aktion benötigt Terminal, um nach dem Administratorpasswort zu fragen. \(AppInfo.name) erfasst keine Passwörter.",
        homebrewLoading: "Laden…",
        homebrewOperationUninstallFormat: "%@ wird deinstalliert",
        homebrewOperationUpgradeFormat: "%@ wird aktualisiert",
        homebrewOperationUpdateHomebrew: "Homebrew wird aktualisiert",
        homebrewOperationUninstalledFormat: "%@ deinstalliert.",
        homebrewOperationUpgradedFormat: "%@ aktualisiert.",
        homebrewOperationUpdatedHomebrew: "Homebrew aktualisiert.",
        homebrewOperationFailedFormat: "%@ konnte nicht abgeschlossen werden.",
        homebrewOperationCancelled: "Aktion abgebrochen.",
        homebrewOperationPreparing: "Vorbereiten…",
        homebrewOperationDownloading: "Dateien werden geladen…",
        homebrewOperationUninstalling: "Dateien werden entfernt…",
        homebrewOperationUpgrading: "Dateien werden aktualisiert…",
        homebrewOperationFinalizing: "Abschließen…",
        homebrewOperationRefreshing: "Liste wird aktualisiert…",
        homebrewOperationTerminal: "Im Terminal fortfahren.",
        homebrewOperationElapsedFormat: "%@ vergangen",
        homebrewOperationShowDetails: "Details anzeigen",
        homebrewOperationHideDetails: "Details ausblenden",
        homebrewOperationTechnicalLog: "Technische Details",
        homebrewOperationProgressUnknown: "Homebrew hat noch keinen Prozentsatz gemeldet.",

        mediaName: "Medien",
        mediaEnableCaption: "Komprimiere Videos, konvertiere und bearbeite Bilder, erstelle GIFs und extrahiere Text lokal.",
        mediaLocalNote: "Lokal. Kein Netzwerk.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Bild",
        mediaToolText: "Text",
        mediaSelectFile: "Datei wählen",
        mediaDropHint: "Ziehe eine Datei hierher oder klicke zum Auswählen.",
        mediaOutput: "Ausgabe",
        mediaOutputAutomatic: "Automatisch",
        mediaChooseOutput: "Ziel",
        mediaStartVideo: "Video komprimieren",
        mediaStartGIF: "GIF erstellen",
        mediaStartImage: "Bild bearbeiten",
        mediaStartConvertPDF: "In PDF umwandeln",
        mediaStartText: "Text extrahieren",
        mediaCancel: "Abbrechen",
        mediaStartTime: "Start",
        mediaEndTime: "Ende",
        mediaQuality: "Komprimierung",
        mediaCompressionLow: "Niedrig",
        mediaCompressionMedium: "Mittel",
        mediaCompressionHigh: "Hoch",
        mediaMaxSize: "Größe",
        mediaSizingResolution: "Auflösung",
        mediaSizingFileSize: "Dateigröße",
        mediaTargetSize: "Zielgröße",
        mediaTargetSizeHint: "Die Auflösung passt sich an, um unter der Grenze zu bleiben.",
        mediaErrorTargetTooSmall: "Zielgröße zu klein für diesen Clip. Kürzen Sie ihn oder erhöhen Sie die Grenze.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Breite",
        mediaFPS: "FPS",
        mediaFormat: "Format",
        mediaStripMetadata: "Metadaten entfernen",
        mediaLoopGIF: "GIF wiederholen",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Genau",
        mediaOCRFast: "Schnell",
        mediaRunning: "Verarbeitung",
        mediaCompleted: "Fertig",
        mediaCancelled: "Abgebrochen.",
        mediaOpenInFinder: "Anzeigen",
        mediaCopyText: "Text kopieren",
        mediaRunAgain: "Erneut ausführen",
        mediaEmptyText: "Kein Text gefunden.",
        mediaResultSavedFormat: "Gespeichert als %@",
        mediaResultSizeFormat: "%@ zu %@",
        mediaResultGrewCaption: "Die umgewandelte Datei ist größer als das Original.",
        mediaErrorNoFile: "Wähle zuerst eine Datei.",
        mediaErrorNoVideo: "Diese Datei hat keine Videospur.",
        mediaErrorSameOutput: "Wähle ein Ziel, das nicht die Originaldatei ist.",
        mediaErrorUnsupported: "Format wird von macOS nicht unterstützt.",

        shelfName: "Ablage",
        shelfEnable: "Temporäre Ablage zum Ziehen von Dateien",
        shelfEnableCaption: "Ein schwebender Ort, um Dateien, Bilder und Text zu sammeln und später überallhin zu ziehen.",
        shelfHowTitle: "So geht’s",
        shelfStep1: "Öffne sie mit dem Kurzbefehl oder indem du die Maus während des Ziehens schüttelst.",
        shelfStep2: "Lege Dateien, Bilder, Links oder Text darauf ab, um sie zu verwahren.",
        shelfStep3: "Ziehe jedes Objekt wieder in eine beliebige App, wenn du es brauchst.",
        shelfShakeToggle: "Durch Schütteln der Maus beim Ziehen öffnen",
        shelfShakeCaption: "Schüttle den Zeiger schnell, während du ein Objekt hältst, um die Ablage beim Cursor erscheinen zu lassen.",
        shelfDropZoneToggle: "Gezogene Dateien in der Menüleiste behalten",
        shelfDropZoneCaption: "Während du eine Datei ziehst, erscheint die Ablage unter dem Menüleistensymbol. Was du ablegst, bleibt gleich dort, in einer Taste, die du mit einem Klick ein- und ausklappst und die verschwindet, sobald die Ablage leer ist.",
        shelfCollapse: "Einklappen",
        shelfBehaviorTitle: "Nach der Verwendung",
        shelfCloseAfterDrop: "Nach dem Ablegen in einer anderen App schließen",
        shelfCloseAfterDropCaption: "Schließt die Ablage, sobald das Ziel die Objekte annimmt. Die Stecknadel im Panel hält sie offen.",
        shelfRemoveAfterDrop: "Objekte nach dem Ablegen entfernen",
        shelfRemoveAfterDropCaption: "Von einer anderen App angenommene Objekte verlassen die Ablage. Ausschalten, um eine Kopie zu behalten.",
        shelfExclusionsTitle: "Automatische Ausnahmen",
        shelfExclusionsEmpty: "Keine Apps hinzugefügt.",
        shelfExclusionsCaption: "Schütteln und die Menüleisten-Ablage bleiben bei Ziehvorgängen aus diesen Apps aus. Kurzbefehl und Jetzt öffnen funktionieren weiter.",
        shelfPin: "Offen halten",
        shelfUnpin: "Schließen nach Verwendung erlauben",
        shelfHotkeyLabel: "Kurzbefehl",
        shelfOpenNow: "Jetzt öffnen",
        shelfNoPermission: "Benötigt keine Berechtigungen.",
        shelfMenuItem: "Ablage öffnen",
        shelfTitle: "Ablage",
        shelfEmpty: "Ziehe Objekte hierher",
        shelfClearAll: "Alle entfernen",
        shelfRemoveSelected: "Ausgewählte entfernen",
        shelfSelectedFormat: "%d ausgewählt",
        shelfHint: "Klicken zum Auswählen. Zum Verwenden ziehen oder für weitere Aktionen rechtsklicken.",
        shelfItemImage: "Bild",
        shelfTooltipItemsFormat: "%d Elemente",
        shelfTooltipItemsFew: "%d Elemente",
        shelfTooltipImageSingular: "%d Bild",
        shelfTooltipImageFew: "%d Bilder",
        shelfTooltipImagePlural: "%d Bilder",
        shelfTooltipFileSingular: "%d Datei",
        shelfTooltipFileFew: "%d Dateien",
        shelfTooltipFilePlural: "%d Dateien",
        shelfTooltipNoteSingular: "%d Notiz",
        shelfTooltipNoteFew: "%d Notizen",
        shelfTooltipNotePlural: "%d Notizen",
        shelfTooltipLinkSingular: "%d Link",
        shelfTooltipLinkFew: "%d Links",
        shelfTooltipLinkPlural: "%d Links",
        shelfActionOpen: "Öffnen",
        shelfActionOpenWith: "Öffnen mit",
        shelfActionShare: "Teilen",

        breakdownMeasuring: "Wird gemessen…",

        preciseVolumeRollerEnable: "Feinere Lautstärkeschritte verwenden",
        preciseVolumeRollerCaption: "Macht aus Lautstärkerädern und -tasten kleinere Systemschritte.",
        preciseVolumeRollerTapFailed: "Lautstärketasten konnten nicht überwacht werden.",

        updatesSection: "Updates",
        autoCheckToggle: "Automatisch nach Updates suchen",
        betaBadgeLabel: "Beta",
        checkNowButton: "Jetzt suchen",
        updateChecking: "Wird gesucht…",
        updateUpToDate: "Du verwendest die neueste Version.",
        updateAvailablePrefix: "Update verfügbar:",
        updateInstallButton: "Laden und installieren",
        updateDownloading: "Update wird geladen…",
        updateInstalling: "Wird installiert und neu gestartet…",
        updateFailedPrefix: "Suche fehlgeschlagen:",
        updateLastChecked: "Zuletzt gesucht:",
        updateNotifyTitle: "\(AppInfo.name)-Update",
        updateInstallFailedBody: "Das Update wurde geladen, konnte aber nicht angewendet werden. Lade die neueste Version von der GitHub-Releases-Seite und ziehe die App über die aktuelle.",
        updateNeedsApplicationsTitle: "Bewege \(AppInfo.name) in den Ordner „Programme“",
        updateNeedsApplicationsBody: "Die App läuft an einem Ort, der nicht aktualisiert werden kann, etwa im Disk-Image oder an einem temporären Systemort. Ziehe \(AppInfo.name) in den Ordner „Programme“, öffne es von dort und versuche es erneut.",
        menuCheckUpdates: "Nach Updates suchen…",

        permissionRequired: "Berechtigung erforderlich",
        permissionAccessibility: "Bedienungshilfen",
        permissionScreenRecording: "Bildschirmaufnahme",
        permissionGranted: "Erteilt",
        permissionMissing: "Nicht erteilt",
        permissionOpenSettings: "Systemeinstellungen öffnen…",
        permissionRequest: "Zugriff erlauben",
        permissionRestartNote: "macOS bittet nach dem Erteilen möglicherweise darum, die App erneut zu öffnen.",

        aboutDescription: "Eine Werkzeugzentrale für deinen Mac.\nEnergie, Systemüberwachung, Scrollen und ein Fensterumschalter, direkt in der Menüleiste.",
        versionPrefix: "Version",
        reviewIntro: "Einführung erneut ansehen",
        reviewHighlights: "Neuerungen ansehen",
        viewOnGitHub: "Auf GitHub ansehen",

        obContinue: "Fortfahren",
        obBack: "Zurück",
        obStart: "\(AppInfo.name) öffnen",
        obStepWelcomeTitle: "Willkommen bei \(AppInfo.name)",
        obStepWelcomeBody: "Ein dezentes Menüleisten-Werkzeug, das den macOS-Alltag praktischer macht.",
        obWelcomeBullet1Title: "Energie unter Kontrolle",
        obWelcomeBullet1Body: "Halte den Mac so lange wach, wie du möchtest, sogar wenn der Mac zugeklappt ist.",
        obWelcomeBullet2Title: "Klarer Blick aufs System",
        obWelcomeBullet2Body: "Temperaturen, CPU- und GPU-Auslastung und Speicherauslastung in Echtzeit.",
        obWelcomeBullet3Title: "Maus und Fenster nach deinem Geschmack",
        obWelcomeBullet3Body: "Umgekehrtes Mausscrollen und ein Fensterumschalter mit Vorschaubildern.",
        obLanguageLabel: "Sprache",
        obStepDoneTitle: "Alles bereit!",
        obStepDoneBody: "\(AppInfo.name) kümmert sich bereits um deinen Mac.",
        obDoneHint: "Suche das Oktopus-Symbol in der Menüleiste oben rechts auf dem Bildschirm.",
        obWhatsNewTitle: "Neu in dieser Version",
        obWhatsNewFallback: "Dieses Update enthält die neuesten Korrekturen und Verbesserungen.",
        obPurposeTitle: "Was führt dich hierher?",
        obPurposeBody: "Wähle einzelne Funktionen zum Aktivieren. Deine bisherigen Optionen bleiben erhalten.",
        obPurposeSkip: "Du kannst Funktionen später in den Einstellungen ändern.",

        tabMonitor: "Überwachung",
        tabMenuBarIcon: "Menüleistensymbol",
        tabMenuBarPanel: "Menüleisten-Panel",
        monitorMenuBarSection: "In der Menüleiste",
        monitorMenuBarCaption: "Wähle, was neben dem Symbol in der Menüleiste erscheint.",
        monitorCombineTemperatures: "Auslastung und Temperatur kombinieren",
        monitorCombineTemperaturesCaption: "Wenn Auslastung und Temperatur desselben Elements aktiv sind, erscheinen sie in einem Block.",
        monitorSeparateMenuBarMetrics: "Messwerte in eigene Elemente trennen",
        monitorSeparateMenuBarMetricsCaption: "Trennt aktive Blöcke in der Menüleiste und hält Auslastung und Temperatur zusammen, wenn Kombinieren aktiv ist.",
        monitorNetworkUploadFirst: "Upload über Download",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Speicher",
        monitorShowNetwork: "Netzwerk",
        monitorShowPowerLabel: "Energie",
        monitorIntervalLabel: "Aktualisieren alle",
        monitorInterval1: "1 Sekunde",
        monitorInterval2: "2 Sekunden",
        monitorInterval5: "5 Sekunden",
        monitorPanelSection: "Im Panel",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Es können noch Fehler auftreten.",

        networkSection: "Netzwerk",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "Diese Sitzung",
        networkMeasuring: "Wird gemessen…",
        networkApps: "Apps mit Netzwerkverkehr",
        networkAppsIdle: "Keine App nutzt gerade das Netzwerk",

        diskSection: "Festplatten",
        diskUsed: "belegt",
        diskAvailable: "verfügbar",
        diskPurgeable: "löschbar",
        diskInternal: "Intern",
        diskExternal: "Extern",
        diskSelect: "Festplatte wählen",
        diskRead: "Lesen",
        diskWrite: "Schreiben",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART für dieses Laufwerk nicht verfügbar",
        diskTotalRead: "Insgesamt gelesen",
        diskTotalWritten: "Insgesamt geschrieben",
        diskTemperature: "Temperatur",
        diskHealth: "Gesundheit",
        diskPowerCycles: "Einschaltzyklen",
        diskPowerOnHours: "Betriebsstunden",
        diskEject: "Auswerfen",
        diskEjectAll: "Alle auswerfen",
        diskEjecting: "Wird ausgeworfen…",
        diskReadyToRemove: "Bereit zum Entfernen",
        diskEjectFailed: "Auswerfen fehlgeschlagen",
        diskProtectionCaption: "Vor dem Abziehen auswerfen.",
        diskNoExternal: "Kein externes Laufwerk zum Auswerfen bereit.",
        diskOpenInFinder: "Öffnen",
        diskStorageSettings: "Speicher",
        diskNoDisks: "Keine eingebundenen Laufwerke gefunden.",

        powerSection: "Energie",
        powerSystem: "System",
        powerAdapter: "Netzteil",
        powerBattery: "Batterie",
        powerCharging: "Wird geladen",
        powerOnBattery: "Im Batteriebetrieb",
        powerPluggedIn: "Am Netzteil",
        powerUnavailable: "Energiedaten auf diesem Mac nicht verfügbar",
        powerAdapterMaxFormat: "max. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU-Temperatur",
        monitorShowGPUTemperature: "GPU-Temperatur",
        monitorShowBatteryTemperature: "Batterietemperatur",
        monitorShowPeripheralBattery: "Peripheriebatterie",
        peripheralBatteryNoDevices: "Keine Geräte gefunden",

        updateBannerTitle: "Update verfügbar",
        updateBannerAction: "Aktualisieren",
        menuBarSpacingLabel: "Abstand in der Menüleiste",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Kompakt",
        menuBarHideIconToggle: "App-Symbol ausblenden, solange Messwerte angezeigt werden",
        menuBarHideIconCaption: "Das Symbol kehrt von selbst zurück, wenn die Messwerte die Leiste verlassen und wenn es etwas zu melden gibt (ein Update bereit oder das Mikrofon stumm).",
        monitorMemoryPressureDot: "Speicherdruckpunkt",
        systemUptime: "Aktiv seit",
        batteryCharge: "Ladung",
        powerHealth: "Batteriezustand",
        powerCycles: "Zyklen",
        speedTestRun: "Geschwindigkeitstest",
        speedTestAgain: "Erneut testen",
        speedTestLatency: "Latenz",
        speedTestTesting: "Wird getestet…",
        speedTestFailed: "Test fehlgeschlagen",

        monitorShowInPanel: "Im Panel anzeigen",
        disclosureExpanded: "Ausgeklappt",
        disclosureCollapsed: "Eingeklappt",
        panelHideItem: "Im Panel ausblenden",
        panelShowItem: "Im Panel anzeigen",
        panelHiddenItem: "Ausgeblendet",
        monitorItemUptime: "Betriebszeit",
        monitorItemNetSpeed: "Live-Geschwindigkeit",
        monitorItemNetTotals: "Sitzungssummen",
        monitorItemNetTest: "Geschwindigkeitstest",
        monitorItemDiskUsage: "Festplattennutzung",
        monitorItemDiskActivity: "Live-Aktivität",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Externer Schutz",
        monitorItemDiskTools: "Werkzeuge",
        monitorPanelConfigHint: "Öffne einen Block, um zu wählen, was er anzeigt.",
        monitorOrderSection: "Reihenfolge der Bereiche",
        monitorOrderHint: "Ziehen, um die Panel-Bereiche neu anzuordnen, und mit dem Auge jeden ein- oder ausblenden.",

        cleaningMenuItem: "Reinigungsmodus",
        utilitiesSection: "Dienstprogramme",
        quickControlsSection: "Steuerung",
        panelCategoryWindows: "Fenster",
        panelCategoryInput: "Maus und Tastatur",
        panelCategoryFiles: "Dateien",
        windowMaximizeName: "Grüne Taste maximiert Fenster",
        windowMaximizeCaption: "Ein Klick auf die grüne Taste oben links vergrößert das Fenster auf dem aktuellen Schreibtisch, ohne den Vollbildmodus zu öffnen.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Doppelte Tasten filtern",
        keyDebounceCaption: "Filtert sehr schnelle doppelte Tastendrücke.",
        keyDebounceActiveNow: "Filter aktiv",
        keyDebounceGlobalWindow: "Globales Fenster",
        keyDebouncePerKeySection: "Bestimmte Tasten",
        keyDebouncePerKeyCaption: "Werte pro Taste ersetzen das globale Fenster. 0 ms filtert diese Taste nicht.",
        keyDebounceKeyLabel: "Taste",
        keyDebounceAddKey: "Taste hinzufügen",
        keyDebounceNoOverrides: "Keine bestimmten Tasten konfiguriert.",
        keyDebounceRemoveKey: "Taste entfernen",
        cleaningPanelCaption: "Sperrt die Tastatur, damit du sicher reinigen kannst.",
        cleaningOverlayTitle: "Tastatur zum Reinigen gesperrt",
        cleaningOverlaySubtitle: "Esc 5-mal drücken zum Entsperren",
        cleaningOverlayUnlock: "Entsperren",
        cleaningOverlayMouseHint: "Maus und Trackpad funktionieren weiterhin",
        cleaningKeepScreenVisibleToggle: "Bildschirm sichtbar lassen",
        cleaningKeepScreenVisibleCaption: "Zeigt einen dezenten Hinweis in der Bildschirmecke an, anstatt Inhalte abzudunkeln.",
        cleaningStartNow: "Tastatur jetzt sperren",
        cleaningNeedsAxTitle: "Bedienungshilfen erforderlich",
        cleaningNeedsAxBody: "Um die Tastatur sicher zu sperren, benötigt \(AppInfo.name) die Berechtigung für Bedienungshilfen. Erteile sie in den Systemeinstellungen und versuche es erneut.",

        shortcutsPageCaption: "Bearbeite hier alle globalen Kurzbefehle der auf diesem Mac installierten Funktionen. Inaktive Kurzbefehle bleiben gespeichert, werden aber nicht ausgeführt.",
        shortcutsPageTitle: "Tastaturkurzbefehle",
        settingsSearchPlaceholder: "Einstellungen durchsuchen",
        supportIntroLaterButton: "Jetzt nicht",
        supportIntroDoneButton: "Fertig",
        updateShowcaseTitle: "Neues in 3.1.4",
        updateShowcaseMessage: "Sieh dir kurz die wichtigsten Verbesserungen in diesem Update an.",
        updateShowcaseUnavailable: "Das Video konnte gerade nicht geladen werden. Du kannst trotzdem fortfahren.",
        updateShowcaseRestart: "Zum Anfang",
        showMenuBarIcon: "Menüleistensymbol anzeigen",
        showMenuBarIconCaption: "Falls das Symbol von \(AppInfo.name) verschwindet (macOS kann Menüleistensymbole ausblenden, wenn der Platz in der Leiste knapp wird, häufig bei Macs mit Notch), öffne \(AppInfo.name) erneut über „Programme“ oder Spotlight: Das stellt das Symbol wieder her und öffnet, falls es weiterhin ausgeblendet ist, dieses Fenster.",
        menuBarIconStillHiddenTitle: "Das Symbol ist weiterhin verborgen",
        menuBarIconStillHiddenBody: "Das Symbol wurde neu aufgebaut, aber macOS hat ihm keinen sichtbaren Platz gegeben. In der Menüleiste ist vermutlich kein Platz mehr: Entferne einige Menüleisten-Symbole (oder schließe Apps mit langen Menüs) und versuche es erneut.",
        menuBarIconManagerHintFormat: "%@ läuft und hält das Symbol womöglich in seinem verborgenen Bereich. Suche \(AppInfo.name) dort, oder stelle %@ so ein, dass \(AppInfo.name) immer angezeigt wird.",
        shortcutRecording: "Neuen Kurzbefehl drücken",
        shortcutReset: "Zurücksetzen",
        shortcutNone: "Keiner",
        shortcutClear: "Kurzbefehl entfernen",
        shortcutInvalid: "Verwende mindestens Control, Option oder Command mit einer Taste.",
        shortcutPressKeys: "Drücken",
        shortcutEscapeHint: "Esc bricht ab.",
        shortcutDeleteHint: "Delete entfernt.",
        shortcutNotCaptured: "Es wurde nichts erfasst. macOS oder eine andere App belegt diese Kombination bereits. Wähle eine andere.",
        shortcutConflictFormat: "Dieser Kurzbefehl wird bereits von %@ verwendet.",
        shortcutUnavailable: "macOS hat diesen Kurzbefehl abgelehnt. Wähle einen anderen.",
        shelfShortcutToggle: "Shelf-Kurzbefehl",
        switcherUsageHintFormat: "Halte %@ zum Navigieren; loslassen, um das Fenster zu aktivieren. Umschalt oder ← geht zurück; W schließt das Fenster; Q beendet die App; Esc bricht ab.",
        cleanerName: "Aufräumen",
        cleanerIntroTitle: "Räume den Mac auf",
        cleanerIntroCaption: "Sucht Reste deinstallierter Apps, Caches, Protokolle und den Papierkorb. Du prüfst alles vorher und Entferntes landet im Papierkorb.",
        cleanerScan: "Prüfen",
        cleanerScanning: "Prüfe…",
        cleanerCleaning: "Räume auf…",
        cleanerCatLeftovers: "Reste deinstallierter Apps",
        cleanerCatLoginItems: "Verwaiste Anmeldeobjekte",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Protokolle",
        cleanerCatDeveloper: "Entwicklerdaten",
        cleanerCatTrash: "Papierkorb",
        cleanerLeftoversNote: "Per Analyse gefunden und nicht angehakt. Prüfe den Pfad vor dem Anhaken.",
        cleanerLoginItemsNote: "Der Eintrag unter Anmeldeobjekte verschwindet nach einem Neustart.",
        cleanerTrashNote: "Das Leeren des Papierkorbs ist endgültig.",
        cleanerCatDeviceBackups: "iPhone-Backups",
        cleanerDeviceBackupsCaption: "Alte iPhone- und iPad-Backups belegen einen großen Teil des Speichers, den macOS Andere nennt. Entferne nur die, die du nicht mehr brauchst; beim nächsten Anschließen entsteht ein neues.",
        cleanerNothingFound: "Nichts aufzuräumen. Dein Mac ist in Ordnung.",
        cleanerIncompleteTitle: "Bereinigung unvollständig",
        cleanerFailedNote: "Diese Objekte konnten nicht bereinigt werden. Erneut scannen, um die verbleibenden Objekte zu prüfen.",
        cleanerDoneNote: "Die Objekte liegen im Papierkorb und können von dort zurückgeholt werden.",
        cleanerAgain: "Erneut prüfen",
        cleanerRevealInFinder: "Im Finder zeigen",
        cleanerPanelCaption: "App-Reste, Caches und Protokolle",
        cleanerSafeSection: "Sichere Reinigung",
        cleanerOptionalSection: "Optional, vorher prüfen",
        cleanerCatOtherCaches: "Weitere Caches",
        cleanerCachesCaption: "Temporäre Dateien, die Apps von selbst neu anlegen.",
        cleanerLogsCaption: "Alte Diagnoseprotokolle.",
        cleanerDeveloperCaption: "Build- und Simulator-Reste von Xcode.",
        cleanerLoginItemsCaption: "Anmeldeeinträge von Apps, die es nicht mehr gibt.",
        cleanerLeftoversCaption: "Dateien von Apps, die du deinstalliert hast.",
        cleanerOtherCachesCaption: "Sicher zu löschen, nichts geht kaputt. Apps starten einmalig langsamer und Heruntergeladenes, etwa Offline-Musik, lädt erneut.",
        cleanerCleanSizeFormat: "%@ aufräumen",
        cleanerScheduleTitle: "Automatisches Aufräumen",
        cleanerScheduleOff: "Aus",
        cleanerScheduleDaily: "Täglich",
        cleanerScheduleWeekly: "Wöchentlich",
        cleanerScheduleCaption: "Räumt zur gewählten Zeit von selbst nur den sicheren Teil auf und legt alles in den Papierkorb.",
        cleanerAutoNotificationFormat: "%@ freigegeben und in den Papierkorb gelegt.",
        cleanerScheduleNextFormat: "Nächstes Aufräumen %@.",
        cleanerScheduleNotifyToggle: "Nach Abschluss benachrichtigen",
        cleanerNotifDenied: "Mitteilungen von \(AppInfo.name) sind im System deaktiviert.",
        cleanerNotifOpenSettings: "Mitteilungseinstellungen öffnen…",
        launchAtLoginNeedsApplications: "Die App läuft von einem Ort, der das Öffnen bei der Anmeldung nicht erlaubt. Ziehe \(AppInfo.name) in den Ordner Programme, öffne die App von dort und schalte die Option wieder ein.",
        launchAtLoginNeedsApproval: "Das Anmeldeobjekt ist registriert, in den Systemeinstellungen aber weiterhin aus. Öffne Systemeinstellungen › Allgemein › Anmeldeobjekte & Erweiterungen und schalte \(AppInfo.name) unter „Bei der Anmeldung öffnen“ ein.",
        ocrRemoveLineBreaksToggle: "Zeilenumbrüche entfernen",
        ocrRemoveLineBreaksCaption: "Entfernt Zeilenumbrüche, damit kopierter Text als ein Absatz eingefügt wird.",
        ocrQRToggle: "QR-Codes lesen",
        ocrQRCaption: "Enthält der Bereich einen QR-Code, wird sein Inhalt zum Kopieren oder Öffnen gezeigt.",
        ocrQRCopied: "QR-Code kopiert",
        qrResultTitle: "QR-Code",
        qrResultCopy: "Kopieren",
        qrResultOpen: "Link öffnen",
        highlightsTitle: "Neu in diesem Update",
        highlightsTitleQuitProtection: "Schutz für ⌘Q und ⌘W",
        highlightsTitleRecorderBlur: "Weichzeichner für Aufnahmen",
        highlightsCaptionQuitProtection: "Verhindern Sie versehentliches Schließen von Apps oder Fenstern durch Gedrückthalten, Doppeltippen oder eine Zusatztaste, anpassbar pro App.",
        highlightsCaptionRecorderBlur: "Verbergen Sie vertrauliche Daten, Passwörter und private Details in beliebigen Abschnitten Ihrer Videoaufnahme vor dem Exportieren.",
        highlightsConfigure: "Einrichten",
        highlightsSeeAll: "Alle Änderungen ansehen",
        switcherCurrentSpaceOnly: "Nur den aktuellen Schreibtisch anzeigen",
        switcherCurrentSpaceOnlyCaption: "Zeigt im Umschalter nur Fenster des Schreibtischs, auf dem du gerade bist. Die Auswahl eines Fensters wechselt nie zu einem anderen Schreibtisch.",
        shelfFileMissing: "Die Datei existiert nicht mehr",
        monitorOpenActivityMonitor: "Aktivitätsanzeige öffnen",
        monitorMemoryMetricLabel: "Speicher messen als",
        memoryMetricUsed: "Genutzter Speicher",
        memoryMetricApp: "App-Speicher",
        keepAwakeRightClickToggle: "Menüleistensymbol rechtsklicken, um Wachhalten umzuschalten",
        keepAwakeRightClickToggleCaption: "Ersetzt das Kontextmenü beim Rechtsklick.",
        urlCleanerRulesTitle: "Bereinigungsregeln",
        urlCleanerRulesCaption: "Eine Website hängt diese Parameter an ihre eigenen Teilen-Links, um zu verfolgen, woher ein Link kam. Mit Haken wird der Name beim Bereinigen entfernt, ohne Haken bleibt er. Selbst hinzugefügte Namen lassen sich löschen.",
        urlCleanerRulesCoverageCaption: "Die Liste deckt die verschiedenen Teilen-Wege einer Website ab (Webseite, App, Livestream), deshalb ist sie lang; ein echter Link trägt meist nur zwei bis vier davon.",
        urlCleanerRulesAllSites: "Alle Websites",
        urlCleanerRulesAddSite: "Website hinzufügen",
        urlCleanerRulesParameterPlaceholder: "Parametername",
        urlCleanerRulesMatchCaption: "Trage den Namen links vom = ein, etwa utm_source. Ein passender Name nimmt genau diesen Parameter aus dem Link und lässt den Rest, wie er war.",
        urlCleanerRulesAddButton: "Hinzufügen",
        urlCleanerRemovedFormat: "Entfernt %@",
        switcherSearchPin: "Suche mit S anpinnen",
        switcherSearchPinCaption: "S startet die Suche und pinnt den Umschalter an – so tippst du keine Sonderzeichen mehr, wenn dein Kurzbefehl ⌥ nutzt, und eine Suche, die mit Q oder W beginnt, schließt das Fenster oder die App nicht mehr versehentlich.",
        invertVerticalScroll: "Vertikales Scrollen umkehren",
        invertHorizontalScroll: "Horizontales Scrollen umkehren",
        switcherShowShortcutHints: "Kurzbefehlhinweise anzeigen",
        switcherShowShortcutHintsCaption: "Zeigt die Kurzbefehle für Apps und Fenster unter den Symbolen.",
        uninstallerHomebrewPackageFormat: "%@ wird auch aus Homebrew entfernt.",
        shelfEdgeToggle: "In der Nähe eines Bildschirmrands öffnen",
        shelfEdgeCaption: "Ziehe eine Datei in Richtung Bildschirmrand, damit die Ablage kurz hervorschaut. Lass sie dort los, oder zieh zurück, und die Ablage verschwindet wieder.",
        focusFollowsMouseName: "Fokus folgt Maus",
        focusFollowsMouseCaption: "Fokussiert das Fenster unter dem Zeiger und bringt es nach kurzer Pause nach vorn.",
        focusFollowsMouseDelay: "Verzögerung",
        switcherMinimizedPlacementLabel: "Minimierte Fenster",
        switcherMinimizedPlacementNormal: "Normale Reihenfolge",
        switcherMinimizedPlacementEnd: "Ans Ende stellen",
        switcherMinimizedPlacementHidden: "Ausblenden",
        switcherShowFullscreenWindows: "Vollbildfenster anzeigen",
        switcherScreenPlacementLabel: "Anzeigen auf",
        switcherScreenPlacementPointer: "Bildschirm mit dem Zeiger",
        switcherScreenPlacementMenuBar: "Bildschirm mit der Menüleiste",
        switcherScreenPlacementActiveWindow: "Bildschirm mit dem aktiven Fenster",
        switcherScreenPlacementCaption: "Auf welchem Bildschirm der Umschalter erscheint, wenn mehrere angeschlossen sind.",
        smoothScrollResponseLabel: "Reaktion",
        mouseAccelerationName: "Mausbeschleunigung deaktivieren",
        mouseAccelerationCaption: "Deaktiviert die Zeigerbeschleunigung für angeschlossene Mäuse. Die vorherige Einstellung wird beim Ausschalten oder Beenden von \(AppInfo.name) wiederhergestellt.",
        shelfClearOnClose: "Beim Schließen leeren",
        shelfClearOnCloseCaption: "Leert die Ablage nur, wenn du auf die Schließen-Taste klickst. Automatisches Ausblenden und Einklappen behalten die Objekte."
    )
}
