// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 日本語 — translated and hand-checked, not machine output.
extension Strings {
    static let ja = Strings(
        statusIdleTooltip: "\(AppInfo.name)：通常のスリープ",
        statusActiveUntil: "\(AppInfo.name)：次の時刻までスリープしない",
        statusActiveIndefinite: "\(AppInfo.name)：解除するまでスリープしない",
        menuEnableAwake: "スリープ防止をオン",
        menuDisableAwake: "スリープ防止をオフ",
        menuActivateFor: "時間を指定してオン…",
        menuSettings: "設定…",
        menuAbout: "\(AppInfo.name) について",
        menuQuit: "\(AppInfo.name) を終了",
        menuHide: "\(AppInfo.name) を隠す",
        menuHideOthers: "ほかを隠す",
        menuShowAll: "すべてを表示",
        menuEdit: "編集",
        menuUndo: "取り消す",
        menuRedo: "やり直す",
        actionClear: "消去",
        actionRemove: "削除",
        actionBack: "戻る",
        actionSearch: "検索",
        actionMute: "消音",
        actionUnmute: "再開",
        actionPlay: "再生",
        actionPause: "一時停止",
        menuCut: "カット",
        menuCopy: "コピー",
        menuPaste: "ペースト",
        menuSelectAll: "すべてを選択",
        menuWindow: "ウインドウ",
        menuMinimize: "しまう",
        menuZoom: "拡大／縮小",
        menuClose: "閉じる",

        minutes15: "15分",
        minutes30: "30分",
        hour1: "1時間",
        hours2: "2時間",
        hours4: "4時間",
        hours8: "8時間",
        indefinitely: "無期限",
        indefinite: "無期限",

        panelSettings: "設定",
        panelQuit: "終了",

        keepAwakeTitle: "スリープ防止",
        keepAwakeEndsIn: "残り",
        keepAwakeUntilDisabled: "オフにするまで継続",
        keepAwakeNormalRules: "Mac は通常の省エネルギー設定に従います",
        keepAwakeOptions: "オプション",
        keepAwakeMouseJiggle: "ポインタを少し動かす",
        keepAwakeMouseJiggleCaption: "セッション中、選んだ間隔でポインタを少し動かします。",
        keepAwakeMouseJiggleInterval: "間隔",
        keepAwakeActiveIconLabel: "使用中のアイコン",
        keepAwakeActiveIconVorssaint: "\(AppInfo.name)",
        keepAwakeActiveIconCoffee: "コーヒー",
        keepAwakeActiveIconEye: "目",
        keepAwakeActiveIconMoon: "月",
        keepAwakeActiveIconLight: "電球",
        keepAwakeIconTintLabel: "アクティブ時のアイコン色",
        keepAwakeIconTintOrange: "オレンジ",
        keepAwakeIconTintGreen: "緑",
        keepAwakeIconTintBlue: "青",
        keepAwakeIconTintPurple: "紫",
        keepAwakeIconTintPink: "ピンク",
        keepAwakeIconTintNone: "色なし",
        durationLabel: "継続時間",
        clamshellTitle: "ふたを閉じても続ける",
        clamshellOnCaption: "スリープを完全に無効化中。電源にご注意ください",
        clamshellNeedsSession: "「スリープ防止」がオンのあいだ常に適用されます",
        clamshellReady: "準備完了。パスワードなしで切り替えられます",
        clamshellNeedsPassword: "管理者パスワードは一度だけ求められます",

        systemSection: "システム",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "バッテリー",
        usageSection: "ハードウェア使用状況",
        memorySection: "メモリ",
        memoryPressure: "プレッシャー",
        memorySwapUsed: "使用中のスワップ",
        memoryCompressed: "圧縮",
        memoryCachedFiles: "キャッシュ済み",
        pressureNormal: "標準",
        pressureWarning: "注意",
        pressureCritical: "危険",
        monitorUnavailable: "この Mac ではセンサーを利用できません",
        energyAppsTitle: "大きなエネルギー使用",
        energyAppsIdle: "大きなエネルギー使用なし",

        notifySessionEndedTitle: "セッションが終了しました",
        notifySessionEndedBody: "時間になりました。Mac は再び通常どおりスリープします。",
        notifyBatteryTitle: "\(AppInfo.name) をオフにしました",
        notifyBatteryBody: "バッテリー残量が少なくなりました。充電を保護するため通常のスリープに戻しました。",
        adminPromptClamshellOff: "Mac の通常のスリープを元に戻すにはパスワードが必要です。",
        adminPromptRecover: "Mac のスリープを無効化したまま \(AppInfo.name) が終了しました。通常のスリープに戻すにはパスワードを入力してください。",
        adminPromptUpdate: "アップデートをインストールするには \(AppInfo.name) にパスワードが必要です。",
        adminPromptSudoersInstall: "ふたを閉じたモードをパスワードなしで切り替えられるよう、\(AppInfo.name) が制限付きルール（pmset disablesleep のみ）を作成します。パスワードが必要なのはこの一度きりです。",
        adminPromptSudoersRemove: "パスワード不要のふたを閉じたモードのルールを \(AppInfo.name) が削除します。",

        settingsTitle: "\(AppInfo.name) 設定",
        tabGeneral: "一般",
        tabMouse: "マウス",
        tabDock: "Dock",
        tabWindowBehavior: "ウインドウの動作",
        tabKeyboard: "キーボード",
        tabTrackpad: "トラックパッド",
        tabAdvanced: "詳細",
        tabAbout: "情報",
        tabReleaseNotes: "新機能",
        advancedResetSection: "アクセス権",
        advancedResetDescription: "\(AppInfo.name) に許可したすべてのアクセス権（アクセシビリティ、画面収録、フルディスクアクセスなど）、ログイン項目、ふたを閉じたモードのルールを削除します。最初からやり直すときや、アンインストールの前に便利です。アプリはインストールされたまま残ります。",
        advancedClearButton: "すべてのアクセス権を消去",
        advancedCleared: "アクセス権を消去しました。",
        advancedClearConfirmTitle: "すべてのアクセス権を消去しますか？",
        advancedClearConfirmBody: "アクセス権が必要な機能は、再度許可するまで動作しなくなります。設定はそのまま保持されます。",
        advancedUninstallSection: "アンインストール",
        advancedUninstallDescription: "このアプリの権限、ログイン項目、パスワード不要のクラムシェル用ルールを解除し、設定とローカルのアプリデータの削除を試みます。アプリの終了後、ゴミ箱への移動を試みます。別に保存したバックアップや書き出したファイルは削除しません。",
        advancedUninstallButton: "\(AppInfo.name) を完全にアンインストール",
        advancedUninstallConfirmTitle: "\(AppInfo.name) をアンインストールしますか？",
        advancedUninstallConfirmBody: "\(AppInfo.name) はアクセス権を消去し、環境設定を削除し、ゴミ箱に移動してから終了します。この操作はアプリからは取り消せませんが、ゴミ箱を空にするまではゴミ箱に残ります。",
        advancedUninstallFailedTitle: "アンインストールを中止しました",
        advancedUninstallFailedBody: "\(AppInfo.name) が変更したシステム設定（スリープ、ファンの回転数、マウス加速）を元に戻せませんでした。何も削除していません。もう一度試して、パスワードの入力を求められたら許可してください。",

        launchAtLogin: "ログイン時に起動",
        languageLabel: "言語",
        showCountdown: "アイコンの横に残り時間を表示",
        hotkeyToggle: "「スリープ防止」のショートカットを有効にする",
        hotkeyCaption: "追加のアクセス権なしで、どのアプリでも使えます。",

        sessionSection: "セッション",
        defaultDurationLabel: "デフォルトの継続時間",
        keepAwakeAutoStart: "\(AppInfo.name)起動時にスリープを防ぐ",
        keepAwakeAutoStartCaption: "既定の時間でセッションを開始します。",
        batteryProtectionSection: "バッテリー保護",
        batteryDisableBelow: "バッテリーが次の値を下回ったらオフにする",
        batteryNever: "しない",
        batteryProtectionCaption: "オンのままになったセッションが MacBook のバッテリーを消耗させるのを防ぎます。",
        clamshellSection: "ふたを閉じたモード",
        configuring: "設定中…",
        sudoersFailed: "ふたを閉じたモードを有効にできませんでした。もう一度お試しください。",
        clamshellExplanation: "「ふたを閉じても続ける」は、「スリープ防止」がオンのあいだスリープを完全に無効化し、セッションの終了時またはアプリの終了時に自動的に元に戻ります。電源に接続した状態での使用をおすすめします。",

        scrollSection: "スクロール",
        invertMouseScroll: "マウスのスクロールを反転",
        invertMouseScrollCaption: "マウスホイールのスクロール方向を逆にします。",
        scrollTrackpadNote: "トラックパッドはそのままで、macOS のナチュラルなスクロールを維持します。",
        scrollActiveNow: "現在マウスのスクロールを反転中",
        mouseNavigationActiveNow: "サイドボタンは現在有効です",
        smoothScrollName: "スムーズスクロール",
        smoothScrollCaption: "マウスホイールの1目盛りを短くなめらかなスライドに変えます。トラックパッドは変わりません。",
        smoothScrollStepLabel: "スクロール速度",
        mouseNavigationEnable: "サイドボタンで戻ると進むを操作",
        mouseNavigationCaption: "マウスの戻るボタンと進むボタンを、Finder、ブラウザ、対応アプリのナビゲーション操作に変換します。",
        middleClickSection: "中クリック",
        middleClickEnable: "3本指クリックを中クリックにする",
        middleClickEnableCaption: "トラックパッドを3本指で押すと、マウスのホイールクリックと同じように動作します。リンクを新しいタブで開く、タブを閉じるなど、中ボタンでできることすべてに使えます。",
        middleClickDragConflict: "macOSの3本指のドラッグがオンになっており、同じジェスチャを使用します。システム設定のアクセシビリティ、ポインタコントロール、トラックパッドオプションでオフにすると、中クリックが機能します。",
        middleClickTapPicker: "軽いタップでもクリック",
        middleClickTapOff: "オフ",
        middleClickTapThreeFingers: "3 本指",
        middleClickTapFourFingers: "4 本指",
        middleClickTapCaption: "その本数の指で軽くタップ（押し込まずに）しても中クリックが発火します。スライドは対象外です。macOS の 3 本指タップが「調べる」に割り当てられている場合は、両方が同時に発火しないようオフにしてください。",
        quickToolShortcutToggle: "グローバルショートカット",
        ocrName: "画面のテキストをコピー",
        ocrCaption: "画面の範囲を選択すると、認識されたテキストがコピーされ、すぐにペーストできます。",
        ocrCopied: "テキストをコピーしました",
        ocrNoText: "テキストが見つかりません",
        colorPickerName: "カラーピッカー",
        colorPickerCaption: "画面上の任意のピクセルの色を取得し、好みの形式でコピーします。",
        colorPickerFormatLabel: "コピー形式",
        colorPickerBareHexToggle: "先頭の # を付けずにコピー",
        colorPickerPickNow: "色を取得",
        pastePlainName: "プレーンテキストとしてペースト",
        pastePlainCaption: "コピーした内容を色・フォント・書式なしでペーストします。元の内容はクリップボードに残ります。",
        switcherSection: "アプリスイッチャー",
        switcherEnable: "\(AppInfo.name) のスイッチャーを使う",
        switcherEnableCaption: "アプリやウインドウを切り替えます。最小化したウインドウや同じアプリの複数ウインドウにも対応します。",
        switcherNoWindows: "開いているウインドウはありません",
        appQuitFailedFormat: "終了を要求できませんでした（%@）。",
        switcherIconRowMode: "%@ を大きなアイコンで表示",
        switcherIconRowModeCaption: "アプリごとに1つのアイコンを表示し、その上にそのアプリのウインドウプレビューを表示します。",
        switcherSimpleMode: "シンプルなアプリスイッチャー",
        switcherSimpleModeCaption: "プレビューやスイッチャーによる画面収録を使わず、アプリのアイコンとウインドウのタイトルを表示します。",
        switcherShortcutHintApps: "アプリ",
        switcherShortcutHintWindows: "ウインドウ",
        switcherWindowShortcutCaption: "最前面のアプリのウインドウ用スイッチャーを開きます。アプリスイッチャー表示中は、選択中のアプリのウインドウを順に切り替えます。",
        switcherTakeOverSystemShortcuts: "macOS の ⌘Tab と ⌘` を置き換える",
        switcherTakeOverSystemShortcutsCaption: "\(AppInfo.name) のスイッチャーが動作中の間だけ、対応する macOS のアプリとウインドウのショートカットを無効にします。実行中のすべてのアプリに切り替えられます。",
        switcherAppearanceDelay: "表示までの待ち時間",
        switcherAppearanceDelayCaption: "スイッチャーが表示されるまでショートカットを押し続ける時間です。",
        switcherMergeTabs: "アプリごとに1つにまとめて表示",
        switcherMergeTabsCaption: "スイッチャーで、アプリのすべてのウインドウをウインドウごとではなく1つの項目にまとめます。",
        switcherWindowlessApps: "ウインドウなしのアプリ",
        switcherWindowlessAppsCaption: "ウインドウを1つも開いていない起動中のアプリのうち、どれをスイッチャーに表示するかを選びます。",
        switcherWindowlessAppsOff: "表示しない",
        switcherWindowlessAppsFinder: "Finder のみ",
        switcherWindowlessAppsAll: "すべてのアプリ",
        switcherNoOpenWindow: "ウインドウなし",
        switcherOtherDesktop: "別のデスクトップ",

        cutPasteName: "カット＆ペースト",
        cutPasteEnable: "Finder でファイルをカット＆ペースト",
        cutPasteEnableCaption: "⌘X でカット、⌘V で Finder のファイルやフォルダを移動できます。",
        cutPasteShowHUD: "フローティングパネルを表示",
        cutPasteShowHUDCaption: "Finder がアクティブなときに、カットしたファイルのフローティング表示を出します。",
        cutPasteHowTitle: "使いかた",
        cutPasteStep1: "Finder で項目を選択し、⌘X を押してカットします。",
        cutPasteStep2: "移動先のフォルダを開き、⌘V を押してそこへ移動します。",
        cutPasteTextNote: "テキストフィールド内では（名前の変更時など）、⌘X と ⌘V はこれまでどおり動作します。",
        cutPasteActiveNow: "Finder でカットできます",
        cutPasteAutomationNote: "初回は、macOS が Finder を制御する許可を求めます。",
        cutReadyTitle: "カットしました",
        cutReadyHint: "移動先のフォルダで",
        cutCancel: "カットをキャンセル",
        cutDoneTitle: "移動しました！",
        cutMovedSingular: "1項目を移動しました",
        cutMovedPluralFormat: "%d項目を移動しました",
        cutSomeFailed: "一部の項目を移動できませんでした",
        cutMovingTitle: "移動中…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "閉じたら終了",
        autoQuitEnable: "最後のウインドウを閉じたらアプリを終了",
        autoQuitEnableCaption: "アプリの最後のウインドウを閉じると、そのアプリも終了します。",
        autoQuitActiveNow: "現在有効",
        autoQuitStep1: "アプリの最後のウインドウを閉じます（⌘W または赤いボタン）。",
        autoQuitStep2: "アプリは自動的に終了します。「変更を保存しますか？」のダイアログは引き続き表示されます。",
        autoQuitPredictableNote: "通常ウインドウなしで動作するアプリは、終了されることはありません。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "このリストのアプリは、ウインドウがなくても開いたままになります。",
        autoQuitExceptionsEmpty: "例外はありません",
        autoQuitAddApp: "アプリを追加…",

        uninstallerName: "アンインストーラ",
        uninstallerEnableCaption: "アプリを、それが残すキャッシュ、環境設定、ログ、残存ファイルもろとも削除します。",
        uninstallerMenuItem: "アプリをアンインストール…",
        uninstallerDropTitle: "ここにアプリをドラッグ",
        uninstallerDropSubtitle: "またはスキャンするアプリを選択",
        uninstallerChoose: "アプリを選択…",
        uninstallerPickerTitle: "アプリを選択",
        uninstallerPickerSearch: "アプリを検索",
        uninstallerPickerEmpty: "アプリが見つかりません",
        uninstallerEmptyNote: "確認なしに削除されるものはありません。",
        uninstallerFDANote: "より徹底的にスキャンするにはフルディスクアクセスを許可してください。",
        uninstallerFDAGrant: "アクセスを許可…",
        uninstallerFDAHint: "リストで \(AppInfo.name) をオンにします。表示されない場合は + をクリックし、アプリケーションから \(AppInfo.name) を選びます。アクセス権はアプリを再度開いた後に有効になります。",
        uninstallerFDARelaunch: "今すぐ再起動",
        uninstallerScanning: "ファイルをスキャン中…",
        uninstallerRemoving: "ゴミ箱に移動中…",
        uninstallerFoundTitle: "件見つかりました",
        uninstallerSelectedFormat: "%d／%d 件を選択中",
        uninstallerRemove: "ゴミ箱に移動",
        uninstallerCancel: "キャンセル",
        uninstallerDoneTitle: "完了！",
        uninstallerFreedFormat: "削除したデータ：%@",
        uninstallerSomeFailed: "一部の項目をゴミ箱に移動できませんでした。",
        uninstallerConfirmationExpired: "この確認は無効になりました。現在の項目を確認して、もう一度承認してください。",
        uninstallerFailedNeedsFDA: "サンドボックス内のアプリデータは、フルディスクアクセスがなければ移動できません。管理者パスワードでは代われません。",
        uninstallerFailedMoreFormat: "ほか %d 項目",
        uninstallerAnother: "別のアプリをアンインストール",
        uninstallerCatApp: "アプリケーション",
        uninstallerCatSupport: "サポート",
        uninstallerCatCaches: "キャッシュ",
        uninstallerCatPreferences: "環境設定",
        uninstallerCatContainers: "コンテナ",
        uninstallerCatLogs: "ログ",
        uninstallerCatState: "保存された状態",
        uninstallerCatOther: "その他",

        urlCleanerName: "URL をクリーン",
        urlCleanerEnable: "コピー時に URL を自動でクリーン",
        urlCleanerEnableCaption: "リンクがクリップボードに入った時点でトラッキング用パラメータを削除します。",
        urlCleanerActiveNow: "現在有効",
        urlCleanerManualTitle: "今すぐクリーン",
        urlCleanerInputPlaceholder: "URL をペースト",
        urlCleanerOutputPlaceholder: "クリーンな URL がここに表示されます",
        urlCleanerCleanButton: "クリーン",
        urlCleanerPasteButton: "ペースト",
        urlCleanerCopyButton: "コピー",
        urlCleanerClearButton: "欄をクリア",
        urlCleanerNoURL: "有効な URL をペーストしてください。",
        urlCleanerNoChange: "削除するものはありません。",
        urlCleanerCleaned: "URL をクリーンしました。",
        urlCleanerCopied: "コピーしました。",
        urlCleanerLocalNote: "ローカル。通信なし。",

        homebrewName: "Homebrew",
        homebrewMissingTitle: "Homebrew が見つかりません",
        homebrewMissingBody: "Homebrew がインストールされていません。入れると、管理下のパッケージがここに並びます。",
        homebrewRequested: "自分で入れたもの",
        homebrewMasApps: "App Store",
        homebrewCopyName: "名前をコピー",
        homebrewTrustTitle: "まだ信頼されていないTap",
        homebrewTrustCaption: "Homebrewはサードパーティ製Tapを使う前に確認を求めるようになりました。%@を信頼すると続行できます。",
        homebrewTrustButton: "信頼して続ける",
        homebrewNoPackages: "パッケージが見つかりません",
        homebrewUninstall: "アンインストール",
        homebrewUpgrade: "更新",
        homebrewPinnedVersion: "バージョン固定中",
        homebrewAllPackages: "パッケージ",
        homebrewOpenTerminal: "Terminal を開く",
        homebrewCancelOperation: "キャンセル",
        homebrewClearLog: "ログをクリア",
        homebrewHomepage: "サイトを開く",
        homebrewUpdateAvailableBadge: "更新あり",
        homebrewConfirmUninstallTitle: "Homebrew でアンインストールしますか？",
        homebrewConfirmUninstallBodyFormat: "Homebrew が %@ をアンインストールします。設定ファイルがシステムに残る場合があります。",
        homebrewConfirmUpgradeTitle: "Homebrew で更新しますか？",
        homebrewConfirmUpgradeBodyFormat: "Homebrew が %@ の最新バージョンをダウンロードして適用します。依存関係も更新される場合があります。",
        homebrewTerminalFallback: "この操作では管理者パスワードを求めるために Terminal が必要です。\(AppInfo.name) はパスワードを取得しません。",
        homebrewLoading: "読み込み中…",
        homebrewOperationUninstallFormat: "%@ をアンインストール中",
        homebrewOperationUpgradeFormat: "%@ を更新中",
        homebrewOperationUpdateHomebrew: "Homebrew を更新中",
        homebrewOperationUninstalledFormat: "%@ をアンインストールしました。",
        homebrewOperationUpgradedFormat: "%@ を更新しました。",
        homebrewOperationUpdatedHomebrew: "Homebrew を更新しました。",
        homebrewOperationFailedFormat: "%@ を完了できませんでした。",
        homebrewOperationCancelled: "操作をキャンセルしました。",
        homebrewOperationPreparing: "準備中…",
        homebrewOperationDownloading: "ファイルをダウンロード中…",
        homebrewOperationUninstalling: "ファイルを削除中…",
        homebrewOperationUpgrading: "ファイルを更新中…",
        homebrewOperationFinalizing: "完了処理中…",
        homebrewOperationRefreshing: "一覧を更新中…",
        homebrewOperationTerminal: "Terminal で続行してください。",
        homebrewOperationElapsedFormat: "%@ 経過",
        homebrewOperationShowDetails: "詳細を表示",
        homebrewOperationHideDetails: "詳細を隠す",
        homebrewOperationTechnicalLog: "技術的な詳細",
        homebrewOperationProgressUnknown: "Homebrew はまだ割合を報告していません。",

        mediaName: "メディア",
        mediaEnableCaption: "動画を圧縮し、画像の変換と加工、GIF の作成、テキストの抽出をローカルで行います。",
        mediaLocalNote: "ローカル。ネットワークなし。",
        mediaToolVideo: "動画",
        mediaToolGIF: "GIF",
        mediaToolImage: "画像",
        mediaToolText: "テキスト",
        mediaSelectFile: "ファイルを選択",
        mediaDropHint: "ここにファイルをドロップするか、クリックして選択します。",
        mediaOutput: "出力",
        mediaOutputAutomatic: "自動",
        mediaChooseOutput: "保存先",
        mediaStartVideo: "動画を圧縮",
        mediaStartGIF: "GIF を作成",
        mediaStartImage: "画像を加工",
        mediaStartConvertPDF: "PDFに変換",
        mediaStartText: "テキストを抽出",
        mediaCancel: "キャンセル",
        mediaStartTime: "開始",
        mediaEndTime: "終了",
        mediaQuality: "圧縮",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "サイズ",
        mediaSizingResolution: "解像度",
        mediaSizingFileSize: "ファイルサイズ",
        mediaTargetSize: "目標サイズ",
        mediaTargetSizeHint: "上限を超えないよう解像度が自動で調整されます。",
        mediaErrorTargetTooSmall: "この動画には目標サイズが小さすぎます。長さを短くするか上限を上げてください。",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "幅",
        mediaFPS: "FPS",
        mediaFormat: "形式",
        mediaStripMetadata: "メタデータを削除",
        mediaLoopGIF: "GIF をループ",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "高精度",
        mediaOCRFast: "高速",
        mediaRunning: "処理中",
        mediaCompleted: "完了",
        mediaCancelled: "キャンセルしました。",
        mediaOpenInFinder: "表示",
        mediaCopyText: "テキストをコピー",
        mediaRunAgain: "もう一度実行",
        mediaEmptyText: "テキストが見つかりません。",
        mediaResultSavedFormat: "%@ として保存しました",
        mediaResultSizeFormat: "%@ から %@",
        mediaResultGrewCaption: "変換後のファイルは元より大きくなりました。",
        mediaErrorNoFile: "先にファイルを選択してください。",
        mediaErrorNoVideo: "このファイルには動画トラックがありません。",
        mediaErrorSameOutput: "元のファイルとは別の保存先を選んでください。",
        mediaErrorUnsupported: "macOS が対応していない形式です。",

        shelfName: "シェルフ",
        shelfEnable: "ファイルをドラッグする一時置き場",
        shelfEnableCaption: "ファイル、画像、テキストを集めておき、あとからどこへでもドラッグできるフローティングの置き場です。",
        shelfHowTitle: "使いかた",
        shelfStep1: "ショートカットを押すか、ドラッグ中にマウスを振って開きます。",
        shelfStep2: "ファイル、画像、リンク、テキストをドロップして保持します。",
        shelfStep3: "必要なときに、各項目をどのアプリへでもドラッグして取り出します。",
        shelfShakeToggle: "ドラッグ中にマウスを振って開く",
        shelfShakeCaption: "項目を持ったままポインタをすばやく振ると、カーソルの近くに呼び出せます。",
        shelfDropZoneToggle: "ドラッグしたファイルをメニューバーに残す",
        shelfDropZoneCaption: "ファイルをドラッグすると、メニューバーのアイコンの下にシェルフが表示されます。ドロップしたものはそのままそこに保存され、クリックで開閉できるボタンに収まり、シェルフが空になると消えます。",
        shelfCollapse: "折りたたむ",
        shelfBehaviorTitle: "使用後",
        shelfCloseAfterDrop: "別のアプリにドロップしたら閉じる",
        shelfCloseAfterDropCaption: "ドロップ先が項目を受け取るとシェルフを閉じます。パネルのピンで開いたままにできます。",
        shelfRemoveAfterDrop: "ドロップ後に項目を削除",
        shelfRemoveAfterDropCaption: "別のアプリが受け取った項目をシェルフから削除します。コピーを残す場合はオフにします。",
        shelfExclusionsTitle: "自動表示の例外",
        shelfExclusionsEmpty: "アプリは追加されていません。",
        shelfExclusionsCaption: "これらのアプリから始めたドラッグでは、振る操作とメニューバーの領域は開きません。ショートカットと今すぐ開くは引き続き使えます。",
        shelfPin: "開いたままにする",
        shelfUnpin: "使用後に閉じる",
        shelfHotkeyLabel: "ショートカット",
        shelfOpenNow: "今すぐ開く",
        shelfNoPermission: "アクセス権は不要です。",
        shelfMenuItem: "シェルフを開く",
        shelfTitle: "シェルフ",
        shelfEmpty: "ここに項目をドラッグ",
        shelfClearAll: "すべてを消去",
        shelfRemoveSelected: "選択した項目を削除",
        shelfSelectedFormat: "%d 件を選択中",
        shelfHint: "クリックで選択。ドラッグして使用するか、右クリックでその他の操作を表示します。",
        shelfItemImage: "画像",
        shelfTooltipItemsFormat: "%d 件",
        shelfTooltipItemsFew: "%d 件",
        shelfTooltipImageSingular: "%d 枚の画像",
        shelfTooltipImageFew: "%d 枚の画像",
        shelfTooltipImagePlural: "%d 枚の画像",
        shelfTooltipFileSingular: "%d 個のファイル",
        shelfTooltipFileFew: "%d 個のファイル",
        shelfTooltipFilePlural: "%d 個のファイル",
        shelfTooltipNoteSingular: "%d 件のメモ",
        shelfTooltipNoteFew: "%d 件のメモ",
        shelfTooltipNotePlural: "%d 件のメモ",
        shelfTooltipLinkSingular: "%d 件のリンク",
        shelfTooltipLinkFew: "%d 件のリンク",
        shelfTooltipLinkPlural: "%d 件のリンク",
        shelfActionOpen: "開く",
        shelfActionOpenWith: "このアプリケーションで開く",
        shelfActionShare: "共有",

        breakdownMeasuring: "計測中…",

        preciseVolumeRollerEnable: "より細かい音量ステップを使う",
        preciseVolumeRollerCaption: "音量ホイールやキーを、より小さなシステム音量ステップに変換します。",
        preciseVolumeRollerTapFailed: "音量キーを監視できませんでした。",

        updatesSection: "アップデート",
        autoCheckToggle: "アップデートを自動的に確認",
        betaBadgeLabel: "ベータ",
        checkNowButton: "今すぐ確認",
        updateChecking: "確認中…",
        updateUpToDate: "最新バージョンを使用しています。",
        updateAvailablePrefix: "アップデートが利用できます：",
        updateInstallButton: "ダウンロードしてインストール",
        updateDownloading: "アップデートをダウンロード中…",
        updateInstalling: "インストールして再起動中…",
        updateFailedPrefix: "確認できませんでした：",
        updateLastChecked: "前回の確認：",
        updateNotifyTitle: "\(AppInfo.name) のアップデート",
        updateInstallFailedBody: "アップデートはダウンロードされましたが、適用できませんでした。GitHub のリリースページから最新版をダウンロードし、現在のアプリの上にドラッグして置き換えてください。",
        updateNeedsApplicationsTitle: "\(AppInfo.name) を「アプリケーション」に移動してください",
        updateNeedsApplicationsBody: "アプリが、ディスクイメージやシステムの一時的な場所など、アップデートできない場所から実行されています。\(AppInfo.name) を「アプリケーション」フォルダにドラッグし、そこから開いてからもう一度お試しください。",
        menuCheckUpdates: "アップデートを確認…",

        permissionRequired: "アクセス権が必要です",
        permissionAccessibility: "アクセシビリティ",
        permissionScreenRecording: "画面収録",
        permissionGranted: "許可済み",
        permissionMissing: "未許可",
        permissionOpenSettings: "システム設定を開く…",
        permissionRequest: "アクセスを許可",
        permissionRestartNote: "許可後、macOS がアプリの再オープンを求めることがあります。",

        aboutDescription: "あなたの Mac のためのユーティリティハブ。\n省エネルギー、システムモニタ、スクロール、ウインドウスイッチャーを、メニューバーから。",
        versionPrefix: "バージョン",
        reviewIntro: "はじめにを見直す",
        reviewHighlights: "新機能ツアーを見直す",
        viewOnGitHub: "GitHub で見る",

        obContinue: "続ける",
        obBack: "戻る",
        obStart: "\(AppInfo.name) を開く",
        obStepWelcomeTitle: "\(AppInfo.name) へようこそ",
        obStepWelcomeBody: "日々の macOS をもっと快適にする、控えめなメニューバーユーティリティです。",
        obWelcomeBullet1Title: "省エネルギーを思いどおりに",
        obWelcomeBullet1Body: "ふたを閉じたままでも、好きなだけ Mac をスリープさせずに使えます。",
        obWelcomeBullet2Title: "システムをひと目で把握",
        obWelcomeBullet2Body: "CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーをリアルタイムで。",
        obWelcomeBullet3Title: "マウスとウインドウを自分流に",
        obWelcomeBullet3Body: "マウスのスクロール反転と、サムネール付きのウインドウスイッチャー。",
        obLanguageLabel: "言語",
        obStepDoneTitle: "準備完了！",
        obStepDoneBody: "\(AppInfo.name) はすでにあなたの Mac を見守っています。",
        obDoneHint: "画面右上のメニューバーで、タコのアイコンを探してください。",
        obWhatsNewTitle: "このバージョンの新機能",
        obWhatsNewFallback: "このアップデートには最新の修正と改善が含まれています。",
        obPurposeTitle: "目的を教えてください",
        obPurposeBody: "有効にする機能を個別に選択します。既存の設定は保持されます。",
        obPurposeSkip: "機能は後から設定で追加または削除できます。",

        tabMonitor: "モニタ",
        tabMenuBarIcon: "メニューバーのアイコン",
        tabMenuBarPanel: "メニューバーパネル",
        monitorMenuBarSection: "メニューバー",
        monitorCombineTemperatures: "使用率と温度をまとめる",
        monitorCombineTemperaturesCaption: "同じ項目の使用率と温度が有効な場合、1つのブロックにまとめて表示します。",
        monitorSeparateMenuBarMetrics: "メトリクスを個別の項目に分ける",
        monitorSeparateMenuBarMetricsCaption: "有効なブロックをメニューバーで分け、結合がオンなら使用率と温度は一緒に表示します。",
        monitorNetworkUploadFirst: "アップロードをダウンロードの上に表示",
        monitorShowCPU: "CPU",
        monitorShowMemory: "メモリ",
        monitorShowNetwork: "ネットワーク",
        monitorShowPowerLabel: "電源",
        monitorIntervalLabel: "更新間隔",
        monitorInterval1: "1秒",
        monitorInterval2: "2秒",
        monitorInterval5: "5秒",
        monitorPanelSection: "パネル",
        betaBadge: "BETA",
        betaFeatureWarning: "ベータ版です。一部の不具合が残っている場合があります。",

        networkSection: "ネットワーク",
        networkDownload: "ダウンロード",
        networkUpload: "アップロード",
        networkThisSession: "このセッション",
        networkMeasuring: "計測中…",
        networkApps: "通信中のアプリ",
        networkAppsIdle: "現在ネットワークを使用中のアプリはありません",

        diskSection: "ディスク",
        diskUsed: "使用済み",
        diskAvailable: "利用可能",
        diskPurgeable: "パージ可能",
        diskInternal: "内蔵",
        diskExternal: "外部",
        diskSelect: "ディスクを選択",
        diskRead: "読み込み",
        diskWrite: "書き込み",
        diskSMARTStatus: "状態",
        diskSMARTUnavailable: "このディスクでは SMART を利用できません",
        diskTotalRead: "総読み込み",
        diskTotalWritten: "総書き込み",
        diskTemperature: "温度",
        diskHealth: "健康状態",
        diskPowerCycles: "電源投入回数",
        diskPowerOnHours: "通電時間",
        diskEject: "取り出す",
        diskEjectAll: "すべて取り出す",
        diskEjecting: "取り出し中…",
        diskReadyToRemove: "取り外せます",
        diskEjectFailed: "取り出せませんでした",
        diskProtectionCaption: "抜く前に取り出します。",
        diskNoExternal: "取り出せる外部ディスクはありません。",
        diskOpenInFinder: "開く",
        diskStorageSettings: "ストレージ",
        diskNoDisks: "マウント済みディスクが見つかりません。",

        powerSection: "電源",
        powerSystem: "システム",
        powerAdapter: "アダプタ",
        powerBattery: "バッテリー",
        powerCharging: "充電中",
        powerOnBattery: "バッテリー駆動",
        powerPluggedIn: "電源に接続",
        powerUnavailable: "この Mac では電源の計測値を利用できません",
        powerAdapterMaxFormat: "最大 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU温度",
        monitorShowGPUTemperature: "GPU温度",
        monitorShowBatteryTemperature: "バッテリー温度",
        monitorShowPeripheralBattery: "周辺機器のバッテリー",
        peripheralBatteryNoDevices: "周辺機器が見つかりません",

        updateBannerTitle: "アップデートが利用できます",
        updateBannerAction: "アップデート",
        menuBarSpacingLabel: "メニューバーの間隔",
        menuBarSpacingStandard: "標準",
        menuBarSpacingCompact: "コンパクト",
        menuBarHideIconToggle: "メトリクス表示中はアプリのアイコンを隠す",
        menuBarHideIconCaption: "メトリクスがバーから消えたときや、知らせることがあるとき（アップデートの準備完了やマイクの消音）は、アイコンが自動的に戻ります。",
        menuBarIconSection: "App アイコン",
        monitorMemoryPressureDot: "メモリ圧力ドット",
        systemUptime: "稼働時間",
        batteryCharge: "充電量",
        powerHealth: "バッテリーの状態",
        powerCycles: "充放電回数",
        speedTestRun: "速度テスト",
        speedTestAgain: "もう一度テスト",
        speedTestLatency: "レイテンシ",
        speedTestTesting: "テスト中…",
        speedTestFailed: "テストに失敗しました",

        monitorShowInPanel: "パネルに表示",
        disclosureExpanded: "展開済み",
        disclosureCollapsed: "折りたたみ済み",
        panelHideItem: "パネルで非表示",
        panelShowItem: "パネルに表示",
        panelHiddenItem: "非表示",
        monitorItemUptime: "稼働時間",
        monitorItemNetSpeed: "リアルタイム速度",
        monitorItemNetTotals: "セッション合計",
        monitorItemNetTest: "速度テスト",
        monitorItemDiskUsage: "ディスク使用量",
        monitorItemDiskActivity: "ライブ活動",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外部保護",
        monitorItemDiskTools: "ツール",
        monitorOrderSection: "セクションの並び順",
        monitorOrderHint: "ドラッグしてパネルのセクションを並べ替え、目のアイコンで各セクションを表示/非表示にできます。",

        cleaningMenuItem: "クリーニングモード",
        utilitiesSection: "ユーティリティ",
        quickControlsSection: "コントロール",
        panelCategoryWindows: "ウインドウ",
        panelCategoryInput: "マウスとキーボード",
        panelCategoryFiles: "ファイル",
        windowMaximizeName: "緑のボタンでウインドウを最大化",
        windowMaximizeCaption: "左上の緑のボタンをクリックすると、フルスクリーンに切り替えず、現在のデスクトップ内でウインドウを広げます。",
        keyDebounceName: "デバウンス",
        keyDebounceEnable: "重複キーをフィルタ",
        keyDebounceCaption: "非常に速い重複入力をフィルタします。",
        keyDebounceActiveNow: "フィルタ有効",
        keyDebounceGlobalWindow: "全体の時間",
        keyDebouncePerKeySection: "個別キー",
        keyDebouncePerKeyCaption: "キーごとの値は全体の時間より優先されます。0 ms にするとそのキーはフィルタされません。",
        keyDebounceKeyLabel: "キー",
        keyDebounceAddKey: "キーを追加",
        keyDebounceNoOverrides: "個別キーは設定されていません。",
        keyDebounceRemoveKey: "キーを削除",
        cleaningPanelCaption: "安全に掃除できるようキーボードをロックします。",
        cleaningOverlayTitle: "クリーニングのためキーボードをロック中",
        cleaningOverlaySubtitle: "Escキーを5回押すとロックを解除します",
        cleaningOverlayUnlock: "ロックを解除",
        cleaningOverlayMouseHint: "マウスとトラックパッドはそのまま使えます",
        cleaningKeepScreenVisibleToggle: "画面を表示したままにする",
        cleaningKeepScreenVisibleCaption: "画面を暗くせず、画面の隅に控えめなインジケータを表示します。",
        cleaningStartNow: "今すぐキーボードをロック",
        cleaningNeedsAxTitle: "アクセシビリティが必要です",
        cleaningNeedsAxBody: "キーボードを安全にロックするには、\(AppInfo.name) にアクセシビリティのアクセス権が必要です。システム設定で許可して、もう一度お試しください。",

        shortcutsPageCaption: "このMacにインストールされている機能のグローバルショートカットをすべてここで編集できます。無効なものも保存されますが、動作はしません。",
        shortcutsPageTitle: "キーボードショートカット",
        settingsSearchPlaceholder: "設定を検索",
        supportIntroLaterButton: "今はしない",
        supportIntroDoneButton: "完了",
        updateShowcaseTitle: "3.1.4 の新機能",
        updateShowcaseMessage: "このアップデートの主な改善点を短いプレビューで確認できます。",
        updateShowcaseUnavailable: "今は動画を読み込めません。続けることはできます。",
        updateShowcaseRestart: "最初に戻る",
        showMenuBarIcon: "メニューバーにアイコンを表示",
        showMenuBarIconCaption: "\(AppInfo.name) のアイコンが消えた場合（メニューバーに空きがなくなると macOS がアイコンを隠すことがあり、ノッチのある Mac でよく起こります）、アプリケーションまたは Spotlight から \(AppInfo.name) を開き直してください。アイコンが再作成され、それでも隠れている場合はこのウインドウが開きます。",
        menuBarIconStillHiddenTitle: "アイコンはまだ隠れています",
        menuBarIconStillHiddenBody: "アイコンを作り直しましたが、macOS が表示できる場所を割り当てませんでした。メニューバーに空きがない可能性が高いので、メニューバーのアイコンをいくつか減らす（またはメニューの長いアプリを閉じる）してから、もう一度お試しください。",
        menuBarIconManagerHintFormat: "%@ が起動中で、アイコンを隠しセクションにしまっている可能性があります。そこで \(AppInfo.name) を探すか、%@ で \(AppInfo.name) を常に表示する設定にしてください。",
        shortcutRecording: "新しいショートカットを押してください",
        shortcutReset: "リセット",
        shortcutNone: "なし",
        shortcutClear: "ショートカットを削除",
        shortcutInvalid: "Control、Option、Command のいずれかとキーを組み合わせてください。",
        shortcutPressKeys: "キーを押す",
        shortcutEscapeHint: "Esc で取り消します。",
        shortcutDeleteHint: "Delete で解除します。",
        shortcutNotCaptured: "何も取得できませんでした。この組み合わせは macOS か別のアプリがすでに使っています。別のものを選んでください。",
        shortcutConflictFormat: "このショートカットはすでに %@ で使われています。",
        shortcutUnavailable: "macOS がこのショートカットを拒否しました。別のものを選んでください。",
        shelfShortcutToggle: "Shelf ショートカット",
        switcherUsageHintFormat: "%@ を押したまま移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、W でウインドウを閉じ、Q でアプリを終了、Esc でキャンセルします。",
        cleanerName: "クリーンアップ",
        cleanerIntroTitle: "Mac の不要ファイルを掃除",
        cleanerIntroCaption: "アンインストール済みアプリの残骸、キャッシュ、ログ、ゴミ箱を調べます。実行前にすべて確認でき、削除した項目はゴミ箱に移動します。",
        cleanerScan: "スキャン",
        cleanerScanning: "スキャン中…",
        cleanerCleaning: "クリーンアップ中…",
        cleanerCatLeftovers: "アンインストール済みアプリの残骸",
        cleanerCatLoginItems: "孤立したログイン項目",
        cleanerCatCaches: "キャッシュ",
        cleanerCatLogs: "ログ",
        cleanerCatDeveloper: "開発ジャンク",
        cleanerCatTrash: "ゴミ箱",
        cleanerLeftoversNote: "解析による検出のため最初はオフです。チェックする前にパスを確認してください。",
        cleanerLoginItemsNote: "ログイン項目の表示は Mac の再起動後に消えます。",
        cleanerTrashNote: "ゴミ箱を空にすると元に戻せません。",
        cleanerCatDeviceBackups: "iPhoneのバックアップ",
        cleanerDeviceBackupsCaption: "古いiPhoneやiPadのバックアップは、macOSが「その他」と呼ぶ領域の大部分を占めます。不要なものだけを削除してください。次に接続すると新しいバックアップが作られます。",
        cleanerNothingFound: "掃除するものはありません。Mac は整っています。",
        cleanerIncompleteTitle: "クリーンアップが完了していません",
        cleanerFailedNote: "以下の項目をクリーンアップできませんでした。再スキャンして残りの項目を確認してください。",
        cleanerDoneNote: "項目はゴミ箱に移動され、そこから復元できます。",
        cleanerAgain: "もう一度スキャン",
        cleanerRevealInFinder: "Finder に表示",
        cleanerPanelCaption: "アプリの残骸、キャッシュ、ログ",
        cleanerSafeSection: "安全なクリーンアップ",
        cleanerOptionalSection: "オプション、先に確認",
        cleanerCatOtherCaches: "その他のキャッシュ",
        cleanerCachesCaption: "アプリが自動で作り直す一時ファイルです。",
        cleanerLogsCaption: "古い診断ログです。",
        cleanerDeveloperCaption: "Xcode のビルドとシミュレータの残骸です。",
        cleanerLoginItemsCaption: "もう存在しないアプリが残したログイン項目です。",
        cleanerLeftoversCaption: "アンインストールしたアプリが残したファイルです。",
        cleanerOtherCachesCaption: "削除しても安全で、壊れるものはありません。初回起動が少し遅くなり、オフライン音楽などのダウンロード済みコンテンツは再ダウンロードされます。",
        cleanerCleanSizeFormat: "%@ をクリーンアップ",
        cleanerScheduleTitle: "自動クリーンアップ",
        cleanerScheduleOff: "オフ",
        cleanerScheduleDaily: "毎日",
        cleanerScheduleWeekly: "毎週",
        cleanerScheduleCaption: "選んだ時刻に安全な部分だけを自動で掃除し、すべてゴミ箱に移動します。",
        cleanerAutoNotificationFormat: "%@ を解放してゴミ箱に移動しました。",
        cleanerScheduleNextFormat: "次のクリーンアップは %@。",
        cleanerScheduleNotifyToggle: "完了時に通知",
        cleanerNotifDenied: "\(AppInfo.name) の通知がシステムでオフになっています。",
        cleanerNotifOpenSettings: "通知設定を開く…",
        launchAtLoginNeedsApplications: "ログイン時に開けない場所からアプリが実行されています。\(AppInfo.name)をアプリケーションフォルダにドラッグし、そこから開いてもう一度オンにしてください。",
        launchAtLoginNeedsApproval: "ログイン項目は登録されていますが、システム設定ではオフのままです。「システム設定 › 一般 › ログイン項目と機能拡張」を開き、「ログイン時に開く」で\(AppInfo.name)をオンにしてください。",
        ocrRemoveLineBreaksToggle: "改行を削除",
        ocrRemoveLineBreaksCaption: "認識したテキストの改行を取り除き、1つの段落としてペーストします。",
        ocrQRToggle: "QRコードを読み取る",
        ocrQRCaption: "選択した範囲にQRコードがあると、その内容をコピーまたは開けるように表示します。",
        ocrQRCopied: "QRコードをコピーしました",
        qrResultTitle: "QRコード",
        qrResultCopy: "コピー",
        qrResultOpen: "リンクを開く",
        highlightsTitle: "このアップデートの新機能",
        highlightsTitleQuitProtection: "⌘Qと⌘Wの保護",
        highlightsTitleRecorderBlur: "画面録画のプライバシーぼかし",
        highlightsCaptionQuitProtection: "長押しや2回押し、追加の修飾キーを必要にすることで、アプリやウィンドウの誤終了を防ぎます。アプリごとに設定可能です。",
        highlightsCaptionRecorderBlur: "保存や書き出しの前に、録画ビデオの指定した領域や時間帯でパスワードや個人情報をぼかして隠せます。",
        highlightsConfigure: "設定する",
        highlightsSeeAll: "すべての変更を見る",
        switcherCurrentSpaceOnly: "現在のデスクトップのみ表示",
        switcherCurrentSpaceOnlyCaption: "今いるデスクトップのウインドウだけをスイッチャーに表示します。ウインドウを選んでも別のデスクトップには移動しません。",
        shelfFileMissing: "ファイルはもう存在しません",
        monitorOpenActivityMonitor: "アクティビティモニタを開く",
        monitorMemoryMetricLabel: "メモリの測定方法",
        memoryMetricUsed: "使用中のメモリ",
        memoryMetricApp: "Appメモリ",
        keepAwakeRightClickToggle: "メニューバーアイコンの右クリックでスリープ防止を切り替える",
        keepAwakeRightClickToggleCaption: "右クリックのコンテキストメニューを置き換えます。",
        urlCleanerRulesTitle: "クリーンのルール",
        urlCleanerRulesCaption: "サイトが自身の共有リンクに付ける、どこから来たリンクかを追跡するためのパラメータです。チェックを入れた名前はリンクの整理時に削除され、外すと残ります。自分で追加した名前は削除できます。",
        urlCleanerRulesCoverageCaption: "一覧はサイトごとの共有経路（ウェブページ、アプリ、ライブルーム）をまとめて扱うため長くなります。実際のリンクが持つのは通常 2〜4 個です。",
        urlCleanerRulesAllSites: "すべてのサイト",
        urlCleanerRulesAddSite: "サイトを追加",
        urlCleanerRulesParameterPlaceholder: "パラメータ名",
        urlCleanerRulesMatchCaption: "= の左側の名前を入力します（例：utm_source）。一致した名前はそのパラメータだけをリンクから取り除き、ほかはそのまま残します。",
        urlCleanerRulesAddButton: "追加",
        urlCleanerRemovedFormat: "%@ を削除しました",
        switcherSearchPin: "S で検索欄を固定",
        switcherSearchPinCaption: "S を押すと検索を開始して切り替え画面を固定表示にします。ショートカットが ⌥ を使う場合の特殊文字入力も、Q や W で始める検索によるウインドウを閉じる/アプリを終了する誤動作も防げます。",
        invertVerticalScroll: "縦スクロールを反転",
        invertHorizontalScroll: "横スクロールを反転",
        switcherShowShortcutHints: "ショートカットのヒントを表示",
        switcherShowShortcutHintsCaption: "アイコンの下にアプリとウインドウのショートカットを表示します。",
        uninstallerHomebrewPackageFormat: "%@ も Homebrew から削除されます。",
        shelfEdgeToggle: "画面の端に近づけたら開く",
        shelfEdgeCaption: "ファイルを画面の端に向けてドラッグすると、シェルフが少しだけ現れます。そこでドロップするか、手を戻すとシェルフは引っ込みます。",
        focusFollowsMouseName: "マウス追従フォーカス",
        focusFollowsMouseCaption: "短い停止後、ポインタの下にあるウインドウをフォーカスして手前に表示します。",
        focusFollowsMouseDelay: "ホバー遅延",
        switcherMinimizedPlacementLabel: "最小化されたウインドウ",
        switcherMinimizedPlacementNormal: "通常の順序",
        switcherMinimizedPlacementEnd: "最後に配置",
        switcherMinimizedPlacementHidden: "非表示",
        switcherShowFullscreenWindows: "フルスクリーンのウインドウを表示",
        switcherScreenPlacementLabel: "表示先",
        switcherScreenPlacementPointer: "ポインタのある画面",
        switcherScreenPlacementMenuBar: "メニューバーのある画面",
        switcherScreenPlacementActiveWindow: "アクティブなウインドウのある画面",
        switcherScreenPlacementCaption: "複数の画面を接続しているとき、スイッチャーをどの画面に表示するかを選びます。",
        smoothScrollResponseLabel: "反応",
        mouseAccelerationName: "マウス加速を無効にする",
        mouseAccelerationCaption: "接続したマウスのポインタ加速を無効にします。オフにするか \(AppInfo.name) を終了すると以前の設定に戻ります。",
        shelfClearOnClose: "閉じるときに項目を消去",
        shelfClearOnCloseCaption: "閉じるボタンをクリックしたときだけシェルフを空にします。自動的に隠れた場合や折りたたんだ場合は項目を保持します。"
    )
}
