// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Español — translated and hand-checked, not machine output.
extension Strings {
    static let es = Strings(
        statusIdleTooltip: "\(AppInfo.name): reposo normal",
        statusActiveUntil: "\(AppInfo.name): activo hasta",
        statusActiveIndefinite: "\(AppInfo.name): activo indefinidamente",
        menuEnableAwake: "Activar mantener activo",
        menuDisableAwake: "Desactivar mantener activo",
        menuActivateFor: "Activar durante…",
        menuSettings: "Ajustes…",
        menuAbout: "Acerca de \(AppInfo.name)",
        menuQuit: "Salir de \(AppInfo.name)",
        menuHide: "Ocultar \(AppInfo.name)",
        menuHideOthers: "Ocultar los demás",
        menuShowAll: "Mostrar todo",
        menuEdit: "Edición",
        menuUndo: "Deshacer",
        menuRedo: "Rehacer",
        actionClear: "Borrar",
        actionRemove: "Quitar",
        actionBack: "Atrás",
        actionSearch: "Buscar",
        actionMute: "Silenciar",
        actionUnmute: "Reactivar sonido",
        actionPlay: "Reproducir",
        actionPause: "Pausar",
        menuCut: "Cortar",
        menuCopy: "Copiar",
        menuPaste: "Pegar",
        menuSelectAll: "Seleccionar todo",
        menuWindow: "Ventana",
        menuMinimize: "Minimizar",
        menuZoom: "Zoom",
        menuClose: "Cerrar",

        minutes15: "15 minutos",
        minutes30: "30 minutos",
        hour1: "1 hora",
        hours2: "2 horas",
        hours4: "4 horas",
        hours8: "8 horas",
        indefinitely: "Indefinidamente",
        indefinite: "Indefinido",

        panelSettings: "Ajustes",
        panelQuit: "Salir",

        keepAwakeTitle: "Mantener activo",
        keepAwakeEndsIn: "Termina en",
        keepAwakeUntilDisabled: "Activo hasta que lo desactives",
        keepAwakeNormalRules: "El Mac sigue sus reglas de energía normales",
        keepAwakeOptions: "Opciones",
        keepAwakeMouseJiggle: "Mover ligeramente el cursor",
        keepAwakeMouseJiggleCaption: "Durante una sesión, mueve un poco el cursor en el intervalo elegido.",
        keepAwakeMouseJiggleInterval: "Intervalo",
        keepAwakeActiveIconLabel: "Icono activo",
        keepAwakeActiveIconVorssaint: "\(AppInfo.name)",
        keepAwakeActiveIconCoffee: "Café",
        keepAwakeActiveIconEye: "Ojo",
        keepAwakeActiveIconMoon: "Luna",
        keepAwakeActiveIconLight: "Bombilla",
        keepAwakeIconTintLabel: "Color del icono activo",
        keepAwakeIconTintOrange: "Naranja",
        keepAwakeIconTintGreen: "Verde",
        keepAwakeIconTintBlue: "Azul",
        keepAwakeIconTintPurple: "Morado",
        keepAwakeIconTintPink: "Rosa",
        keepAwakeIconTintNone: "Sin color",
        durationLabel: "Duración",
        clamshellTitle: "Seguir con la tapa cerrada",
        clamshellOnCaption: "Reposo totalmente desactivado. Cuida la energía",
        clamshellNeedsSession: "Se aplica siempre que “Mantener activo” esté activo",
        clamshellReady: "Listo. Se alterna sin contraseña",
        clamshellNeedsPassword: "Pedirá la contraseña de administrador una vez",

        systemSection: "Sistema",
        temperatures: "Temperaturas",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batería",
        usageSection: "Uso del hardware",
        memorySection: "Memoria",
        memoryPressure: "Presión",
        memorySwapUsed: "Swap usado",
        memoryCompressed: "Comprimida",
        memoryCachedFiles: "Archivos en caché",
        pressureNormal: "Normal",
        pressureWarning: "Precaución",
        pressureCritical: "Crítica",
        monitorUnavailable: "Sensores no disponibles en este Mac",
        energyAppsTitle: "Uso significativo de energía",
        energyAppsIdle: "Sin uso significativo de energía",

        notifySessionEndedTitle: "Sesión finalizada",
        notifySessionEndedBody: "Se acabó el tiempo. El Mac volverá a entrar en reposo con normalidad.",
        notifyBatteryTitle: "\(AppInfo.name) desactivado",
        notifyBatteryBody: "Batería baja. Se restauró el reposo normal para proteger la carga.",
        adminPromptClamshellOff: "\(AppInfo.name) necesita tu contraseña para restaurar el reposo normal del Mac.",
        adminPromptRecover: "\(AppInfo.name) se cerró mientras el reposo del Mac estaba desactivado. Introduce la contraseña para restaurar el reposo normal.",
        adminPromptUpdate: "\(AppInfo.name) necesita tu contraseña para instalar la actualización.",
        adminPromptSudoersInstall: "\(AppInfo.name) creará una regla restringida (solo pmset disablesleep) para alternar el modo de tapa cerrada sin pedir contraseña. Esta es la única vez que se necesita la contraseña.",
        adminPromptSudoersRemove: "\(AppInfo.name) eliminará la regla de tapa cerrada sin contraseña.",

        settingsTitle: "Ajustes de \(AppInfo.name)",
        tabGeneral: "General",
        tabMouse: "Ratón",
        tabDock: "Dock",
        tabWindowBehavior: "Comportamiento de ventanas",
        tabKeyboard: "Teclado",
        tabTrackpad: "Trackpad",
        tabAdvanced: "Avanzado",
        tabAbout: "Acerca de",
        tabReleaseNotes: "Novedades",
        advancedResetSection: "Permisos",
        advancedResetDescription: "Elimina todos los permisos que concediste a \(AppInfo.name) (Accesibilidad, Grabación de pantalla, Acceso total al disco y otros), el ítem de inicio de sesión y la regla de tapa cerrada. Útil para empezar de cero o antes de desinstalar. La app sigue instalada.",
        advancedClearButton: "Borrar todos los permisos",
        advancedCleared: "Permisos borrados.",
        advancedClearConfirmTitle: "¿Borrar todos los permisos?",
        advancedClearConfirmBody: "Las funciones que necesitan permisos dejarán de funcionar hasta que los concedas de nuevo. Tus ajustes se conservan.",
        advancedUninstallSection: "Desinstalar",
        advancedUninstallDescription: "Intenta quitar los permisos de esta app, su ítem de inicio y la regla sin contraseña para el modo con la tapa cerrada, y borrar sus ajustes y datos locales. Tras cerrarse, intenta mover la app a la Papelera. No se borran las copias de seguridad ni las exportaciones guardadas por separado.",
        advancedUninstallButton: "Desinstalar \(AppInfo.name) por completo",
        advancedUninstallConfirmTitle: "¿Desinstalar \(AppInfo.name)?",
        advancedUninstallConfirmBody: "\(AppInfo.name) borrará sus permisos, eliminará sus preferencias y se moverá a la Papelera; después se cerrará. Esto no se puede deshacer desde la app, pero permanece en la Papelera hasta que la vacíes.",
        advancedUninstallFailedTitle: "La desinstalación se detuvo",
        advancedUninstallFailedBody: "\(AppInfo.name) no pudo restaurar un ajuste del sistema que había cambiado: la suspensión, la velocidad de los ventiladores o la aceleración del ratón. No se eliminó nada. Inténtalo de nuevo y permite la solicitud de contraseña si aparece.",

        launchAtLogin: "Abrir al iniciar sesión",
        languageLabel: "Idioma",
        showCountdown: "Mostrar el tiempo restante junto al icono",
        hotkeyToggle: "Activar atajo para “Mantener activo”",
        hotkeyCaption: "Funciona en cualquier app, sin permisos adicionales.",

        sessionSection: "Sesión",
        defaultDurationLabel: "Duración predeterminada",
        keepAwakeAutoStart: "Mantener activo al abrir \(AppInfo.name)",
        keepAwakeAutoStartCaption: "Inicia una sesión con la duración predeterminada.",
        batteryProtectionSection: "Protección de la batería",
        batteryDisableBelow: "Desactivar cuando la batería baje de",
        batteryNever: "Nunca",
        batteryProtectionCaption: "Evita que una sesión olvidada agote la batería del MacBook.",
        clamshellSection: "Tapa cerrada",
        configuring: "Configurando…",
        sudoersFailed: "No se pudo activar el modo de tapa cerrada. Inténtalo de nuevo.",
        clamshellExplanation: "“Seguir con la tapa cerrada” desactiva por completo el reposo mientras “Mantener activo” está activo y se revierte automáticamente cuando la sesión termina o la app se cierra. Es preferible usarlo conectado a la corriente.",

        scrollSection: "Desplazamiento",
        invertMouseScroll: "Invertir el desplazamiento del ratón",
        invertMouseScrollCaption: "Invierte la dirección de la rueda del ratón.",
        scrollTrackpadNote: "El trackpad no se modifica: mantiene el desplazamiento natural de macOS.",
        scrollActiveNow: "Invirtiendo el desplazamiento del ratón ahora",
        mouseNavigationActiveNow: "Botones laterales activos ahora",
        smoothScrollName: "Desplazamiento suave",
        smoothScrollCaption: "Convierte cada paso de la rueda del ratón en un deslizamiento corto y suave. El trackpad no cambia.",
        smoothScrollStepLabel: "Velocidad de desplazamiento",
        mouseNavigationEnable: "Usar los botones laterales para Atrás y Adelante",
        mouseNavigationCaption: "Convierte los botones Atrás y Adelante del ratón en comandos de navegación para Finder, navegadores y apps compatibles.",
        middleClickSection: "Clic central",
        middleClickEnable: "El clic con tres dedos actúa como clic central",
        middleClickEnableCaption: "Presionar el trackpad con tres dedos funciona como el clic de la rueda del ratón: abrir enlaces en una pestaña nueva, cerrar pestañas y todo lo demás que hace el botón central.",
        middleClickDragConflict: "El arrastre con tres dedos de macOS está activado y usa este mismo gesto. Desactívalo en Ajustes del Sistema, en Accesibilidad, Control del puntero, Opciones del trackpad, y el clic central funcionará.",
        middleClickTapPicker: "Un toque ligero también hace clic",
        middleClickTapOff: "Desactivado",
        middleClickTapThreeFingers: "3 dedos",
        middleClickTapFourFingers: "4 dedos",
        middleClickTapCaption: "Un toque ligero con ese número de dedos, sin presionar, también dispara el clic central. Deslizar nunca cuenta. Si el toque con tres dedos de macOS está asignado a Consultar, desactívalo para que no se disparen juntos.",
        quickToolShortcutToggle: "Atajo global",
        ocrName: "Copiar texto de la pantalla",
        ocrCaption: "Selecciona un área de la pantalla y el texto reconocido se copia, listo para pegar.",
        ocrCopied: "Texto copiado",
        ocrNoText: "No se encontró texto",
        colorPickerName: "Cuentagotas de color",
        colorPickerCaption: "Captura el color de cualquier píxel de la pantalla y cópialo en tu formato preferido.",
        colorPickerFormatLabel: "Formato copiado",
        colorPickerBareHexToggle: "Copiar sin el prefijo #",
        colorPickerPickNow: "Capturar color",
        pastePlainName: "Pegar como texto sin formato",
        pastePlainCaption: "Pega lo copiado sin colores, fuentes ni formato. El original se mantiene en el portapapeles.",
        switcherSection: "Selector de apps",
        switcherEnable: "Usar el selector de \(AppInfo.name)",
        switcherEnableCaption: "Cambia entre apps y ventanas, incluidas las minimizadas y varias ventanas de la misma app.",
        switcherNoWindows: "No hay ventanas abiertas",
        appQuitFailedFormat: "No se pudo solicitar el cierre de %@.",
        switcherIconRowMode: "Mostrar %@ con iconos grandes",
        switcherIconRowModeCaption: "Muestra un icono por app con las vistas previas de sus ventanas arriba.",
        switcherSimpleMode: "Selector de apps sencillo",
        switcherSimpleModeCaption: "Muestra iconos de apps y títulos de ventanas, sin vistas previas ni captura de pantalla por el selector.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Ventanas",
        switcherWindowShortcutCaption: "Abre un selector de las ventanas de la app en primer plano. Con el selector de apps abierto, salta entre las ventanas de la app seleccionada.",
        switcherTakeOverSystemShortcuts: "Reemplazar ⌘Tab y ⌘` de macOS",
        switcherTakeOverSystemShortcutsCaption: "Desactiva los atajos correspondientes de macOS solo mientras el selector de \(AppInfo.name) está activo. Todas las apps abiertas siguen accesibles.",
        switcherAppearanceDelay: "Retardo de aparición",
        switcherAppearanceDelayCaption: "Cuánto tiempo debe mantenerse pulsado el atajo antes de que aparezca el selector.",
        switcherMergeTabs: "Mostrar una entrada por app",
        switcherMergeTabsCaption: "Agrupa todas las ventanas de una app en una sola entrada del selector, en vez de una por ventana.",
        switcherWindowlessApps: "Apps sin ventanas abiertas",
        switcherWindowlessAppsCaption: "Elige qué apps abiertas sin ninguna ventana aparecen en el selector.",
        switcherWindowlessAppsOff: "No mostrar",
        switcherWindowlessAppsFinder: "Solo Finder",
        switcherWindowlessAppsAll: "Todas las apps",
        switcherNoOpenWindow: "Sin ventanas abiertas",
        switcherOtherDesktop: "Otro escritorio",

        cutPasteName: "Cortar y pegar",
        cutPasteEnable: "Cortar y pegar archivos en el Finder",
        cutPasteEnableCaption: "Usa ⌘X para cortar y ⌘V para mover archivos y carpetas en el Finder.",
        cutPasteShowHUD: "Mostrar panel flotante",
        cutPasteShowHUDCaption: "Muestra un indicador flotante con los archivos cortados mientras el Finder está activo.",
        cutPasteHowTitle: "Cómo se usa",
        cutPasteStep1: "Selecciona ítems en el Finder y pulsa ⌘X para cortarlos.",
        cutPasteStep2: "Abre la carpeta de destino y pulsa ⌘V para moverlos allí.",
        cutPasteTextNote: "En los campos de texto (como al renombrar), ⌘X y ⌘V siguen funcionando con normalidad.",
        cutPasteActiveNow: "Listo para cortar en el Finder",
        cutPasteAutomationNote: "La primera vez, macOS pide permiso para controlar el Finder.",
        cutReadyTitle: "Cortado",
        cutReadyHint: "en la carpeta de destino para mover",
        cutCancel: "Cancelar corte",
        cutDoneTitle: "¡Movido!",
        cutMovedSingular: "1 ítem movido",
        cutMovedPluralFormat: "%d ítems movidos",
        cutSomeFailed: "Algunos ítems no se pudieron mover",
        cutMovingTitle: "Moviendo…",
        cutMovingCountFormat: "%d de %d",

        autoQuitName: "Salir al cerrar",
        autoQuitEnable: "Salir de una app al cerrar su última ventana",
        autoQuitEnableCaption: "Cerrar la última ventana de una app también la cierra.",
        autoQuitActiveNow: "Activo ahora",
        autoQuitStep1: "Cierra la última ventana de una app (⌘W o el botón rojo).",
        autoQuitStep2: "La app se cierra sola. Los diálogos “¿Guardar cambios?” siguen apareciendo.",
        autoQuitPredictableNote: "Las apps que normalmente funcionan sin ventana nunca se cierran.",
        autoQuitExceptionsTitle: "Excepciones",
        autoQuitExceptionsCaption: "Las apps de esta lista permanecen abiertas aunque no tengan ventanas.",
        autoQuitExceptionsEmpty: "Sin excepciones",
        autoQuitAddApp: "Añadir app…",

        uninstallerName: "Desinstalador",
        uninstallerEnableCaption: "Elimina una app junto con las cachés, preferencias, registros y restos que deja atrás.",
        uninstallerMenuItem: "Desinstalar una app…",
        uninstallerDropTitle: "Arrastra una app aquí",
        uninstallerDropSubtitle: "o elige una para analizar",
        uninstallerChoose: "Elegir app…",
        uninstallerPickerTitle: "Elegir app",
        uninstallerPickerSearch: "Buscar apps",
        uninstallerPickerEmpty: "No se encontraron apps",
        uninstallerEmptyNote: "No se elimina nada sin tu confirmación.",
        uninstallerFDANote: "Concede Acceso total al disco para un análisis más exhaustivo.",
        uninstallerFDAGrant: "Conceder acceso…",
        uninstallerFDAHint: "Activa \(AppInfo.name) en la lista. Si no aparece, haz clic en + y elige \(AppInfo.name) en Aplicaciones. El acceso solo se aplica después de volver a abrir la app.",
        uninstallerFDARelaunch: "Reabrir ahora",
        uninstallerScanning: "Analizando archivos…",
        uninstallerRemoving: "Moviendo a la Papelera…",
        uninstallerFoundTitle: "encontrado",
        uninstallerSelectedFormat: "%d de %d seleccionados",
        uninstallerRemove: "Mover a la Papelera",
        uninstallerCancel: "Cancelar",
        uninstallerDoneTitle: "¡Listo!",
        uninstallerFreedFormat: "Datos eliminados: %@",
        uninstallerSomeFailed: "Algunos ítems no se pudieron mover a la Papelera.",
        uninstallerConfirmationExpired: "Esta confirmación ya no es válida. Revisa los elementos actuales y confirma de nuevo.",
        uninstallerFailedNeedsFDA: "Los datos de apps en zona protegida solo se pueden mover con Acceso total al disco. La contraseña de administrador no lo sustituye.",
        uninstallerFailedMoreFormat: "y %d más",
        uninstallerAnother: "Desinstalar otra",
        uninstallerCatApp: "Aplicación",
        uninstallerCatSupport: "Soporte",
        uninstallerCatCaches: "Cachés",
        uninstallerCatPreferences: "Preferencias",
        uninstallerCatContainers: "Contenedores",
        uninstallerCatLogs: "Registros",
        uninstallerCatState: "Estado guardado",
        uninstallerCatOther: "Otros",

        urlCleanerName: "Limpiar URL",
        urlCleanerEnable: "Limpiar URL automáticamente al copiarlas",
        urlCleanerEnableCaption: "Elimina los parámetros de rastreo de un enlace en cuanto llega al portapapeles.",
        urlCleanerActiveNow: "Activo ahora",
        urlCleanerManualTitle: "Limpiar ahora",
        urlCleanerInputPlaceholder: "Pega una URL",
        urlCleanerOutputPlaceholder: "La URL limpia aparece aquí",
        urlCleanerCleanButton: "Limpiar",
        urlCleanerPasteButton: "Pegar",
        urlCleanerCopyButton: "Copiar",
        urlCleanerClearButton: "Limpiar campo",
        urlCleanerNoURL: "Pega una URL válida.",
        urlCleanerNoChange: "Nada que limpiar.",
        urlCleanerCleaned: "URL limpia.",
        urlCleanerCopied: "Copiado.",
        urlCleanerLocalNote: "Local. Sin red.",

        homebrewName: "Homebrew",
        homebrewMissingTitle: "No se encontró Homebrew",
        homebrewMissingBody: "Homebrew no está instalado. Cuando lo esté, los paquetes que gestiona aparecerán aquí.",
        homebrewRequested: "Instalados por ti",
        homebrewMasApps: "App Store",
        homebrewCopyName: "Copiar nombre",
        homebrewTrustTitle: "Tap aún no es de confianza",
        homebrewTrustCaption: "Homebrew ahora pide tu confirmación antes de usar taps de terceros. Confía en %@ para continuar.",
        homebrewTrustButton: "Confiar y continuar",
        homebrewNoPackages: "No se encontraron paquetes",
        homebrewUninstall: "Desinstalar",
        homebrewUpgrade: "Actualizar",
        homebrewPinnedVersion: "Versión fijada",
        homebrewAllPackages: "paquetes",
        homebrewOpenTerminal: "Abrir Terminal",
        homebrewCancelOperation: "Cancelar",
        homebrewClearLog: "Borrar registro",
        homebrewHomepage: "Abrir sitio web",
        homebrewUpdateAvailableBadge: "Actualización disponible",
        homebrewConfirmUninstallTitle: "¿Desinstalar con Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew desinstalará %@. Los archivos de configuración pueden permanecer en el sistema.",
        homebrewConfirmUpgradeTitle: "¿Actualizar con Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew descargará y aplicará la versión más reciente de %@. También puede actualizar dependencias.",
        homebrewTerminalFallback: "Esta operación necesita Terminal para pedir la contraseña de administrador. \(AppInfo.name) no captura contraseñas.",
        homebrewLoading: "Cargando…",
        homebrewOperationUninstallFormat: "Desinstalando %@",
        homebrewOperationUpgradeFormat: "Actualizando %@",
        homebrewOperationUpdateHomebrew: "Actualizando Homebrew",
        homebrewOperationUninstalledFormat: "%@ desinstalado.",
        homebrewOperationUpgradedFormat: "%@ actualizado.",
        homebrewOperationUpdatedHomebrew: "Homebrew actualizado.",
        homebrewOperationFailedFormat: "No se pudo completar %@.",
        homebrewOperationCancelled: "Operación cancelada.",
        homebrewOperationPreparing: "Preparando…",
        homebrewOperationDownloading: "Descargando archivos…",
        homebrewOperationUninstalling: "Eliminando archivos…",
        homebrewOperationUpgrading: "Actualizando archivos…",
        homebrewOperationFinalizing: "Finalizando…",
        homebrewOperationRefreshing: "Actualizando lista…",
        homebrewOperationTerminal: "Continúa en Terminal.",
        homebrewOperationElapsedFormat: "%@ transcurridos",
        homebrewOperationShowDetails: "Mostrar detalles",
        homebrewOperationHideDetails: "Ocultar detalles",
        homebrewOperationTechnicalLog: "Detalles técnicos",
        homebrewOperationProgressUnknown: "Homebrew aún no informó un porcentaje.",

        mediaName: "Media",
        mediaEnableCaption: "Comprime videos, convierte y procesa imágenes, crea GIFs y extrae texto localmente.",
        mediaLocalNote: "Local. Sin red.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Imagen",
        mediaToolText: "Texto",
        mediaSelectFile: "Elegir archivo",
        mediaDropHint: "Arrastra un archivo aquí o haz clic para elegir.",
        mediaOutput: "Salida",
        mediaOutputAutomatic: "Automática",
        mediaChooseOutput: "Destino",
        mediaStartVideo: "Comprimir video",
        mediaStartGIF: "Crear GIF",
        mediaStartImage: "Procesar imagen",
        mediaStartConvertPDF: "Convertir a PDF",
        mediaStartText: "Extraer texto",
        mediaCancel: "Cancelar",
        mediaStartTime: "Inicio",
        mediaEndTime: "Fin",
        mediaQuality: "Compresión",
        mediaCompressionLow: "Baja",
        mediaCompressionMedium: "Media",
        mediaCompressionHigh: "Alta",
        mediaMaxSize: "Tamaño",
        mediaSizingResolution: "Resolución",
        mediaSizingFileSize: "Tamaño del archivo",
        mediaTargetSize: "Tamaño objetivo",
        mediaTargetSizeHint: "La resolución se ajusta para no superar el límite.",
        mediaErrorTargetTooSmall: "Tamaño objetivo demasiado pequeño para este clip. Recórtalo o aumenta el límite.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Ancho",
        mediaFPS: "FPS",
        mediaFormat: "Formato",
        mediaStripMetadata: "Quitar metadatos",
        mediaLoopGIF: "Repetir GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Preciso",
        mediaOCRFast: "Rápido",
        mediaRunning: "Procesando",
        mediaCompleted: "Listo",
        mediaCancelled: "Cancelado.",
        mediaOpenInFinder: "Mostrar",
        mediaCopyText: "Copiar texto",
        mediaRunAgain: "Ejecutar otra vez",
        mediaEmptyText: "No se encontró texto.",
        mediaResultSavedFormat: "Guardado como %@",
        mediaResultSizeFormat: "%@ a %@",
        mediaResultGrewCaption: "El archivo convertido quedó más grande que el original.",
        mediaErrorNoFile: "Elige un archivo primero.",
        mediaErrorNoVideo: "Este archivo no tiene pista de video.",
        mediaErrorSameOutput: "Elige un destino distinto del archivo original.",
        mediaErrorUnsupported: "Formato no compatible con macOS.",

        shelfName: "Estante",
        shelfEnable: "Área temporal para arrastrar archivos",
        shelfEnableCaption: "Un espacio flotante para reunir archivos, imágenes y texto, y luego arrastrarlos a cualquier sitio.",
        shelfHowTitle: "Cómo se usa",
        shelfStep1: "Ábrelo con el atajo o agitando el ratón durante un arrastre.",
        shelfStep2: "Suelta sobre él archivos, imágenes, enlaces o texto para guardarlos.",
        shelfStep3: "Arrastra cada ítem de vuelta a cualquier app cuando lo necesites.",
        shelfShakeToggle: "Abrir agitando el ratón al arrastrar",
        shelfShakeCaption: "Agita el puntero rápidamente mientras sostienes un ítem para que aparezca cerca del cursor.",
        shelfDropZoneToggle: "Mantener en la barra de menús los archivos arrastrados",
        shelfDropZoneCaption: "Mientras arrastras un archivo, el estante aparece debajo del icono de la barra de menús. Lo que sueltes se guarda ahí mismo, en un botón que contraes y abres con un clic y que desaparece cuando el estante se vacía.",
        shelfCollapse: "Contraer",
        shelfBehaviorTitle: "Después de usar",
        shelfCloseAfterDrop: "Cerrar después de soltar en otra app",
        shelfCloseAfterDropCaption: "Cierra el estante cuando el destino acepta los ítems. El alfiler del panel lo mantiene abierto.",
        shelfRemoveAfterDrop: "Quitar ítems después de soltarlos",
        shelfRemoveAfterDropCaption: "Los ítems aceptados por otra app salen del estante. Desactívalo para conservar una copia.",
        shelfExclusionsTitle: "Excepciones automáticas",
        shelfExclusionsEmpty: "No se añadieron apps.",
        shelfExclusionsCaption: "Agitar y la zona de la barra de menús no se activan en arrastres iniciados en estas apps. El atajo y Abrir ahora siguen funcionando.",
        shelfPin: "Mantener abierto",
        shelfUnpin: "Permitir cerrar después de usar",
        shelfHotkeyLabel: "Atajo",
        shelfOpenNow: "Abrir ahora",
        shelfNoPermission: "No requiere ningún permiso.",
        shelfMenuItem: "Abrir el estante",
        shelfTitle: "Estante",
        shelfEmpty: "Arrastra ítems aquí",
        shelfClearAll: "Borrar todo",
        shelfRemoveSelected: "Quitar seleccionados",
        shelfSelectedFormat: "%d seleccionados",
        shelfHint: "Haz clic para seleccionar. Arrastra para usar o haz clic derecho para ver más acciones.",
        shelfItemImage: "Imagen",
        shelfTooltipItemsFormat: "%d elementos",
        shelfTooltipItemsFew: "%d elementos",
        shelfTooltipImageSingular: "%d imagen",
        shelfTooltipImageFew: "%d imágenes",
        shelfTooltipImagePlural: "%d imágenes",
        shelfTooltipFileSingular: "%d archivo",
        shelfTooltipFileFew: "%d archivos",
        shelfTooltipFilePlural: "%d archivos",
        shelfTooltipNoteSingular: "%d nota",
        shelfTooltipNoteFew: "%d notas",
        shelfTooltipNotePlural: "%d notas",
        shelfTooltipLinkSingular: "%d enlace",
        shelfTooltipLinkFew: "%d enlaces",
        shelfTooltipLinkPlural: "%d enlaces",
        shelfActionOpen: "Abrir",
        shelfActionOpenWith: "Abrir con",
        shelfActionShare: "Compartir",

        breakdownMeasuring: "Midiendo…",

        preciseVolumeRollerEnable: "Usar pasos de volumen más finos",
        preciseVolumeRollerCaption: "Convierte ruedas y teclas de volumen en pasos más pequeños del sistema.",
        preciseVolumeRollerTapFailed: "No se pudo escuchar las teclas de volumen.",

        updatesSection: "Actualizaciones",
        autoCheckToggle: "Buscar actualizaciones automáticamente",
        betaBadgeLabel: "Beta",
        checkNowButton: "Buscar ahora",
        updateChecking: "Buscando…",
        updateUpToDate: "Tienes la última versión.",
        updateAvailablePrefix: "Actualización disponible:",
        updateInstallButton: "Descargar e instalar",
        updateDownloading: "Descargando la actualización…",
        updateInstalling: "Instalando y reiniciando…",
        updateFailedPrefix: "No se pudo comprobar:",
        updateLastChecked: "Última comprobación:",
        updateNotifyTitle: "Actualización de \(AppInfo.name)",
        updateInstallFailedBody: "La actualización se descargó pero no se pudo aplicar. Descarga la última versión desde la página de releases de GitHub y arrastra la app sobre la actual.",
        updateNeedsApplicationsTitle: "Mueve \(AppInfo.name) a Aplicaciones",
        updateNeedsApplicationsBody: "La app se está ejecutando desde un lugar que no se puede actualizar, como la imagen de disco o una ubicación temporal del sistema. Arrastra \(AppInfo.name) a la carpeta Aplicaciones, ábrela desde ahí y vuelve a intentarlo.",
        menuCheckUpdates: "Buscar actualizaciones…",

        permissionRequired: "Permiso necesario",
        permissionAccessibility: "Accesibilidad",
        permissionScreenRecording: "Grabación de pantalla",
        permissionGranted: "Concedido",
        permissionMissing: "No concedido",
        permissionOpenSettings: "Abrir Ajustes del Sistema…",
        permissionRequest: "Conceder acceso",
        permissionRestartNote: "macOS puede pedir que vuelvas a abrir la app tras concederlo.",

        aboutDescription: "Un centro de utilidades para tu Mac.\nEnergía, monitor del sistema, desplazamiento y un selector de ventanas, directamente en la barra de menús.",
        versionPrefix: "Versión",
        reviewIntro: "Ver la introducción",
        reviewHighlights: "Ver novedades de la versión",
        viewOnGitHub: "Ver en GitHub",

        obContinue: "Continuar",
        obBack: "Atrás",
        obStart: "Abrir \(AppInfo.name)",
        obStepWelcomeTitle: "Te damos la bienvenida a \(AppInfo.name)",
        obStepWelcomeBody: "Una utilidad discreta en la barra de menús que hace que el día a día con macOS sea más práctico.",
        obWelcomeBullet1Title: "Energía bajo control",
        obWelcomeBullet1Body: "Mantén el Mac activo todo el tiempo que quieras, incluso con la tapa cerrada.",
        obWelcomeBullet2Title: "Una visión clara del sistema",
        obWelcomeBullet2Body: "Temperaturas de CPU, GPU y batería, uso del hardware y presión de memoria en tiempo real.",
        obWelcomeBullet3Title: "El ratón y las ventanas a tu manera",
        obWelcomeBullet3Body: "Desplazamiento invertido del ratón y un selector de ventanas con miniaturas.",
        obLanguageLabel: "Idioma",
        obStepDoneTitle: "¡Todo listo!",
        obStepDoneBody: "\(AppInfo.name) ya está cuidando de tu Mac.",
        obDoneHint: "Busca el icono del pulpo en la barra de menús, en la esquina superior derecha de la pantalla.",
        obWhatsNewTitle: "Novedades de esta versión",
        obWhatsNewFallback: "Esta actualización incluye las correcciones y mejoras más recientes.",
        obPurposeTitle: "¿Qué te trae por aquí?",
        obPurposeBody: "Selecciona las funciones que quieras activar. Se conservan tus opciones actuales.",
        obPurposeSkip: "Puedes añadir o quitar funciones después en Ajustes.",

        tabMonitor: "Monitor",
        tabMenuBarIcon: "Icono de la barra de menús",
        tabMenuBarPanel: "Panel de la barra de menús",
        monitorMenuBarSection: "En la barra de menús",
        monitorMenuBarCaption: "Elige qué aparece junto al icono en la barra de menús.",
        monitorCombineTemperatures: "Combinar uso y temperatura",
        monitorCombineTemperaturesCaption: "Cuando el uso y la temperatura del mismo elemento estén activos, se muestran en un solo bloque.",
        monitorSeparateMenuBarMetrics: "Separar métricas en elementos propios",
        monitorSeparateMenuBarMetricsCaption: "Separa los bloques activos en la barra de menús y mantiene uso y temperatura juntos cuando combinar está activo.",
        monitorNetworkUploadFirst: "Subida encima de descarga",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Memoria",
        monitorShowNetwork: "Red",
        monitorShowPowerLabel: "Energía",
        monitorIntervalLabel: "Actualizar cada",
        monitorInterval1: "1 segundo",
        monitorInterval2: "2 segundos",
        monitorInterval5: "5 segundos",
        monitorPanelSection: "En el panel",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Puedes encontrar algunos errores.",

        networkSection: "Red",
        networkDownload: "Descarga",
        networkUpload: "Subida",
        networkThisSession: "En esta sesión",
        networkMeasuring: "Midiendo…",
        networkApps: "Apps usando red",
        networkAppsIdle: "Ninguna app usa la red ahora",

        diskSection: "Discos",
        diskUsed: "usado",
        diskAvailable: "disponible",
        diskPurgeable: "purgable",
        diskInternal: "Interno",
        diskExternal: "Externo",
        diskSelect: "Seleccionar disco",
        diskRead: "Lectura",
        diskWrite: "Escritura",
        diskSMARTStatus: "Estado",
        diskSMARTUnavailable: "SMART no disponible para este disco",
        diskTotalRead: "Total leído",
        diskTotalWritten: "Total escrito",
        diskTemperature: "Temperatura",
        diskHealth: "Salud",
        diskPowerCycles: "Ciclos",
        diskPowerOnHours: "Horas encendido",
        diskEject: "Expulsar",
        diskEjectAll: "Expulsar todos",
        diskEjecting: "Expulsando…",
        diskReadyToRemove: "Listo para retirar",
        diskEjectFailed: "No se pudo expulsar",
        diskProtectionCaption: "Expulsa antes de desconectar.",
        diskNoExternal: "No hay discos externos listos para expulsar.",
        diskOpenInFinder: "Abrir",
        diskStorageSettings: "Almacenamiento",
        diskNoDisks: "No se encontraron discos montados.",

        powerSection: "Energía",
        powerSystem: "Sistema",
        powerAdapter: "Adaptador",
        powerBattery: "Batería",
        powerCharging: "Cargando",
        powerOnBattery: "Con batería",
        powerPluggedIn: "Enchufado",
        powerUnavailable: "Métricas de energía no disponibles en este Mac",
        powerAdapterMaxFormat: "%@ máx.",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura de CPU",
        monitorShowGPUTemperature: "Temperatura de GPU",
        monitorShowBatteryTemperature: "Temperatura de batería",
        monitorShowPeripheralBattery: "Batería de periféricos",
        peripheralBatteryNoDevices: "No se encontraron periféricos",

        updateBannerTitle: "Actualización disponible",
        updateBannerAction: "Actualizar",
        menuBarSpacingLabel: "Espaciado en la barra",
        menuBarSpacingStandard: "Estándar",
        menuBarSpacingCompact: "Compacto",
        menuBarHideIconToggle: "Ocultar el icono de la app mientras se muestran métricas",
        menuBarHideIconCaption: "El icono vuelve solo cuando las métricas salen de la barra y cuando hay algo que avisar (una actualización lista o el micrófono silenciado).",
        monitorMemoryPressureDot: "Punto de presión",
        systemUptime: "Activo desde hace",
        batteryCharge: "Carga",
        powerHealth: "Salud de la batería",
        powerCycles: "Ciclos",
        speedTestRun: "Prueba de velocidad",
        speedTestAgain: "Probar de nuevo",
        speedTestLatency: "Latencia",
        speedTestTesting: "Probando…",
        speedTestFailed: "La prueba falló",

        monitorShowInPanel: "Mostrar en el panel",
        disclosureExpanded: "Expandido",
        disclosureCollapsed: "Contraído",
        panelHideItem: "Ocultar del panel",
        panelShowItem: "Mostrar en el panel",
        panelHiddenItem: "Oculto",
        monitorItemUptime: "Tiempo activo",
        monitorItemNetSpeed: "Velocidad en directo",
        monitorItemNetTotals: "Totales de la sesión",
        monitorItemNetTest: "Prueba de velocidad",
        monitorItemDiskUsage: "Uso del disco",
        monitorItemDiskActivity: "Actividad en directo",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protección externa",
        monitorItemDiskTools: "Herramientas",
        monitorOrderSection: "Orden de las secciones",
        monitorOrderHint: "Arrastra para reordenar las secciones del panel y usa el ojo para mostrar u ocultar cada una.",

        cleaningMenuItem: "Modo de limpieza",
        utilitiesSection: "Utilidades",
        quickControlsSection: "Controles",
        panelCategoryWindows: "Ventanas",
        panelCategoryInput: "Ratón y teclado",
        panelCategoryFiles: "Archivos",
        windowMaximizeName: "El botón verde maximiza la ventana",
        windowMaximizeCaption: "Haz clic en el botón verde de la esquina superior izquierda para ampliar la ventana en el escritorio actual, sin entrar en pantalla completa.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrar teclas duplicadas",
        keyDebounceCaption: "Filtra pulsaciones duplicadas muy rápidas.",
        keyDebounceActiveNow: "Filtro activo",
        keyDebounceGlobalWindow: "Ventana global",
        keyDebouncePerKeySection: "Teclas específicas",
        keyDebouncePerKeyCaption: "Los valores por tecla sustituyen la ventana global. Usa 0 ms para no filtrar una tecla.",
        keyDebounceKeyLabel: "Tecla",
        keyDebounceAddKey: "Añadir tecla",
        keyDebounceNoOverrides: "No hay teclas específicas configuradas.",
        keyDebounceRemoveKey: "Eliminar tecla",
        cleaningPanelCaption: "Bloquea el teclado para limpiar con seguridad.",
        cleaningOverlayTitle: "Teclado bloqueado para limpiar",
        cleaningOverlaySubtitle: "Pulsa Esc 5 veces para desbloquear",
        cleaningOverlayUnlock: "Desbloquear",
        cleaningOverlayMouseHint: "El ratón y el trackpad siguen funcionando",
        cleaningKeepScreenVisibleToggle: "Mantener la pantalla visible",
        cleaningKeepScreenVisibleCaption: "Muestra un indicador discreto en la esquina de la pantalla en lugar de oscurecer el contenido.",
        cleaningStartNow: "Bloquear el teclado ahora",
        cleaningNeedsAxTitle: "Se necesita Accesibilidad",
        cleaningNeedsAxBody: "Para bloquear el teclado de forma segura, \(AppInfo.name) necesita el permiso de Accesibilidad. Concédelo en Ajustes del Sistema e inténtalo de nuevo.",

        shortcutsPageCaption: "Edita aquí todos los atajos globales de las funciones instaladas en este Mac. Los inactivos se guardan, pero no se ejecutan.",
        shortcutsPageTitle: "Atajos de teclado",
        settingsSearchPlaceholder: "Buscar en ajustes",
        supportIntroLaterButton: "Ahora no",
        supportIntroDoneButton: "Listo",
        updateShowcaseTitle: "Novedades de 3.1.4",
        updateShowcaseMessage: "Mira una vista previa rápida de las principales mejoras de esta actualización.",
        updateShowcaseUnavailable: "No se pudo cargar el video ahora. Puedes continuar igualmente.",
        updateShowcaseRestart: "Volver al inicio",
        showMenuBarIcon: "Mostrar el icono en la barra de menús",
        showMenuBarIconCaption: "Si el icono de \(AppInfo.name) desaparece (macOS puede ocultar iconos de la barra de menús cuando se queda sin espacio, algo habitual en Macs con notch), vuelve a abrir \(AppInfo.name) desde Aplicaciones o Spotlight: eso recrea el icono y, si sigue oculto, abre esta ventana.",
        menuBarIconStillHiddenTitle: "El icono sigue oculto",
        menuBarIconStillHiddenBody: "El icono se recreó, pero macOS no le dio un lugar visible. Probablemente la barra de menús se quedó sin espacio: quita algunos iconos de la barra (o cierra apps con menús largos) y vuelve a intentarlo.",
        menuBarIconManagerHintFormat: "%@ está abierto y puede estar guardando el icono en su sección oculta. Busca \(AppInfo.name) ahí, o configura %@ para mostrar siempre \(AppInfo.name).",
        shortcutRecording: "Pulsa el nuevo atajo",
        shortcutReset: "Restablecer",
        shortcutNone: "Ninguno",
        shortcutClear: "Eliminar atajo",
        shortcutInvalid: "Usa al menos Control, Option o Command junto con una tecla.",
        shortcutPressKeys: "Pulsa teclas",
        shortcutEscapeHint: "Esc cancela.",
        shortcutDeleteHint: "Delete lo elimina.",
        shortcutNotCaptured: "No se capturó nada. macOS u otra app ya usa esa combinación. Prueba con otra.",
        shortcutConflictFormat: "Este atajo ya lo usa %@.",
        shortcutUnavailable: "macOS rechazó este atajo. Elige otro.",
        shelfShortcutToggle: "Atajo del estante",
        switcherUsageHintFormat: "Mantén %@ para navegar; suelta para activar la ventana. Mayúsculas o ← retrocede; W cierra la ventana; Q cierra la app; Esc cancela.",
        cleanerName: "Limpieza",
        cleanerIntroTitle: "Limpia la basura del Mac",
        cleanerIntroCaption: "Busca restos de apps desinstaladas, cachés, registros y la Papelera. Revisas todo antes y lo eliminado va a la Papelera.",
        cleanerScan: "Analizar",
        cleanerScanning: "Analizando…",
        cleanerCleaning: "Limpiando…",
        cleanerCatLeftovers: "Restos de apps desinstaladas",
        cleanerCatLoginItems: "Ítems de inicio huérfanos",
        cleanerCatCaches: "Cachés",
        cleanerCatLogs: "Registros",
        cleanerCatDeveloper: "Basura de desarrollo",
        cleanerCatTrash: "Papelera",
        cleanerLeftoversNote: "Encontrados por análisis y sin marcar. Revisa la ruta antes de marcar.",
        cleanerLoginItemsNote: "La entrada en Ítems de inicio desaparece tras reiniciar el Mac.",
        cleanerTrashNote: "Vaciar la Papelera es permanente.",
        cleanerCatDeviceBackups: "Copias de iPhone",
        cleanerDeviceBackupsCaption: "Las copias antiguas de iPhone y iPad ocupan gran parte de lo que macOS llama Otros. Elimina solo las que ya no necesites; al conectar el aparato se crea una nueva.",
        cleanerNothingFound: "Nada que limpiar. Tu Mac está en orden.",
        cleanerIncompleteTitle: "Limpieza incompleta",
        cleanerFailedNote: "No se pudieron limpiar estos ítems. Vuelve a analizar para revisar los que quedan.",
        cleanerDoneNote: "Los ítems fueron a la Papelera y pueden recuperarse desde ahí.",
        cleanerAgain: "Analizar de nuevo",
        cleanerRevealInFinder: "Mostrar en Finder",
        cleanerPanelCaption: "Restos de apps, cachés y registros",
        cleanerSafeSection: "Limpieza segura",
        cleanerOptionalSection: "Opcional, revisa antes",
        cleanerCatOtherCaches: "Otras cachés",
        cleanerCachesCaption: "Archivos temporales que las apps rehacen solas.",
        cleanerLogsCaption: "Registros antiguos de diagnóstico.",
        cleanerDeveloperCaption: "Restos de compilaciones y simuladores de Xcode.",
        cleanerLoginItemsCaption: "Entradas de inicio dejadas por apps que ya no existen.",
        cleanerLeftoversCaption: "Archivos dejados por apps que desinstalaste.",
        cleanerOtherCachesCaption: "Seguro de borrar, nada se rompe. Las apps pueden abrir más lento una vez y el contenido descargado, como música offline, se descarga de nuevo.",
        cleanerCleanSizeFormat: "Limpiar %@",
        cleanerScheduleTitle: "Limpieza automática",
        cleanerScheduleOff: "Desactivada",
        cleanerScheduleDaily: "Diaria",
        cleanerScheduleWeekly: "Semanal",
        cleanerScheduleCaption: "Limpia sola solo la parte segura a la hora elegida y envía todo a la Papelera.",
        cleanerAutoNotificationFormat: "%@ liberados y enviados a la Papelera.",
        cleanerScheduleNextFormat: "Próxima limpieza %@.",
        cleanerScheduleNotifyToggle: "Avisar al terminar",
        cleanerNotifDenied: "Las notificaciones de \(AppInfo.name) están desactivadas en el sistema.",
        cleanerNotifOpenSettings: "Abrir ajustes de notificaciones…",
        launchAtLoginNeedsApplications: "La app se está ejecutando desde un lugar que no permite abrirse al iniciar sesión. Arrastra \(AppInfo.name) a la carpeta Aplicaciones, ábrelo desde ahí y actívalo de nuevo.",
        launchAtLoginNeedsApproval: "El ítem de inicio está registrado, pero sigue desactivado en Ajustes del Sistema. Abre Ajustes del Sistema › General › Ítems de inicio y extensiones y activa \(AppInfo.name) en “Abrir al iniciar sesión”.",
        ocrRemoveLineBreaksToggle: "Eliminar saltos de línea",
        ocrRemoveLineBreaksCaption: "Elimina los saltos de línea para que el texto copiado se pegue como un solo párrafo.",
        ocrQRToggle: "Leer códigos QR",
        ocrQRCaption: "Si el área tiene un código QR, se muestra su contenido para copiar o abrir.",
        ocrQRCopied: "Código QR copiado",
        qrResultTitle: "Código QR",
        qrResultCopy: "Copiar",
        qrResultOpen: "Abrir enlace",
        highlightsTitle: "Novedades de esta versión",
        highlightsTitleQuitProtection: "Protección de ⌘Q y ⌘W",
        highlightsTitleRecorderBlur: "Desenfoque en grabaciones",
        highlightsCaptionQuitProtection: "Evite cerrar apps o ventanas por error manteniendo presionada la tecla, pulsando dos veces o con un modificador extra, configurable por app.",
        highlightsCaptionRecorderBlur: "Oculte datos confidenciales, contraseñas y detalles privados en cualquier tramo de su video grabado antes de guardarlo o compartirlo.",
        highlightsConfigure: "Configurar",
        highlightsSeeAll: "Ver todos los cambios",
        switcherCurrentSpaceOnly: "Mostrar solo el escritorio actual",
        switcherCurrentSpaceOnlyCaption: "Muestra en el selector solo las ventanas del escritorio en el que estás. Elegir una ventana nunca te lleva a otro escritorio.",
        shelfFileMissing: "El archivo ya no existe",
        monitorOpenActivityMonitor: "Abrir Monitor de Actividad",
        monitorMemoryMetricLabel: "Medir memoria como",
        memoryMetricUsed: "Memoria usada",
        memoryMetricApp: "Memoria de apps",
        keepAwakeRightClickToggle: "Haz clic derecho en el icono de la barra de menús para activar o desactivar “Mantener activo”",
        keepAwakeRightClickToggleCaption: "Sustituye el menú contextual del clic derecho.",
        urlCleanerRulesTitle: "Reglas de limpieza",
        urlCleanerRulesCaption: "Un sitio añade estos parámetros a sus propios enlaces para compartir y así rastrear de dónde vino el enlace. Marcado, el nombre se elimina al limpiar; sin marcar, permanece. Los nombres que añadas se pueden eliminar.",
        urlCleanerRulesCoverageCaption: "La lista abarca las distintas vías para compartir de un sitio (la página web, la app, una sala en directo), por eso es larga; un enlace real suele llevar solo entre dos y cuatro.",
        urlCleanerRulesAllSites: "Todos los sitios",
        urlCleanerRulesAddSite: "Añadir sitio",
        urlCleanerRulesParameterPlaceholder: "Nombre del parámetro",
        urlCleanerRulesMatchCaption: "Escribe el nombre a la izquierda del = , por ejemplo utm_source. Un nombre que coincide quita solo ese parámetro del enlace y deja el resto igual.",
        urlCleanerRulesAddButton: "Añadir",
        urlCleanerRemovedFormat: "Eliminados %@",
        switcherSearchPin: "Fijar búsqueda con S",
        switcherSearchPinCaption: "S inicia una búsqueda y fija el selector abierto: al escribir ya no aparecen caracteres especiales cuando el atajo usa ⌥, y una búsqueda que empieza por Q o W ya no cierra la ventana ni cierra la app por error.",
        invertVerticalScroll: "Invertir el desplazamiento vertical",
        invertHorizontalScroll: "Invertir el desplazamiento horizontal",
        switcherShowShortcutHints: "Mostrar indicaciones de atajos",
        switcherShowShortcutHintsCaption: "Muestra los atajos de apps y ventanas debajo de los iconos.",
        uninstallerHomebrewPackageFormat: "%@ también se eliminará de Homebrew.",
        shelfEdgeToggle: "Abrir cerca de un borde de la pantalla",
        shelfEdgeCaption: "Arrastra un archivo hacia el borde de la pantalla para que el estante asome. Suéltalo ahí, o retíralo y el estante se repliega.",
        focusFollowsMouseName: "El foco sigue al ratón",
        focusFollowsMouseCaption: "Enfoca y trae al frente la ventana bajo el puntero tras una breve pausa.",
        focusFollowsMouseDelay: "Retraso al pasar",
        switcherMinimizedPlacementLabel: "Ventanas minimizadas",
        switcherMinimizedPlacementNormal: "Orden normal",
        switcherMinimizedPlacementEnd: "Colocar al final",
        switcherMinimizedPlacementHidden: "Ocultar",
        switcherShowFullscreenWindows: "Mostrar ventanas en pantalla completa",
        switcherScreenPlacementLabel: "Mostrar en",
        switcherScreenPlacementPointer: "Pantalla con el puntero",
        switcherScreenPlacementMenuBar: "Pantalla con la barra de menús",
        switcherScreenPlacementActiveWindow: "Pantalla con la ventana activa",
        switcherScreenPlacementCaption: "En qué pantalla se abre el selector cuando hay más de una conectada.",
        smoothScrollResponseLabel: "Respuesta",
        mouseAccelerationName: "Desactivar la aceleración del ratón",
        mouseAccelerationCaption: "Elimina la aceleración del puntero para los ratones conectados. El ajuste anterior vuelve al desactivarlo o salir de \(AppInfo.name).",
        shelfClearOnClose: "Borrar al cerrar",
        shelfClearOnCloseCaption: "Vacía el estante solo al hacer clic en el botón de cierre. Ocultarlo automáticamente y contraerlo conservan los ítems."
    )
}
